//---------------------------------------------------------------------------*
//                                                                           *
//                   File 'include_typeGalgasListType.h'                     *
//                Generated by version 1.0.0 (LL(1) grammar)                 *
//                     october 29th, 2005, at 20h9'41"                       *
//                                                                           *
// This program is free software; you can redistribute it and/or modify it   *
// under the terms of the GNU General Public License as published by the     *
// Free Software Foundation.                                                 *
//                                                                           *
// This program is distributed in the hope it will be useful, but WITHOUT    *
// ANY WARRANTY; without even the implied warranty of MERCHANDIBILITY or     *
// FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for  *
// more details.                                                             *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

//---------------------------------------------------------------------------*
//                                                                           *
//                     class 'cPtr_typeGalgasListType'                       *
//                                                                           *
//---------------------------------------------------------------------------*

#ifndef typeGalgasListType_DEFINED
#define typeGalgasListType_DEFINED

class cPtr_typeGalgasListType : public cPtr_typeGalgasUndefinedListType {
  private : typedef cPtr_typeGalgasUndefinedListType inherited ;
//--- START OF USER ZONE 2

public : virtual void generateAttributeDeclaration (const GGS_lstring & nom,
                                                    AC_OutputStream & inHfile) ;
public : virtual void generateAttributeInitialization (const GGS_lstring & nom,
                                                       AC_OutputStream & inCppFile) ;
public : virtual void generateCppClassName (AC_OutputStream & fichier) const ;

//--- END OF USER ZONE 2

  public : cPtr_typeGalgasListType (const GGS_lstring & ,
                                const GGS_typeListeAttributsSemantiques & ) ;
  public : GGS_typeListeAttributsSemantiques  mNonExternAttributesList ;
  public : virtual void methode_acceptForeachInstruction (C_Lexique &,
                                GGS_lstring  ,
                                GGS_typeListeAttributsSemantiques & ,
                                GGS_localConstantBuildStyleEnum& ) ;
  public : virtual void methode_handleAddAssignOperatorCall (C_Lexique &,
                                GGS_location  ,
                                GGS_typeListeAttributsSemantiques & ,
                                GGS_bool& ) ;
  public : virtual void methode_handleConstructorCall (C_Lexique &,
                                GGS_lstring  ,
                                GGS_typeListeAttributsSemantiques & ) ;
  public : virtual const char * message_messageGalgasType (void) const ;
  public : static const char * static_string_message_messageGalgasType (void) ;
} ;

//---------------------------------------------------------------------------*

#endif

