//---------------------------------------------------------------------------*
//                                                                           *
//                  File 'include_typeParserInstruction.h'                   *
//         Generated by version GALGAS_BETA_VERSION (LL(1) grammar)          *
//                       june 6th, 2006, at 22h24'6"                         *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

//---------------------------------------------------------------------------*
//                                                                           *
//               abstract class 'cPtr_typeParserInstruction'                 *
//                                                                           *
//---------------------------------------------------------------------------*

class cPtr_typeParserInstruction : public cPtr_typeInstruction {
  private : typedef cPtr_typeInstruction inherited ;
//--- START OF USER ZONE 2

public : virtual bool isSyntacticInstruction (void) const { return true ; }

//--- END OF USER ZONE 2

  public : cPtr_typeParserInstruction (LOCATION_ARGS) ;
//--- Method for 'description' reader
  public : virtual void appendForDescription (C_Lexique & _inLexique, C_String & ioString COMMA_LOCATION_ARGS) const ;
} ;

//---------------------------------------------------------------------------*

