//---------------------------------------------------------------------------*
//                                                                           *
//                   File 'include_typeLogInstruction.h'                     *
//         Generated by version GALGAS_BETA_VERSION (LL(1) grammar)          *
//                     october 19th, 2006, at 19h47'17"                      *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

//---------------------------------------------------------------------------*
//                                                                           *
//                     class 'cPtr_typeLogInstruction'                       *
//                                                                           *
//---------------------------------------------------------------------------*

class cPtr_typeLogInstruction : public cPtr_typeInstruction {
  private : typedef cPtr_typeInstruction inherited ;
//--- START OF USER ZONE 2

public : virtual void generateInstruction (AC_OutputStream & inCppFile,
                                           const C_String & inLexiqueClassName,
                                           const C_String & inTargetFileName,
                                           sint32 & ioPrototypeIndex,
                                           const bool inGenerateDebug,
                                           const bool inGenerateSemanticInstructions) const ;
public : virtual bool isLexiqueFormalArgumentUsed (const bool inGenerateSemanticInstructions) const ;
public : virtual bool formalArgumentIsUsed (const GGS_typeCplusPlusName & inArgumentCppName,
                                            const bool inGenerateSemanticInstructions) const ;

//--- END OF USER ZONE 2

  public : cPtr_typeLogInstruction (const GGS_lstring & ,
                                const GGS_typeCplusPlusName &  COMMA_LOCATION_ARGS) ;
  public : GGS_lstring  mGalgasVariableName ;
  public : GGS_typeCplusPlusName  mLoggedVariable ;
//--- Method for 'description' reader
  public : virtual void appendForDescription (C_Lexique & _inLexique,
                                              C_String & ioString,
                                              const sint32 inIndentation
                                              COMMA_LOCATION_ARGS) const ;
} ;

//---------------------------------------------------------------------------*

