//---------------------------------------------------------------------------*
//                                                                           *
//                   File 'include_typeGalgasListType.h'                     *
//         Generated by version GALGAS_BETA_VERSION (LL(1) grammar)          *
//                     october 20th, 2006, at 10h23'20"                      *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

//---------------------------------------------------------------------------*
//                                                                           *
//                     class 'cPtr_typeGalgasListType'                       *
//                                                                           *
//---------------------------------------------------------------------------*

class cPtr_typeGalgasListType : public cPtr_typeGalgasUndefinedListType {
  private : typedef cPtr_typeGalgasUndefinedListType inherited ;
//--- START OF USER ZONE 2

public : virtual void generateAttributeDeclaration (const GGS_lstring & nom,
                                                    AC_OutputStream & inHfile) const ;

public : virtual void generateAttributeInitialization (const GGS_lstring & nom,
                                                       AC_OutputStream & inCppFile) const ;

public : virtual void generateCppClassName (AC_OutputStream & fichier) const ;

//--- END OF USER ZONE 2

  public : cPtr_typeGalgasListType (const GGS_lstring & ,
                                const GGS_typeListeAttributsSemantiques & ,
                                const GGS_L_EXsignature & ,
                                const GGS_L_EXsignature &  COMMA_LOCATION_ARGS) ;
  public : GGS_typeListeAttributsSemantiques  mNonExternAttributesList ;
  public : GGS_L_EXsignature  mExtractSignature ;
  public : GGS_L_EXsignature  mInputSignature ;
  public : virtual void method_acceptForeachInstruction (C_Lexique &,
                                GGS_lstring  ,
                                GGS_typeListeAttributsSemantiques & ,
                                GGS_localConstantBuildStyleEnum&  COMMA_LOCATION_ARGS) ;
  public : virtual void method_handleModifierCall (C_Lexique &,
                                GGS_lstring  ,
                                GGS_lstring  ,
                                GGS_L_EXsignature &  COMMA_LOCATION_ARGS) ;
  public : virtual void method_handleReaderInstructionCall (C_Lexique &,
                                GGS_lstring  ,
                                GGS_lstring  ,
                                GGS_L_EXsignature &  COMMA_LOCATION_ARGS) ;
  public : virtual void method_handleAddAssignOperatorCall (C_Lexique &,
                                GGS_location  ,
                                GGS_typeListeAttributsSemantiques &  COMMA_LOCATION_ARGS) ;
  public : virtual void method_handleConstructorCall (C_Lexique &,
                                GGS_lstring  ,
                                GGS_typeListeAttributsSemantiques &  COMMA_LOCATION_ARGS) ;
  public : virtual const char * message_messageGalgasType (void) const ;
  public : static const char * static_string_message_messageGalgasType (void) ;
//--- Method for 'description' reader
  public : virtual void appendForDescription (C_Lexique & _inLexique,
                                              C_String & ioString,
                                              const sint32 inIndentation
                                              COMMA_LOCATION_ARGS) const ;
} ;

//---------------------------------------------------------------------------*

