//---------------------------------------------------------------------------*
//                                                                           *
//                      File 'lexique_LL1_grammar.cpp'                       *
//         Generated by version GALGAS_BETA_VERSION (LL(1) grammar)          *
//                      march 31th, 2007, at 20h42'47"                       *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

//---------------------------------------------------------------------------*

#include "version_libpm.h"
#if LIBPM_VERSION != THE_LIBPM_VERSION
  #error "This file has been compiled with a version of GALGAS different than the version of libpm"
#endif

//---------------------------------------------------------------------------*

#include "lexique_LL1_grammar.h"

//---------------------------------------------------------------------------*

#ifndef DO_NOT_GENERATE_CHECKINGS
  #define SOURCE_FILE_AT_LINE(line) "lexique_LL1_grammar.ggs", line
  #define COMMA_SOURCE_FILE_AT_LINE(line) , SOURCE_FILE_AT_LINE(line)
#else
  #define SOURCE_FILE_AT_LINE(line) 
  #define COMMA_SOURCE_FILE_AT_LINE(line) 
#endif

//--- START OF USER ZONE 2


//--- END OF USER ZONE 2

//---------------------------------------------------------------------------*
//                                                                           *
//              L L ( 1 )    P R O D U C T I O N    R U L E S                *
//                                                                           *
//---------------------------------------------------------------------------*

#define TERMINAL(t)     ((t)+1)
#define NONTERMINAL(nt) ((-nt)-1)
#define END_PRODUCTION  (0)

static const sint16 gProductions [] = {
// At index 0 : <lexique_component_start_symbol>, in file 'lexique_model_builder.ggs', line 74
  TERMINAL (galgas_scanner::galgas_scanner_1_lexique) // $lexique$
, TERMINAL (galgas_scanner::galgas_scanner_1_identifier) // $identifier$
, TERMINAL (galgas_scanner::galgas_scanner_1__3A) // $:$
, NONTERMINAL (22) // <select_repeat_lexique_model_builder_0>
, TERMINAL (galgas_scanner::galgas_scanner_1_end) // $end$
, TERMINAL (galgas_scanner::galgas_scanner_1_lexique) // $lexique$
, TERMINAL (galgas_scanner::galgas_scanner_1__3B) // $;$
, END_PRODUCTION
// At index 8 : <lexical_attribute_declaration>, in file 'lexique_model_builder.ggs', line 458
, TERMINAL (galgas_scanner::galgas_scanner_1_type_5Fname) // $type_name$
, TERMINAL (galgas_scanner::galgas_scanner_1_identifier) // $identifier$
, TERMINAL (galgas_scanner::galgas_scanner_1__3B) // $;$
, END_PRODUCTION
// At index 12 : <style_declaration>, in file 'lexique_model_builder.ggs', line 490
, TERMINAL (galgas_scanner::galgas_scanner_1_style) // $style$
, TERMINAL (galgas_scanner::galgas_scanner_1_identifier) // $identifier$
, TERMINAL (galgas_scanner::galgas_scanner_1__2D_3E) // $->$
, TERMINAL (galgas_scanner::galgas_scanner_1_literal_5Fstring) // $literal_string$
, TERMINAL (galgas_scanner::galgas_scanner_1__3B) // $;$
, END_PRODUCTION
// At index 18 : <terminal_declaration>, in file 'lexique_model_builder.ggs', line 466
, TERMINAL (galgas_scanner::galgas_scanner_1_terminal) // $terminal$
, NONTERMINAL (41) // <select_repeat_lexique_model_builder_19>
, TERMINAL (galgas_scanner::galgas_scanner_1_error) // $error$
, TERMINAL (galgas_scanner::galgas_scanner_1_message) // $message$
, TERMINAL (galgas_scanner::galgas_scanner_1_literal_5Fstring) // $literal_string$
, NONTERMINAL (42) // <select_lexique_model_builder_20>
, TERMINAL (galgas_scanner::galgas_scanner_1__3B) // $;$
, END_PRODUCTION
// At index 26 : <lexical_list_declaration>, in file 'lexique_model_builder.ggs', line 415
, TERMINAL (galgas_scanner::galgas_scanner_1_list) // $list$
, TERMINAL (galgas_scanner::galgas_scanner_1_identifier) // $identifier$
, NONTERMINAL (37) // <select_repeat_lexique_model_builder_15>
, TERMINAL (galgas_scanner::galgas_scanner_1_error) // $error$
, TERMINAL (galgas_scanner::galgas_scanner_1_message) // $message$
, TERMINAL (galgas_scanner::galgas_scanner_1_literal_5Fstring) // $literal_string$
, NONTERMINAL (38) // <select_lexique_model_builder_16>
, TERMINAL (galgas_scanner::galgas_scanner_1__3A) // $:$
, NONTERMINAL (5) // <lexical_list_entry>
, NONTERMINAL (39) // <select_repeat_lexique_model_builder_17>
, TERMINAL (galgas_scanner::galgas_scanner_1__3B) // $;$
, END_PRODUCTION
// At index 38 : <lexical_list_entry>, in file 'lexique_model_builder.ggs', line 446
, TERMINAL (galgas_scanner::galgas_scanner_1_literal_5Fstring) // $literal_string$
, NONTERMINAL (40) // <select_lexique_model_builder_18>
, END_PRODUCTION
// At index 41 : <lexical_explicit_rule>, in file 'lexique_model_builder.ggs', line 124
, NONTERMINAL (13) // <lexical_expression>
, TERMINAL (galgas_scanner::galgas_scanner_1__3A) // $:$
, NONTERMINAL (24) // <select_repeat_lexique_model_builder_2>
, TERMINAL (galgas_scanner::galgas_scanner_1_end) // $end$
, TERMINAL (galgas_scanner::galgas_scanner_1_rule) // $rule$
, END_PRODUCTION
// At index 47 : <lexical_implicit_rule>, in file 'lexique_model_builder.ggs', line 117
, TERMINAL (galgas_scanner::galgas_scanner_1_list) // $list$
, TERMINAL (galgas_scanner::galgas_scanner_1_identifier) // $identifier$
, END_PRODUCTION
// At index 50 : <lexical_error_message_declaration>, in file 'lexique_model_builder.ggs', line 107
, TERMINAL (galgas_scanner::galgas_scanner_1_message) // $message$
, TERMINAL (galgas_scanner::galgas_scanner_1_identifier) // $identifier$
, TERMINAL (galgas_scanner::galgas_scanner_1__3A) // $:$
, TERMINAL (galgas_scanner::galgas_scanner_1_literal_5Fstring) // $literal_string$
, TERMINAL (galgas_scanner::galgas_scanner_1__3B) // $;$
, END_PRODUCTION
// At index 56 : <lexical_instruction>, in file 'lexique_model_builder.ggs', line 137
, TERMINAL (galgas_scanner::galgas_scanner_1_send) // $send$
, NONTERMINAL (10) // <lexical_send_instruction>
, TERMINAL (galgas_scanner::galgas_scanner_1__3B) // $;$
, END_PRODUCTION
// At index 60 : <lexical_instruction>, in file 'lexique_model_builder.ggs', line 184
, TERMINAL (galgas_scanner::galgas_scanner_1_repeat) // $repeat$
, NONTERMINAL (26) // <select_repeat_lexique_model_builder_4>
, NONTERMINAL (18) // <repeat_while_branch>
, NONTERMINAL (27) // <select_repeat_lexique_model_builder_5>
, TERMINAL (galgas_scanner::galgas_scanner_1_end) // $end$
, TERMINAL (galgas_scanner::galgas_scanner_1_repeat) // $repeat$
, TERMINAL (galgas_scanner::galgas_scanner_1__3B) // $;$
, END_PRODUCTION
// At index 68 : <lexical_instruction>, in file 'lexique_model_builder.ggs', line 213
, TERMINAL (galgas_scanner::galgas_scanner_1_select) // $select$
, NONTERMINAL (19) // <lexical_select_branch>
, NONTERMINAL (29) // <select_repeat_lexique_model_builder_7>
, TERMINAL (galgas_scanner::galgas_scanner_1_default) // $default$
, NONTERMINAL (30) // <select_repeat_lexique_model_builder_8>
, TERMINAL (galgas_scanner::galgas_scanner_1_end) // $end$
, TERMINAL (galgas_scanner::galgas_scanner_1_select) // $select$
, TERMINAL (galgas_scanner::galgas_scanner_1__3B) // $;$
, END_PRODUCTION
// At index 77 : <lexical_instruction>, in file 'lexique_model_builder.ggs', line 243
, TERMINAL (galgas_scanner::galgas_scanner_1_identifier) // $identifier$
, TERMINAL (galgas_scanner::galgas_scanner_1__28) // $($
, NONTERMINAL (12) // <lexical_action_effective_argument>
, NONTERMINAL (32) // <select_repeat_lexique_model_builder_10>
, TERMINAL (galgas_scanner::galgas_scanner_1__29) // $)$
, NONTERMINAL (33) // <select_lexique_model_builder_11>
, TERMINAL (galgas_scanner::galgas_scanner_1__3B) // $;$
, END_PRODUCTION
// At index 85 : <lexical_instruction>, in file 'lexique_model_builder.ggs', line 308
, TERMINAL (galgas_scanner::galgas_scanner_1_error) // $error$
, TERMINAL (galgas_scanner::galgas_scanner_1_identifier) // $identifier$
, TERMINAL (galgas_scanner::galgas_scanner_1__3B) // $;$
, END_PRODUCTION
// At index 89 : <lexical_instruction>, in file 'lexique_model_builder.ggs', line 316
, TERMINAL (galgas_scanner::galgas_scanner_1_drop) // $drop$
, TERMINAL (galgas_scanner::galgas_scanner_1_terminal) // $terminal$
, TERMINAL (galgas_scanner::galgas_scanner_1__3B) // $;$
, END_PRODUCTION
// At index 93 : <lexical_instruction>, in file 'lexique_model_builder.ggs', line 324
, TERMINAL (galgas_scanner::galgas_scanner_1_tag) // $tag$
, TERMINAL (galgas_scanner::galgas_scanner_1_identifier) // $identifier$
, TERMINAL (galgas_scanner::galgas_scanner_1__3B) // $;$
, END_PRODUCTION
// At index 97 : <lexical_instruction>, in file 'lexique_model_builder.ggs', line 332
, TERMINAL (galgas_scanner::galgas_scanner_1_rewind) // $rewind$
, TERMINAL (galgas_scanner::galgas_scanner_1_identifier) // $identifier$
, TERMINAL (galgas_scanner::galgas_scanner_1_send) // $send$
, TERMINAL (galgas_scanner::galgas_scanner_1_terminal) // $terminal$
, TERMINAL (galgas_scanner::galgas_scanner_1__3B) // $;$
, END_PRODUCTION
// At index 103 : <lexical_instruction>, in file 'lexique_model_builder.ggs', line 342
, TERMINAL (galgas_scanner::galgas_scanner_1_log) // $log$
, TERMINAL (galgas_scanner::galgas_scanner_1__3B) // $;$
, END_PRODUCTION
// At index 106 : <lexical_send_instruction>, in file 'lexique_model_builder.ggs', line 145
, TERMINAL (galgas_scanner::galgas_scanner_1_terminal) // $terminal$
, END_PRODUCTION
// At index 108 : <lexical_send_instruction>, in file 'lexique_model_builder.ggs', line 151
, NONTERMINAL (16) // <search_in_lexical_send>
, NONTERMINAL (25) // <select_repeat_lexique_model_builder_3>
, TERMINAL (galgas_scanner::galgas_scanner_1_default) // $default$
, NONTERMINAL (17) // <default_send_action>
, END_PRODUCTION
// At index 113 : <function_call_or_attribute>, in file 'lexique_model_builder.ggs', line 289
, END_PRODUCTION
// At index 114 : <function_call_or_attribute>, in file 'lexique_model_builder.ggs', line 295
, TERMINAL (galgas_scanner::galgas_scanner_1__28) // $($
, NONTERMINAL (12) // <lexical_action_effective_argument>
, NONTERMINAL (35) // <select_repeat_lexique_model_builder_13>
, TERMINAL (galgas_scanner::galgas_scanner_1__29) // $)$
, END_PRODUCTION
// At index 119 : <lexical_action_effective_argument>, in file 'lexique_model_builder.ggs', line 269
, TERMINAL (galgas_scanner::galgas_scanner_1_literal_5Fchar) // $literal_char$
, END_PRODUCTION
// At index 121 : <lexical_action_effective_argument>, in file 'lexique_model_builder.ggs', line 275
, TERMINAL (galgas_scanner::galgas_scanner_1__2A) // $*$
, END_PRODUCTION
// At index 123 : <lexical_action_effective_argument>, in file 'lexique_model_builder.ggs', line 281
, TERMINAL (galgas_scanner::galgas_scanner_1_identifier) // $identifier$
, NONTERMINAL (11) // <function_call_or_attribute>
, END_PRODUCTION
// At index 126 : <lexical_expression>, in file 'lexique_model_builder.ggs', line 349
, NONTERMINAL (14) // <lexical_term>
, END_PRODUCTION
// At index 128 : <lexical_term>, in file 'lexique_model_builder.ggs', line 355
, NONTERMINAL (15) // <lexical_factor>
, NONTERMINAL (36) // <select_repeat_lexique_model_builder_14>
, END_PRODUCTION
// At index 131 : <lexical_factor>, in file 'lexique_model_builder.ggs', line 378
, TERMINAL (galgas_scanner::galgas_scanner_1_literal_5Fstring) // $literal_string$
, END_PRODUCTION
// At index 133 : <lexical_factor>, in file 'lexique_model_builder.ggs', line 384
, TERMINAL (galgas_scanner::galgas_scanner_1__7E) // $~$
, TERMINAL (galgas_scanner::galgas_scanner_1_literal_5Fstring) // $literal_string$
, TERMINAL (galgas_scanner::galgas_scanner_1_error) // $error$
, TERMINAL (galgas_scanner::galgas_scanner_1_identifier) // $identifier$
, END_PRODUCTION
// At index 138 : <lexical_factor>, in file 'lexique_model_builder.ggs', line 393
, TERMINAL (galgas_scanner::galgas_scanner_1_literal_5Fchar) // $literal_char$
, NONTERMINAL (21) // <character_or_interval>
, END_PRODUCTION
// At index 141 : <search_in_lexical_send>, in file 'lexique_model_builder.ggs', line 162
, TERMINAL (galgas_scanner::galgas_scanner_1_search) // $search$
, TERMINAL (galgas_scanner::galgas_scanner_1_identifier) // $identifier$
, TERMINAL (galgas_scanner::galgas_scanner_1_in) // $in$
, TERMINAL (galgas_scanner::galgas_scanner_1_identifier) // $identifier$
, END_PRODUCTION
// At index 146 : <default_send_action>, in file 'lexique_model_builder.ggs', line 171
, TERMINAL (galgas_scanner::galgas_scanner_1_terminal) // $terminal$
, END_PRODUCTION
// At index 148 : <default_send_action>, in file 'lexique_model_builder.ggs', line 177
, TERMINAL (galgas_scanner::galgas_scanner_1_error) // $error$
, TERMINAL (galgas_scanner::galgas_scanner_1_identifier) // $identifier$
, END_PRODUCTION
// At index 151 : <repeat_while_branch>, in file 'lexique_model_builder.ggs', line 201
, TERMINAL (galgas_scanner::galgas_scanner_1_while) // $while$
, NONTERMINAL (13) // <lexical_expression>
, TERMINAL (galgas_scanner::galgas_scanner_1__3A) // $:$
, NONTERMINAL (28) // <select_repeat_lexique_model_builder_6>
, END_PRODUCTION
// At index 156 : <lexical_select_branch>, in file 'lexique_model_builder.ggs', line 231
, TERMINAL (galgas_scanner::galgas_scanner_1_when) // $when$
, NONTERMINAL (13) // <lexical_expression>
, TERMINAL (galgas_scanner::galgas_scanner_1__3A) // $:$
, NONTERMINAL (31) // <select_repeat_lexique_model_builder_9>
, END_PRODUCTION
// At index 161 : <build_lexical_or>, in file 'lexique_model_builder.ggs', line 368
, END_PRODUCTION
// At index 162 : <character_or_interval>, in file 'lexique_model_builder.ggs', line 401
, END_PRODUCTION
// At index 163 : <character_or_interval>, in file 'lexique_model_builder.ggs', line 407
, TERMINAL (galgas_scanner::galgas_scanner_1__2D_3E) // $->$
, TERMINAL (galgas_scanner::galgas_scanner_1_literal_5Fchar) // $literal_char$
, END_PRODUCTION
//---- Added productions from 'select' and 'repeat' instructions
// At index 166 : <select_repeat_lexique_model_builder_0>, in file 'lexique_model_builder.ggs', line 81
, END_PRODUCTION
// At index 167 : <select_repeat_lexique_model_builder_0>, in file 'lexique_model_builder.ggs', line 81
, NONTERMINAL (1) // <lexical_attribute_declaration>
, NONTERMINAL (22) // <select_repeat_lexique_model_builder_0>
, END_PRODUCTION
// At index 170 : <select_repeat_lexique_model_builder_0>, in file 'lexique_model_builder.ggs', line 81
, NONTERMINAL (2) // <style_declaration>
, NONTERMINAL (22) // <select_repeat_lexique_model_builder_0>
, END_PRODUCTION
// At index 173 : <select_repeat_lexique_model_builder_0>, in file 'lexique_model_builder.ggs', line 81
, NONTERMINAL (3) // <terminal_declaration>
, NONTERMINAL (22) // <select_repeat_lexique_model_builder_0>
, END_PRODUCTION
// At index 176 : <select_repeat_lexique_model_builder_0>, in file 'lexique_model_builder.ggs', line 81
, NONTERMINAL (4) // <lexical_list_declaration>
, NONTERMINAL (22) // <select_repeat_lexique_model_builder_0>
, END_PRODUCTION
// At index 179 : <select_repeat_lexique_model_builder_0>, in file 'lexique_model_builder.ggs', line 81
, TERMINAL (galgas_scanner::galgas_scanner_1_rule) // $rule$
, NONTERMINAL (23) // <select_lexique_model_builder_1>
, TERMINAL (galgas_scanner::galgas_scanner_1__3B) // $;$
, NONTERMINAL (22) // <select_repeat_lexique_model_builder_0>
, END_PRODUCTION
// At index 184 : <select_repeat_lexique_model_builder_0>, in file 'lexique_model_builder.ggs', line 81
, NONTERMINAL (8) // <lexical_error_message_declaration>
, NONTERMINAL (22) // <select_repeat_lexique_model_builder_0>
, END_PRODUCTION
// At index 187 : <select_lexique_model_builder_1>, in file 'lexique_model_builder.ggs', line 92
, NONTERMINAL (6) // <lexical_explicit_rule>
, END_PRODUCTION
// At index 189 : <select_lexique_model_builder_1>, in file 'lexique_model_builder.ggs', line 92
, NONTERMINAL (7) // <lexical_implicit_rule>
, END_PRODUCTION
// At index 191 : <select_repeat_lexique_model_builder_2>, in file 'lexique_model_builder.ggs', line 128
, END_PRODUCTION
// At index 192 : <select_repeat_lexique_model_builder_2>, in file 'lexique_model_builder.ggs', line 128
, NONTERMINAL (9) // <lexical_instruction>
, NONTERMINAL (24) // <select_repeat_lexique_model_builder_2>
, END_PRODUCTION
// At index 195 : <select_repeat_lexique_model_builder_3>, in file 'lexique_model_builder.ggs', line 153
, END_PRODUCTION
// At index 196 : <select_repeat_lexique_model_builder_3>, in file 'lexique_model_builder.ggs', line 153
, NONTERMINAL (16) // <search_in_lexical_send>
, NONTERMINAL (25) // <select_repeat_lexique_model_builder_3>
, END_PRODUCTION
// At index 199 : <select_repeat_lexique_model_builder_4>, in file 'lexique_model_builder.ggs', line 187
, END_PRODUCTION
// At index 200 : <select_repeat_lexique_model_builder_4>, in file 'lexique_model_builder.ggs', line 187
, NONTERMINAL (9) // <lexical_instruction>
, NONTERMINAL (26) // <select_repeat_lexique_model_builder_4>
, END_PRODUCTION
// At index 203 : <select_repeat_lexique_model_builder_5>, in file 'lexique_model_builder.ggs', line 191
, END_PRODUCTION
// At index 204 : <select_repeat_lexique_model_builder_5>, in file 'lexique_model_builder.ggs', line 191
, NONTERMINAL (18) // <repeat_while_branch>
, NONTERMINAL (27) // <select_repeat_lexique_model_builder_5>
, END_PRODUCTION
// At index 207 : <select_repeat_lexique_model_builder_6>, in file 'lexique_model_builder.ggs', line 206
, END_PRODUCTION
// At index 208 : <select_repeat_lexique_model_builder_6>, in file 'lexique_model_builder.ggs', line 206
, NONTERMINAL (9) // <lexical_instruction>
, NONTERMINAL (28) // <select_repeat_lexique_model_builder_6>
, END_PRODUCTION
// At index 211 : <select_repeat_lexique_model_builder_7>, in file 'lexique_model_builder.ggs', line 216
, END_PRODUCTION
// At index 212 : <select_repeat_lexique_model_builder_7>, in file 'lexique_model_builder.ggs', line 216
, NONTERMINAL (19) // <lexical_select_branch>
, NONTERMINAL (29) // <select_repeat_lexique_model_builder_7>
, END_PRODUCTION
// At index 215 : <select_repeat_lexique_model_builder_8>, in file 'lexique_model_builder.ggs', line 221
, END_PRODUCTION
// At index 216 : <select_repeat_lexique_model_builder_8>, in file 'lexique_model_builder.ggs', line 221
, NONTERMINAL (9) // <lexical_instruction>
, NONTERMINAL (30) // <select_repeat_lexique_model_builder_8>
, END_PRODUCTION
// At index 219 : <select_repeat_lexique_model_builder_9>, in file 'lexique_model_builder.ggs', line 236
, END_PRODUCTION
// At index 220 : <select_repeat_lexique_model_builder_9>, in file 'lexique_model_builder.ggs', line 236
, NONTERMINAL (9) // <lexical_instruction>
, NONTERMINAL (31) // <select_repeat_lexique_model_builder_9>
, END_PRODUCTION
// At index 223 : <select_repeat_lexique_model_builder_10>, in file 'lexique_model_builder.ggs', line 247
, END_PRODUCTION
// At index 224 : <select_repeat_lexique_model_builder_10>, in file 'lexique_model_builder.ggs', line 247
, TERMINAL (galgas_scanner::galgas_scanner_1__2C) // $,$
, NONTERMINAL (12) // <lexical_action_effective_argument>
, NONTERMINAL (32) // <select_repeat_lexique_model_builder_10>
, END_PRODUCTION
// At index 228 : <select_lexique_model_builder_11>, in file 'lexique_model_builder.ggs', line 254
, END_PRODUCTION
// At index 229 : <select_lexique_model_builder_11>, in file 'lexique_model_builder.ggs', line 254
, TERMINAL (galgas_scanner::galgas_scanner_1_error) // $error$
, TERMINAL (galgas_scanner::galgas_scanner_1_identifier) // $identifier$
, NONTERMINAL (34) // <select_repeat_lexique_model_builder_12>
, END_PRODUCTION
// At index 233 : <select_repeat_lexique_model_builder_12>, in file 'lexique_model_builder.ggs', line 257
, END_PRODUCTION
// At index 234 : <select_repeat_lexique_model_builder_12>, in file 'lexique_model_builder.ggs', line 257
, TERMINAL (galgas_scanner::galgas_scanner_1__2C) // $,$
, TERMINAL (galgas_scanner::galgas_scanner_1_identifier) // $identifier$
, NONTERMINAL (34) // <select_repeat_lexique_model_builder_12>
, END_PRODUCTION
// At index 238 : <select_repeat_lexique_model_builder_13>, in file 'lexique_model_builder.ggs', line 299
, END_PRODUCTION
// At index 239 : <select_repeat_lexique_model_builder_13>, in file 'lexique_model_builder.ggs', line 299
, TERMINAL (galgas_scanner::galgas_scanner_1__2C) // $,$
, NONTERMINAL (12) // <lexical_action_effective_argument>
, NONTERMINAL (35) // <select_repeat_lexique_model_builder_13>
, END_PRODUCTION
// At index 243 : <select_repeat_lexique_model_builder_14>, in file 'lexique_model_builder.ggs', line 358
, END_PRODUCTION
// At index 244 : <select_repeat_lexique_model_builder_14>, in file 'lexique_model_builder.ggs', line 358
, TERMINAL (galgas_scanner::galgas_scanner_1__7C) // $|$
, NONTERMINAL (15) // <lexical_factor>
, NONTERMINAL (20) // <build_lexical_or>
, NONTERMINAL (36) // <select_repeat_lexique_model_builder_14>
, END_PRODUCTION
// At index 249 : <select_repeat_lexique_model_builder_15>, in file 'lexique_model_builder.ggs', line 420
, END_PRODUCTION
// At index 250 : <select_repeat_lexique_model_builder_15>, in file 'lexique_model_builder.ggs', line 420
, TERMINAL (galgas_scanner::galgas_scanner_1__21) // $!$
, TERMINAL (galgas_scanner::galgas_scanner_1_identifier) // $identifier$
, NONTERMINAL (37) // <select_repeat_lexique_model_builder_15>
, END_PRODUCTION
// At index 254 : <select_lexique_model_builder_16>, in file 'lexique_model_builder.ggs', line 430
, TERMINAL (galgas_scanner::galgas_scanner_1_style) // $style$
, TERMINAL (galgas_scanner::galgas_scanner_1_identifier) // $identifier$
, END_PRODUCTION
// At index 257 : <select_lexique_model_builder_16>, in file 'lexique_model_builder.ggs', line 430
, END_PRODUCTION
// At index 258 : <select_repeat_lexique_model_builder_17>, in file 'lexique_model_builder.ggs', line 437
, END_PRODUCTION
// At index 259 : <select_repeat_lexique_model_builder_17>, in file 'lexique_model_builder.ggs', line 437
, TERMINAL (galgas_scanner::galgas_scanner_1__2C) // $,$
, NONTERMINAL (5) // <lexical_list_entry>
, NONTERMINAL (39) // <select_repeat_lexique_model_builder_17>
, END_PRODUCTION
// At index 263 : <select_lexique_model_builder_18>, in file 'lexique_model_builder.ggs', line 449
, TERMINAL (galgas_scanner::galgas_scanner_1__2D_3E) // $->$
, TERMINAL (galgas_scanner::galgas_scanner_1_literal_5Fstring) // $literal_string$
, END_PRODUCTION
// At index 266 : <select_lexique_model_builder_18>, in file 'lexique_model_builder.ggs', line 449
, END_PRODUCTION
// At index 267 : <select_repeat_lexique_model_builder_19>, in file 'lexique_model_builder.ggs', line 470
, END_PRODUCTION
// At index 268 : <select_repeat_lexique_model_builder_19>, in file 'lexique_model_builder.ggs', line 470
, TERMINAL (galgas_scanner::galgas_scanner_1__21) // $!$
, TERMINAL (galgas_scanner::galgas_scanner_1_identifier) // $identifier$
, NONTERMINAL (41) // <select_repeat_lexique_model_builder_19>
, END_PRODUCTION
// At index 272 : <select_lexique_model_builder_20>, in file 'lexique_model_builder.ggs', line 480
, TERMINAL (galgas_scanner::galgas_scanner_1_style) // $style$
, TERMINAL (galgas_scanner::galgas_scanner_1_identifier) // $identifier$
, END_PRODUCTION
// At index 275 : <select_lexique_model_builder_20>, in file 'lexique_model_builder.ggs', line 480
, END_PRODUCTION
// At index 276 : <>, in file '.ggs', line 0
, NONTERMINAL (0) // <lexique_component_start_symbol>
, END_PRODUCTION
} ;

//---------------------------------------------------------------------------*
//                                                                           *
//                     P R O D U C T I O N    N A M E S                      *
//                                                                           *
//---------------------------------------------------------------------------*

static const char * gProductionNames [86] = {
 "<lexique_component_start_symbol>, in file 'lexique_model_builder.ggs', line 74", // at index 0
 "<lexical_attribute_declaration>, in file 'lexique_model_builder.ggs', line 458", // at index 1
 "<style_declaration>, in file 'lexique_model_builder.ggs', line 490", // at index 2
 "<terminal_declaration>, in file 'lexique_model_builder.ggs', line 466", // at index 3
 "<lexical_list_declaration>, in file 'lexique_model_builder.ggs', line 415", // at index 4
 "<lexical_list_entry>, in file 'lexique_model_builder.ggs', line 446", // at index 5
 "<lexical_explicit_rule>, in file 'lexique_model_builder.ggs', line 124", // at index 6
 "<lexical_implicit_rule>, in file 'lexique_model_builder.ggs', line 117", // at index 7
 "<lexical_error_message_declaration>, in file 'lexique_model_builder.ggs', line 107", // at index 8
 "<lexical_instruction>, in file 'lexique_model_builder.ggs', line 137", // at index 9
 "<lexical_instruction>, in file 'lexique_model_builder.ggs', line 184", // at index 10
 "<lexical_instruction>, in file 'lexique_model_builder.ggs', line 213", // at index 11
 "<lexical_instruction>, in file 'lexique_model_builder.ggs', line 243", // at index 12
 "<lexical_instruction>, in file 'lexique_model_builder.ggs', line 308", // at index 13
 "<lexical_instruction>, in file 'lexique_model_builder.ggs', line 316", // at index 14
 "<lexical_instruction>, in file 'lexique_model_builder.ggs', line 324", // at index 15
 "<lexical_instruction>, in file 'lexique_model_builder.ggs', line 332", // at index 16
 "<lexical_instruction>, in file 'lexique_model_builder.ggs', line 342", // at index 17
 "<lexical_send_instruction>, in file 'lexique_model_builder.ggs', line 145", // at index 18
 "<lexical_send_instruction>, in file 'lexique_model_builder.ggs', line 151", // at index 19
 "<function_call_or_attribute>, in file 'lexique_model_builder.ggs', line 289", // at index 20
 "<function_call_or_attribute>, in file 'lexique_model_builder.ggs', line 295", // at index 21
 "<lexical_action_effective_argument>, in file 'lexique_model_builder.ggs', line 269", // at index 22
 "<lexical_action_effective_argument>, in file 'lexique_model_builder.ggs', line 275", // at index 23
 "<lexical_action_effective_argument>, in file 'lexique_model_builder.ggs', line 281", // at index 24
 "<lexical_expression>, in file 'lexique_model_builder.ggs', line 349", // at index 25
 "<lexical_term>, in file 'lexique_model_builder.ggs', line 355", // at index 26
 "<lexical_factor>, in file 'lexique_model_builder.ggs', line 378", // at index 27
 "<lexical_factor>, in file 'lexique_model_builder.ggs', line 384", // at index 28
 "<lexical_factor>, in file 'lexique_model_builder.ggs', line 393", // at index 29
 "<search_in_lexical_send>, in file 'lexique_model_builder.ggs', line 162", // at index 30
 "<default_send_action>, in file 'lexique_model_builder.ggs', line 171", // at index 31
 "<default_send_action>, in file 'lexique_model_builder.ggs', line 177", // at index 32
 "<repeat_while_branch>, in file 'lexique_model_builder.ggs', line 201", // at index 33
 "<lexical_select_branch>, in file 'lexique_model_builder.ggs', line 231", // at index 34
 "<build_lexical_or>, in file 'lexique_model_builder.ggs', line 368", // at index 35
 "<character_or_interval>, in file 'lexique_model_builder.ggs', line 401", // at index 36
 "<character_or_interval>, in file 'lexique_model_builder.ggs', line 407", // at index 37
 "<select_repeat_lexique_model_builder_0>, in file 'lexique_model_builder.ggs', line 81", // at index 38
 "<select_repeat_lexique_model_builder_0>, in file 'lexique_model_builder.ggs', line 81", // at index 39
 "<select_repeat_lexique_model_builder_0>, in file 'lexique_model_builder.ggs', line 81", // at index 40
 "<select_repeat_lexique_model_builder_0>, in file 'lexique_model_builder.ggs', line 81", // at index 41
 "<select_repeat_lexique_model_builder_0>, in file 'lexique_model_builder.ggs', line 81", // at index 42
 "<select_repeat_lexique_model_builder_0>, in file 'lexique_model_builder.ggs', line 81", // at index 43
 "<select_repeat_lexique_model_builder_0>, in file 'lexique_model_builder.ggs', line 81", // at index 44
 "<select_lexique_model_builder_1>, in file 'lexique_model_builder.ggs', line 92", // at index 45
 "<select_lexique_model_builder_1>, in file 'lexique_model_builder.ggs', line 92", // at index 46
 "<select_repeat_lexique_model_builder_2>, in file 'lexique_model_builder.ggs', line 128", // at index 47
 "<select_repeat_lexique_model_builder_2>, in file 'lexique_model_builder.ggs', line 128", // at index 48
 "<select_repeat_lexique_model_builder_3>, in file 'lexique_model_builder.ggs', line 153", // at index 49
 "<select_repeat_lexique_model_builder_3>, in file 'lexique_model_builder.ggs', line 153", // at index 50
 "<select_repeat_lexique_model_builder_4>, in file 'lexique_model_builder.ggs', line 187", // at index 51
 "<select_repeat_lexique_model_builder_4>, in file 'lexique_model_builder.ggs', line 187", // at index 52
 "<select_repeat_lexique_model_builder_5>, in file 'lexique_model_builder.ggs', line 191", // at index 53
 "<select_repeat_lexique_model_builder_5>, in file 'lexique_model_builder.ggs', line 191", // at index 54
 "<select_repeat_lexique_model_builder_6>, in file 'lexique_model_builder.ggs', line 206", // at index 55
 "<select_repeat_lexique_model_builder_6>, in file 'lexique_model_builder.ggs', line 206", // at index 56
 "<select_repeat_lexique_model_builder_7>, in file 'lexique_model_builder.ggs', line 216", // at index 57
 "<select_repeat_lexique_model_builder_7>, in file 'lexique_model_builder.ggs', line 216", // at index 58
 "<select_repeat_lexique_model_builder_8>, in file 'lexique_model_builder.ggs', line 221", // at index 59
 "<select_repeat_lexique_model_builder_8>, in file 'lexique_model_builder.ggs', line 221", // at index 60
 "<select_repeat_lexique_model_builder_9>, in file 'lexique_model_builder.ggs', line 236", // at index 61
 "<select_repeat_lexique_model_builder_9>, in file 'lexique_model_builder.ggs', line 236", // at index 62
 "<select_repeat_lexique_model_builder_10>, in file 'lexique_model_builder.ggs', line 247", // at index 63
 "<select_repeat_lexique_model_builder_10>, in file 'lexique_model_builder.ggs', line 247", // at index 64
 "<select_lexique_model_builder_11>, in file 'lexique_model_builder.ggs', line 254", // at index 65
 "<select_lexique_model_builder_11>, in file 'lexique_model_builder.ggs', line 254", // at index 66
 "<select_repeat_lexique_model_builder_12>, in file 'lexique_model_builder.ggs', line 257", // at index 67
 "<select_repeat_lexique_model_builder_12>, in file 'lexique_model_builder.ggs', line 257", // at index 68
 "<select_repeat_lexique_model_builder_13>, in file 'lexique_model_builder.ggs', line 299", // at index 69
 "<select_repeat_lexique_model_builder_13>, in file 'lexique_model_builder.ggs', line 299", // at index 70
 "<select_repeat_lexique_model_builder_14>, in file 'lexique_model_builder.ggs', line 358", // at index 71
 "<select_repeat_lexique_model_builder_14>, in file 'lexique_model_builder.ggs', line 358", // at index 72
 "<select_repeat_lexique_model_builder_15>, in file 'lexique_model_builder.ggs', line 420", // at index 73
 "<select_repeat_lexique_model_builder_15>, in file 'lexique_model_builder.ggs', line 420", // at index 74
 "<select_lexique_model_builder_16>, in file 'lexique_model_builder.ggs', line 430", // at index 75
 "<select_lexique_model_builder_16>, in file 'lexique_model_builder.ggs', line 430", // at index 76
 "<select_repeat_lexique_model_builder_17>, in file 'lexique_model_builder.ggs', line 437", // at index 77
 "<select_repeat_lexique_model_builder_17>, in file 'lexique_model_builder.ggs', line 437", // at index 78
 "<select_lexique_model_builder_18>, in file 'lexique_model_builder.ggs', line 449", // at index 79
 "<select_lexique_model_builder_18>, in file 'lexique_model_builder.ggs', line 449", // at index 80
 "<select_repeat_lexique_model_builder_19>, in file 'lexique_model_builder.ggs', line 470", // at index 81
 "<select_repeat_lexique_model_builder_19>, in file 'lexique_model_builder.ggs', line 470", // at index 82
 "<select_lexique_model_builder_20>, in file 'lexique_model_builder.ggs', line 480", // at index 83
 "<select_lexique_model_builder_20>, in file 'lexique_model_builder.ggs', line 480", // at index 84
 "<>, in file '.ggs', line 0" // at index 85
} ;

//---------------------------------------------------------------------------*
//                                                                           *
//            L L ( 1 )    P R O D U C T I O N    I N D E X E S              *
//                                                                           *
//---------------------------------------------------------------------------*

static const sint16 gProductionIndexes [86] = {
0, // index 0 : <lexique_component_start_symbol>, in file 'lexique_model_builder.ggs', line 74
8, // index 1 : <lexical_attribute_declaration>, in file 'lexique_model_builder.ggs', line 458
12, // index 2 : <style_declaration>, in file 'lexique_model_builder.ggs', line 490
18, // index 3 : <terminal_declaration>, in file 'lexique_model_builder.ggs', line 466
26, // index 4 : <lexical_list_declaration>, in file 'lexique_model_builder.ggs', line 415
38, // index 5 : <lexical_list_entry>, in file 'lexique_model_builder.ggs', line 446
41, // index 6 : <lexical_explicit_rule>, in file 'lexique_model_builder.ggs', line 124
47, // index 7 : <lexical_implicit_rule>, in file 'lexique_model_builder.ggs', line 117
50, // index 8 : <lexical_error_message_declaration>, in file 'lexique_model_builder.ggs', line 107
56, // index 9 : <lexical_instruction>, in file 'lexique_model_builder.ggs', line 137
60, // index 10 : <lexical_instruction>, in file 'lexique_model_builder.ggs', line 184
68, // index 11 : <lexical_instruction>, in file 'lexique_model_builder.ggs', line 213
77, // index 12 : <lexical_instruction>, in file 'lexique_model_builder.ggs', line 243
85, // index 13 : <lexical_instruction>, in file 'lexique_model_builder.ggs', line 308
89, // index 14 : <lexical_instruction>, in file 'lexique_model_builder.ggs', line 316
93, // index 15 : <lexical_instruction>, in file 'lexique_model_builder.ggs', line 324
97, // index 16 : <lexical_instruction>, in file 'lexique_model_builder.ggs', line 332
103, // index 17 : <lexical_instruction>, in file 'lexique_model_builder.ggs', line 342
106, // index 18 : <lexical_send_instruction>, in file 'lexique_model_builder.ggs', line 145
108, // index 19 : <lexical_send_instruction>, in file 'lexique_model_builder.ggs', line 151
113, // index 20 : <function_call_or_attribute>, in file 'lexique_model_builder.ggs', line 289
114, // index 21 : <function_call_or_attribute>, in file 'lexique_model_builder.ggs', line 295
119, // index 22 : <lexical_action_effective_argument>, in file 'lexique_model_builder.ggs', line 269
121, // index 23 : <lexical_action_effective_argument>, in file 'lexique_model_builder.ggs', line 275
123, // index 24 : <lexical_action_effective_argument>, in file 'lexique_model_builder.ggs', line 281
126, // index 25 : <lexical_expression>, in file 'lexique_model_builder.ggs', line 349
128, // index 26 : <lexical_term>, in file 'lexique_model_builder.ggs', line 355
131, // index 27 : <lexical_factor>, in file 'lexique_model_builder.ggs', line 378
133, // index 28 : <lexical_factor>, in file 'lexique_model_builder.ggs', line 384
138, // index 29 : <lexical_factor>, in file 'lexique_model_builder.ggs', line 393
141, // index 30 : <search_in_lexical_send>, in file 'lexique_model_builder.ggs', line 162
146, // index 31 : <default_send_action>, in file 'lexique_model_builder.ggs', line 171
148, // index 32 : <default_send_action>, in file 'lexique_model_builder.ggs', line 177
151, // index 33 : <repeat_while_branch>, in file 'lexique_model_builder.ggs', line 201
156, // index 34 : <lexical_select_branch>, in file 'lexique_model_builder.ggs', line 231
161, // index 35 : <build_lexical_or>, in file 'lexique_model_builder.ggs', line 368
162, // index 36 : <character_or_interval>, in file 'lexique_model_builder.ggs', line 401
163, // index 37 : <character_or_interval>, in file 'lexique_model_builder.ggs', line 407
166, // index 38 : <select_repeat_lexique_model_builder_0>, in file 'lexique_model_builder.ggs', line 81
167, // index 39 : <select_repeat_lexique_model_builder_0>, in file 'lexique_model_builder.ggs', line 81
170, // index 40 : <select_repeat_lexique_model_builder_0>, in file 'lexique_model_builder.ggs', line 81
173, // index 41 : <select_repeat_lexique_model_builder_0>, in file 'lexique_model_builder.ggs', line 81
176, // index 42 : <select_repeat_lexique_model_builder_0>, in file 'lexique_model_builder.ggs', line 81
179, // index 43 : <select_repeat_lexique_model_builder_0>, in file 'lexique_model_builder.ggs', line 81
184, // index 44 : <select_repeat_lexique_model_builder_0>, in file 'lexique_model_builder.ggs', line 81
187, // index 45 : <select_lexique_model_builder_1>, in file 'lexique_model_builder.ggs', line 92
189, // index 46 : <select_lexique_model_builder_1>, in file 'lexique_model_builder.ggs', line 92
191, // index 47 : <select_repeat_lexique_model_builder_2>, in file 'lexique_model_builder.ggs', line 128
192, // index 48 : <select_repeat_lexique_model_builder_2>, in file 'lexique_model_builder.ggs', line 128
195, // index 49 : <select_repeat_lexique_model_builder_3>, in file 'lexique_model_builder.ggs', line 153
196, // index 50 : <select_repeat_lexique_model_builder_3>, in file 'lexique_model_builder.ggs', line 153
199, // index 51 : <select_repeat_lexique_model_builder_4>, in file 'lexique_model_builder.ggs', line 187
200, // index 52 : <select_repeat_lexique_model_builder_4>, in file 'lexique_model_builder.ggs', line 187
203, // index 53 : <select_repeat_lexique_model_builder_5>, in file 'lexique_model_builder.ggs', line 191
204, // index 54 : <select_repeat_lexique_model_builder_5>, in file 'lexique_model_builder.ggs', line 191
207, // index 55 : <select_repeat_lexique_model_builder_6>, in file 'lexique_model_builder.ggs', line 206
208, // index 56 : <select_repeat_lexique_model_builder_6>, in file 'lexique_model_builder.ggs', line 206
211, // index 57 : <select_repeat_lexique_model_builder_7>, in file 'lexique_model_builder.ggs', line 216
212, // index 58 : <select_repeat_lexique_model_builder_7>, in file 'lexique_model_builder.ggs', line 216
215, // index 59 : <select_repeat_lexique_model_builder_8>, in file 'lexique_model_builder.ggs', line 221
216, // index 60 : <select_repeat_lexique_model_builder_8>, in file 'lexique_model_builder.ggs', line 221
219, // index 61 : <select_repeat_lexique_model_builder_9>, in file 'lexique_model_builder.ggs', line 236
220, // index 62 : <select_repeat_lexique_model_builder_9>, in file 'lexique_model_builder.ggs', line 236
223, // index 63 : <select_repeat_lexique_model_builder_10>, in file 'lexique_model_builder.ggs', line 247
224, // index 64 : <select_repeat_lexique_model_builder_10>, in file 'lexique_model_builder.ggs', line 247
228, // index 65 : <select_lexique_model_builder_11>, in file 'lexique_model_builder.ggs', line 254
229, // index 66 : <select_lexique_model_builder_11>, in file 'lexique_model_builder.ggs', line 254
233, // index 67 : <select_repeat_lexique_model_builder_12>, in file 'lexique_model_builder.ggs', line 257
234, // index 68 : <select_repeat_lexique_model_builder_12>, in file 'lexique_model_builder.ggs', line 257
238, // index 69 : <select_repeat_lexique_model_builder_13>, in file 'lexique_model_builder.ggs', line 299
239, // index 70 : <select_repeat_lexique_model_builder_13>, in file 'lexique_model_builder.ggs', line 299
243, // index 71 : <select_repeat_lexique_model_builder_14>, in file 'lexique_model_builder.ggs', line 358
244, // index 72 : <select_repeat_lexique_model_builder_14>, in file 'lexique_model_builder.ggs', line 358
249, // index 73 : <select_repeat_lexique_model_builder_15>, in file 'lexique_model_builder.ggs', line 420
250, // index 74 : <select_repeat_lexique_model_builder_15>, in file 'lexique_model_builder.ggs', line 420
254, // index 75 : <select_lexique_model_builder_16>, in file 'lexique_model_builder.ggs', line 430
257, // index 76 : <select_lexique_model_builder_16>, in file 'lexique_model_builder.ggs', line 430
258, // index 77 : <select_repeat_lexique_model_builder_17>, in file 'lexique_model_builder.ggs', line 437
259, // index 78 : <select_repeat_lexique_model_builder_17>, in file 'lexique_model_builder.ggs', line 437
263, // index 79 : <select_lexique_model_builder_18>, in file 'lexique_model_builder.ggs', line 449
266, // index 80 : <select_lexique_model_builder_18>, in file 'lexique_model_builder.ggs', line 449
267, // index 81 : <select_repeat_lexique_model_builder_19>, in file 'lexique_model_builder.ggs', line 470
268, // index 82 : <select_repeat_lexique_model_builder_19>, in file 'lexique_model_builder.ggs', line 470
272, // index 83 : <select_lexique_model_builder_20>, in file 'lexique_model_builder.ggs', line 480
275, // index 84 : <select_lexique_model_builder_20>, in file 'lexique_model_builder.ggs', line 480
276 // index 85 : <>, in file '.ggs', line 0
} ;

//---------------------------------------------------------------------------*
//                                                                           *
//      L L ( 1 )    F I R S T    P R O D U C T I O N    I N D E X E S       *
//                                                                           *
//---------------------------------------------------------------------------*

static const sint16 gFirstProductionIndexes [45] = {
0, // at 0 : <lexique_component_start_symbol>
1, // at 1 : <lexical_attribute_declaration>
2, // at 2 : <style_declaration>
3, // at 3 : <terminal_declaration>
4, // at 4 : <lexical_list_declaration>
5, // at 5 : <lexical_list_entry>
6, // at 6 : <lexical_explicit_rule>
7, // at 7 : <lexical_implicit_rule>
8, // at 8 : <lexical_error_message_declaration>
9, // at 9 : <lexical_instruction>
18, // at 10 : <lexical_send_instruction>
20, // at 11 : <function_call_or_attribute>
22, // at 12 : <lexical_action_effective_argument>
25, // at 13 : <lexical_expression>
26, // at 14 : <lexical_term>
27, // at 15 : <lexical_factor>
30, // at 16 : <search_in_lexical_send>
31, // at 17 : <default_send_action>
33, // at 18 : <repeat_while_branch>
34, // at 19 : <lexical_select_branch>
35, // at 20 : <build_lexical_or>
36, // at 21 : <character_or_interval>
38, // at 22 : <select_repeat_lexique_model_builder_0>
45, // at 23 : <select_lexique_model_builder_1>
47, // at 24 : <select_repeat_lexique_model_builder_2>
49, // at 25 : <select_repeat_lexique_model_builder_3>
51, // at 26 : <select_repeat_lexique_model_builder_4>
53, // at 27 : <select_repeat_lexique_model_builder_5>
55, // at 28 : <select_repeat_lexique_model_builder_6>
57, // at 29 : <select_repeat_lexique_model_builder_7>
59, // at 30 : <select_repeat_lexique_model_builder_8>
61, // at 31 : <select_repeat_lexique_model_builder_9>
63, // at 32 : <select_repeat_lexique_model_builder_10>
65, // at 33 : <select_lexique_model_builder_11>
67, // at 34 : <select_repeat_lexique_model_builder_12>
69, // at 35 : <select_repeat_lexique_model_builder_13>
71, // at 36 : <select_repeat_lexique_model_builder_14>
73, // at 37 : <select_repeat_lexique_model_builder_15>
75, // at 38 : <select_lexique_model_builder_16>
77, // at 39 : <select_repeat_lexique_model_builder_17>
79, // at 40 : <select_lexique_model_builder_18>
81, // at 41 : <select_repeat_lexique_model_builder_19>
83, // at 42 : <select_lexique_model_builder_20>
85, // at 43 : <>
0} ;

//---------------------------------------------------------------------------*
//                                                                           *
//               L L ( 1 )    D E C I S I O N    T A B L E S                 *
//                                                                           *
//---------------------------------------------------------------------------*

static const sint16 gDecision [] = {
// At index 0 : <lexique_component_start_symbol> only one production, no choice
  -1,
// At index 1 : <lexical_attribute_declaration> only one production, no choice
  -1,
// At index 2 : <style_declaration> only one production, no choice
  -1,
// At index 3 : <terminal_declaration> only one production, no choice
  -1,
// At index 4 : <lexical_list_declaration> only one production, no choice
  -1,
// At index 5 : <lexical_list_entry> only one production, no choice
  -1,
// At index 6 : <lexical_explicit_rule> only one production, no choice
  -1,
// At index 7 : <lexical_implicit_rule> only one production, no choice
  -1,
// At index 8 : <lexical_error_message_declaration> only one production, no choice
  -1,
// At index 9 : <lexical_instruction>
galgas_scanner::galgas_scanner_1_send, -1, // Choice 1
galgas_scanner::galgas_scanner_1_repeat, -1, // Choice 2
galgas_scanner::galgas_scanner_1_select, -1, // Choice 3
galgas_scanner::galgas_scanner_1_identifier, -1, // Choice 4
galgas_scanner::galgas_scanner_1_error, -1, // Choice 5
galgas_scanner::galgas_scanner_1_drop, -1, // Choice 6
galgas_scanner::galgas_scanner_1_tag, -1, // Choice 7
galgas_scanner::galgas_scanner_1_rewind, -1, // Choice 8
galgas_scanner::galgas_scanner_1_log, -1, // Choice 9
  -1,
// At index 28 : <lexical_send_instruction>
galgas_scanner::galgas_scanner_1_terminal, -1, // Choice 1
galgas_scanner::galgas_scanner_1_search, -1, // Choice 2
  -1,
// At index 33 : <function_call_or_attribute>
galgas_scanner::galgas_scanner_1__2C, galgas_scanner::galgas_scanner_1__29, -1, // Choice 1
galgas_scanner::galgas_scanner_1__28, -1, // Choice 2
  -1,
// At index 39 : <lexical_action_effective_argument>
galgas_scanner::galgas_scanner_1_literal_5Fchar, -1, // Choice 1
galgas_scanner::galgas_scanner_1__2A, -1, // Choice 2
galgas_scanner::galgas_scanner_1_identifier, -1, // Choice 3
  -1,
// At index 46 : <lexical_expression> only one production, no choice
  -1,
// At index 47 : <lexical_term> only one production, no choice
  -1,
// At index 48 : <lexical_factor>
galgas_scanner::galgas_scanner_1_literal_5Fstring, -1, // Choice 1
galgas_scanner::galgas_scanner_1__7E, -1, // Choice 2
galgas_scanner::galgas_scanner_1_literal_5Fchar, -1, // Choice 3
  -1,
// At index 55 : <search_in_lexical_send> only one production, no choice
  -1,
// At index 56 : <default_send_action>
galgas_scanner::galgas_scanner_1_terminal, -1, // Choice 1
galgas_scanner::galgas_scanner_1_error, -1, // Choice 2
  -1,
// At index 61 : <repeat_while_branch> only one production, no choice
  -1,
// At index 62 : <lexical_select_branch> only one production, no choice
  -1,
// At index 63 : <build_lexical_or> only one production, no choice
  -1,
// At index 64 : <character_or_interval>
galgas_scanner::galgas_scanner_1__7C, galgas_scanner::galgas_scanner_1__3A, -1, // Choice 1
galgas_scanner::galgas_scanner_1__2D_3E, -1, // Choice 2
  -1,
//---- Added non terminal symbols from 'select' and 'repeat' instructions
// At index 70 : <select_repeat_lexique_model_builder_0>
galgas_scanner::galgas_scanner_1_end, -1, // Choice 1
galgas_scanner::galgas_scanner_1_type_5Fname, -1, // Choice 2
galgas_scanner::galgas_scanner_1_style, -1, // Choice 3
galgas_scanner::galgas_scanner_1_terminal, -1, // Choice 4
galgas_scanner::galgas_scanner_1_list, -1, // Choice 5
galgas_scanner::galgas_scanner_1_rule, -1, // Choice 6
galgas_scanner::galgas_scanner_1_message, -1, // Choice 7
  -1,
// At index 85 : <select_lexique_model_builder_1>
galgas_scanner::galgas_scanner_1_literal_5Fchar, galgas_scanner::galgas_scanner_1__7E, galgas_scanner::galgas_scanner_1_literal_5Fstring, -1, // Choice 1
galgas_scanner::galgas_scanner_1_list, -1, // Choice 2
  -1,
// At index 92 : <select_repeat_lexique_model_builder_2>
galgas_scanner::galgas_scanner_1_end, -1, // Choice 1
galgas_scanner::galgas_scanner_1_identifier, galgas_scanner::galgas_scanner_1_drop, galgas_scanner::galgas_scanner_1_error, galgas_scanner::galgas_scanner_1_log, galgas_scanner::galgas_scanner_1_repeat, galgas_scanner::galgas_scanner_1_rewind, galgas_scanner::galgas_scanner_1_select, galgas_scanner::galgas_scanner_1_send, galgas_scanner::galgas_scanner_1_tag, -1, // Choice 2
  -1,
// At index 105 : <select_repeat_lexique_model_builder_3>
galgas_scanner::galgas_scanner_1_default, -1, // Choice 1
galgas_scanner::galgas_scanner_1_search, -1, // Choice 2
  -1,
// At index 110 : <select_repeat_lexique_model_builder_4>
galgas_scanner::galgas_scanner_1_while, -1, // Choice 1
galgas_scanner::galgas_scanner_1_identifier, galgas_scanner::galgas_scanner_1_drop, galgas_scanner::galgas_scanner_1_error, galgas_scanner::galgas_scanner_1_log, galgas_scanner::galgas_scanner_1_repeat, galgas_scanner::galgas_scanner_1_rewind, galgas_scanner::galgas_scanner_1_select, galgas_scanner::galgas_scanner_1_send, galgas_scanner::galgas_scanner_1_tag, -1, // Choice 2
  -1,
// At index 123 : <select_repeat_lexique_model_builder_5>
galgas_scanner::galgas_scanner_1_end, -1, // Choice 1
galgas_scanner::galgas_scanner_1_while, -1, // Choice 2
  -1,
// At index 128 : <select_repeat_lexique_model_builder_6>
galgas_scanner::galgas_scanner_1_end, galgas_scanner::galgas_scanner_1_while, -1, // Choice 1
galgas_scanner::galgas_scanner_1_identifier, galgas_scanner::galgas_scanner_1_drop, galgas_scanner::galgas_scanner_1_error, galgas_scanner::galgas_scanner_1_log, galgas_scanner::galgas_scanner_1_repeat, galgas_scanner::galgas_scanner_1_rewind, galgas_scanner::galgas_scanner_1_select, galgas_scanner::galgas_scanner_1_send, galgas_scanner::galgas_scanner_1_tag, -1, // Choice 2
  -1,
// At index 142 : <select_repeat_lexique_model_builder_7>
galgas_scanner::galgas_scanner_1_default, -1, // Choice 1
galgas_scanner::galgas_scanner_1_when, -1, // Choice 2
  -1,
// At index 147 : <select_repeat_lexique_model_builder_8>
galgas_scanner::galgas_scanner_1_end, -1, // Choice 1
galgas_scanner::galgas_scanner_1_identifier, galgas_scanner::galgas_scanner_1_drop, galgas_scanner::galgas_scanner_1_error, galgas_scanner::galgas_scanner_1_log, galgas_scanner::galgas_scanner_1_repeat, galgas_scanner::galgas_scanner_1_rewind, galgas_scanner::galgas_scanner_1_select, galgas_scanner::galgas_scanner_1_send, galgas_scanner::galgas_scanner_1_tag, -1, // Choice 2
  -1,
// At index 160 : <select_repeat_lexique_model_builder_9>
galgas_scanner::galgas_scanner_1_default, galgas_scanner::galgas_scanner_1_when, -1, // Choice 1
galgas_scanner::galgas_scanner_1_identifier, galgas_scanner::galgas_scanner_1_drop, galgas_scanner::galgas_scanner_1_error, galgas_scanner::galgas_scanner_1_log, galgas_scanner::galgas_scanner_1_repeat, galgas_scanner::galgas_scanner_1_rewind, galgas_scanner::galgas_scanner_1_select, galgas_scanner::galgas_scanner_1_send, galgas_scanner::galgas_scanner_1_tag, -1, // Choice 2
  -1,
// At index 174 : <select_repeat_lexique_model_builder_10>
galgas_scanner::galgas_scanner_1__29, -1, // Choice 1
galgas_scanner::galgas_scanner_1__2C, -1, // Choice 2
  -1,
// At index 179 : <select_lexique_model_builder_11>
galgas_scanner::galgas_scanner_1__3B, -1, // Choice 1
galgas_scanner::galgas_scanner_1_error, -1, // Choice 2
  -1,
// At index 184 : <select_repeat_lexique_model_builder_12>
galgas_scanner::galgas_scanner_1__3B, -1, // Choice 1
galgas_scanner::galgas_scanner_1__2C, -1, // Choice 2
  -1,
// At index 189 : <select_repeat_lexique_model_builder_13>
galgas_scanner::galgas_scanner_1__29, -1, // Choice 1
galgas_scanner::galgas_scanner_1__2C, -1, // Choice 2
  -1,
// At index 194 : <select_repeat_lexique_model_builder_14>
galgas_scanner::galgas_scanner_1__3A, -1, // Choice 1
galgas_scanner::galgas_scanner_1__7C, -1, // Choice 2
  -1,
// At index 199 : <select_repeat_lexique_model_builder_15>
galgas_scanner::galgas_scanner_1_error, -1, // Choice 1
galgas_scanner::galgas_scanner_1__21, -1, // Choice 2
  -1,
// At index 204 : <select_lexique_model_builder_16>
galgas_scanner::galgas_scanner_1_style, -1, // Choice 1
galgas_scanner::galgas_scanner_1__3A, -1, // Choice 2
  -1,
// At index 209 : <select_repeat_lexique_model_builder_17>
galgas_scanner::galgas_scanner_1__3B, -1, // Choice 1
galgas_scanner::galgas_scanner_1__2C, -1, // Choice 2
  -1,
// At index 214 : <select_lexique_model_builder_18>
galgas_scanner::galgas_scanner_1__2D_3E, -1, // Choice 1
galgas_scanner::galgas_scanner_1__2C, galgas_scanner::galgas_scanner_1__3B, -1, // Choice 2
  -1,
// At index 220 : <select_repeat_lexique_model_builder_19>
galgas_scanner::galgas_scanner_1_error, -1, // Choice 1
galgas_scanner::galgas_scanner_1__21, -1, // Choice 2
  -1,
// At index 225 : <select_lexique_model_builder_20>
galgas_scanner::galgas_scanner_1_style, -1, // Choice 1
galgas_scanner::galgas_scanner_1__3B, -1, // Choice 2
  -1,
// At index 230 : <> only one production, no choice
  -1,
0} ;

//---------------------------------------------------------------------------*
//                                                                           *
//       L L ( 1 )    D E C I S I O N    T A B L E S    I N D E X E S        *
//                                                                           *
//---------------------------------------------------------------------------*

static const sint16 gDecisionIndexes [45] = {
0, // at 0 : <lexique_component_start_symbol>
1, // at 1 : <lexical_attribute_declaration>
2, // at 2 : <style_declaration>
3, // at 3 : <terminal_declaration>
4, // at 4 : <lexical_list_declaration>
5, // at 5 : <lexical_list_entry>
6, // at 6 : <lexical_explicit_rule>
7, // at 7 : <lexical_implicit_rule>
8, // at 8 : <lexical_error_message_declaration>
9, // at 9 : <lexical_instruction>
28, // at 10 : <lexical_send_instruction>
33, // at 11 : <function_call_or_attribute>
39, // at 12 : <lexical_action_effective_argument>
46, // at 13 : <lexical_expression>
47, // at 14 : <lexical_term>
48, // at 15 : <lexical_factor>
55, // at 16 : <search_in_lexical_send>
56, // at 17 : <default_send_action>
61, // at 18 : <repeat_while_branch>
62, // at 19 : <lexical_select_branch>
63, // at 20 : <build_lexical_or>
64, // at 21 : <character_or_interval>
70, // at 22 : <select_repeat_lexique_model_builder_0>
85, // at 23 : <select_lexique_model_builder_1>
92, // at 24 : <select_repeat_lexique_model_builder_2>
105, // at 25 : <select_repeat_lexique_model_builder_3>
110, // at 26 : <select_repeat_lexique_model_builder_4>
123, // at 27 : <select_repeat_lexique_model_builder_5>
128, // at 28 : <select_repeat_lexique_model_builder_6>
142, // at 29 : <select_repeat_lexique_model_builder_7>
147, // at 30 : <select_repeat_lexique_model_builder_8>
160, // at 31 : <select_repeat_lexique_model_builder_9>
174, // at 32 : <select_repeat_lexique_model_builder_10>
179, // at 33 : <select_lexique_model_builder_11>
184, // at 34 : <select_repeat_lexique_model_builder_12>
189, // at 35 : <select_repeat_lexique_model_builder_13>
194, // at 36 : <select_repeat_lexique_model_builder_14>
199, // at 37 : <select_repeat_lexique_model_builder_15>
204, // at 38 : <select_lexique_model_builder_16>
209, // at 39 : <select_repeat_lexique_model_builder_17>
214, // at 40 : <select_lexique_model_builder_18>
220, // at 41 : <select_repeat_lexique_model_builder_19>
225, // at 42 : <select_lexique_model_builder_20>
230, // at 43 : <>
0} ;

//---------------------------------------------------------------------------*
//                                                                           *
//       'lexique_component_start_symbol' non terminal implementation        *
//                                                                           *
//---------------------------------------------------------------------------*

GGS_lexiqueComponentRoot lexique_LL1_grammar::
nt_lexique_component_start_symbol_ (galgas_scanner & _inLexique) {
  GGS_lexiqueComponentRoot _outReturnedModelInstance ;
  _outReturnedModelInstance = pr_lexique_component_start_symbol_lexique_model_builder_74_6_ (_inLexique) ;
  return _outReturnedModelInstance ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//                   Grammar start symbol implementation                     *
//                                                                           *
//---------------------------------------------------------------------------*


GGS_lexiqueComponentRoot lexique_LL1_grammar::startParsing_ (galgas_scanner & _inLexique) {
  GGS_lexiqueComponentRoot _outReturnedModelInstance ;
// classCount : 0
  const bool ok = _inLexique.performTopDownParsing (gProductions, gProductionNames, gProductionIndexes,
                     gFirstProductionIndexes, gDecision, gDecisionIndexes, 276) ;
  if (ok && ! _inLexique.mParseOnlyFlag) {
    _outReturnedModelInstance = nt_lexique_component_start_symbol_ (_inLexique) ;
  }
  return _outReturnedModelInstance ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//       'lexical_attribute_declaration' non terminal implementation         *
//                                                                           *
//---------------------------------------------------------------------------*

GGS_lexicalAttribute lexique_LL1_grammar::
nt_lexical_attribute_declaration_ (galgas_scanner & _inLexique) {
  GGS_lexicalAttribute _outReturnedModelInstance ;
  _outReturnedModelInstance = pr_lexical_attribute_declaration_lexique_model_builder_458_6_ (_inLexique) ;
  return _outReturnedModelInstance ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//             'style_declaration' non terminal implementation               *
//                                                                           *
//---------------------------------------------------------------------------*

GGS_lexicalStyle lexique_LL1_grammar::
nt_style_declaration_ (galgas_scanner & _inLexique) {
  GGS_lexicalStyle _outReturnedModelInstance ;
  _outReturnedModelInstance = pr_style_declaration_lexique_model_builder_490_6_ (_inLexique) ;
  return _outReturnedModelInstance ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//            'terminal_declaration' non terminal implementation             *
//                                                                           *
//---------------------------------------------------------------------------*

GGS_terminalDeclaration lexique_LL1_grammar::
nt_terminal_declaration_ (galgas_scanner & _inLexique) {
  GGS_terminalDeclaration _outReturnedModelInstance ;
  _outReturnedModelInstance = pr_terminal_declaration_lexique_model_builder_466_6_ (_inLexique) ;
  return _outReturnedModelInstance ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//          'lexical_list_declaration' non terminal implementation           *
//                                                                           *
//---------------------------------------------------------------------------*

GGS_lexicalListDeclaration lexique_LL1_grammar::
nt_lexical_list_declaration_ (galgas_scanner & _inLexique) {
  GGS_lexicalListDeclaration _outReturnedModelInstance ;
  _outReturnedModelInstance = pr_lexical_list_declaration_lexique_model_builder_415_6_ (_inLexique) ;
  return _outReturnedModelInstance ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//             'lexical_list_entry' non terminal implementation              *
//                                                                           *
//---------------------------------------------------------------------------*

GGS_lexicalListEntry lexique_LL1_grammar::
nt_lexical_list_entry_ (galgas_scanner & _inLexique) {
  GGS_lexicalListEntry _outReturnedModelInstance ;
  _outReturnedModelInstance = pr_lexical_list_entry_lexique_model_builder_446_6_ (_inLexique) ;
  return _outReturnedModelInstance ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//           'lexical_explicit_rule' non terminal implementation             *
//                                                                           *
//---------------------------------------------------------------------------*

GGS_lexicalExplicitRule lexique_LL1_grammar::
nt_lexical_explicit_rule_ (galgas_scanner & _inLexique) {
  GGS_lexicalExplicitRule _outReturnedModelInstance ;
  _outReturnedModelInstance = pr_lexical_explicit_rule_lexique_model_builder_124_6_ (_inLexique) ;
  return _outReturnedModelInstance ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//           'lexical_implicit_rule' non terminal implementation             *
//                                                                           *
//---------------------------------------------------------------------------*

GGS_lexicalImplicitRule lexique_LL1_grammar::
nt_lexical_implicit_rule_ (galgas_scanner & _inLexique) {
  GGS_lexicalImplicitRule _outReturnedModelInstance ;
  _outReturnedModelInstance = pr_lexical_implicit_rule_lexique_model_builder_117_6_ (_inLexique) ;
  return _outReturnedModelInstance ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//     'lexical_error_message_declaration' non terminal implementation       *
//                                                                           *
//---------------------------------------------------------------------------*

GGS_lexicalErrorMessageDeclaration lexique_LL1_grammar::
nt_lexical_error_message_declaration_ (galgas_scanner & _inLexique) {
  GGS_lexicalErrorMessageDeclaration _outReturnedModelInstance ;
  _outReturnedModelInstance = pr_lexical_error_message_declaration_lexique_model_builder_107_6_ (_inLexique) ;
  return _outReturnedModelInstance ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//            'lexical_instruction' non terminal implementation              *
//                                                                           *
//---------------------------------------------------------------------------*

GGS_lexicalInstruction lexique_LL1_grammar::
nt_lexical_instruction_ (galgas_scanner & _inLexique) {
  GGS_lexicalInstruction _outReturnedModelInstance ;
  switch (_inLexique.nextProductionIndex ()) {
  case 1 :
    _outReturnedModelInstance = pr_lexical_instruction_lexique_model_builder_137_6_ (_inLexique) ;
    break ;
  case 2 :
    _outReturnedModelInstance = pr_lexical_instruction_lexique_model_builder_184_6_ (_inLexique) ;
    break ;
  case 3 :
    _outReturnedModelInstance = pr_lexical_instruction_lexique_model_builder_213_6_ (_inLexique) ;
    break ;
  case 4 :
    _outReturnedModelInstance = pr_lexical_instruction_lexique_model_builder_243_6_ (_inLexique) ;
    break ;
  case 5 :
    _outReturnedModelInstance = pr_lexical_instruction_lexique_model_builder_308_6_ (_inLexique) ;
    break ;
  case 6 :
    _outReturnedModelInstance = pr_lexical_instruction_lexique_model_builder_316_6_ (_inLexique) ;
    break ;
  case 7 :
    _outReturnedModelInstance = pr_lexical_instruction_lexique_model_builder_324_6_ (_inLexique) ;
    break ;
  case 8 :
    _outReturnedModelInstance = pr_lexical_instruction_lexique_model_builder_332_6_ (_inLexique) ;
    break ;
  case 9 :
    _outReturnedModelInstance = pr_lexical_instruction_lexique_model_builder_342_6_ (_inLexique) ;
    break ;
  default :
    break ;
  }
  return _outReturnedModelInstance ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//          'lexical_send_instruction' non terminal implementation           *
//                                                                           *
//---------------------------------------------------------------------------*

GGS_lexicalInstruction lexique_LL1_grammar::
nt_lexical_send_instruction_ (galgas_scanner & _inLexique) {
  GGS_lexicalInstruction _outReturnedModelInstance ;
  switch (_inLexique.nextProductionIndex ()) {
  case 1 :
    _outReturnedModelInstance = pr_lexical_send_instruction_lexique_model_builder_145_6_ (_inLexique) ;
    break ;
  case 2 :
    _outReturnedModelInstance = pr_lexical_send_instruction_lexique_model_builder_151_6_ (_inLexique) ;
    break ;
  default :
    break ;
  }
  return _outReturnedModelInstance ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//         'function_call_or_attribute' non terminal implementation          *
//                                                                           *
//---------------------------------------------------------------------------*

GGS_lexicalActualArgument lexique_LL1_grammar::
nt_function_call_or_attribute_ (galgas_scanner & _inLexique,
                                const GGS_lstring & parameter_1) {
  GGS_lexicalActualArgument _outReturnedModelInstance ;
  switch (_inLexique.nextProductionIndex ()) {
  case 1 :
    _outReturnedModelInstance = pr_function_call_or_attribute_lexique_model_builder_289_6_ (_inLexique, parameter_1) ;
    break ;
  case 2 :
    _outReturnedModelInstance = pr_function_call_or_attribute_lexique_model_builder_295_6_ (_inLexique, parameter_1) ;
    break ;
  default :
    break ;
  }
  return _outReturnedModelInstance ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//     'lexical_action_effective_argument' non terminal implementation       *
//                                                                           *
//---------------------------------------------------------------------------*

GGS_lexicalActualArgument lexique_LL1_grammar::
nt_lexical_action_effective_argument_ (galgas_scanner & _inLexique) {
  GGS_lexicalActualArgument _outReturnedModelInstance ;
  switch (_inLexique.nextProductionIndex ()) {
  case 1 :
    _outReturnedModelInstance = pr_lexical_action_effective_argument_lexique_model_builder_269_6_ (_inLexique) ;
    break ;
  case 2 :
    _outReturnedModelInstance = pr_lexical_action_effective_argument_lexique_model_builder_275_6_ (_inLexique) ;
    break ;
  case 3 :
    _outReturnedModelInstance = pr_lexical_action_effective_argument_lexique_model_builder_281_6_ (_inLexique) ;
    break ;
  default :
    break ;
  }
  return _outReturnedModelInstance ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//             'lexical_expression' non terminal implementation              *
//                                                                           *
//---------------------------------------------------------------------------*

GGS_lexicalExpression lexique_LL1_grammar::
nt_lexical_expression_ (galgas_scanner & _inLexique) {
  GGS_lexicalExpression _outReturnedModelInstance ;
  _outReturnedModelInstance = pr_lexical_expression_lexique_model_builder_349_6_ (_inLexique) ;
  return _outReturnedModelInstance ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//                'lexical_term' non terminal implementation                 *
//                                                                           *
//---------------------------------------------------------------------------*

GGS_lexicalExpression lexique_LL1_grammar::
nt_lexical_term_ (galgas_scanner & _inLexique) {
  GGS_lexicalExpression _outReturnedModelInstance ;
  _outReturnedModelInstance = pr_lexical_term_lexique_model_builder_355_6_ (_inLexique) ;
  return _outReturnedModelInstance ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//               'lexical_factor' non terminal implementation                *
//                                                                           *
//---------------------------------------------------------------------------*

GGS_lexicalExpression lexique_LL1_grammar::
nt_lexical_factor_ (galgas_scanner & _inLexique) {
  GGS_lexicalExpression _outReturnedModelInstance ;
  switch (_inLexique.nextProductionIndex ()) {
  case 1 :
    _outReturnedModelInstance = pr_lexical_factor_lexique_model_builder_378_6_ (_inLexique) ;
    break ;
  case 2 :
    _outReturnedModelInstance = pr_lexical_factor_lexique_model_builder_384_6_ (_inLexique) ;
    break ;
  case 3 :
    _outReturnedModelInstance = pr_lexical_factor_lexique_model_builder_393_6_ (_inLexique) ;
    break ;
  default :
    break ;
  }
  return _outReturnedModelInstance ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//           'search_in_lexical_send' non terminal implementation            *
//                                                                           *
//---------------------------------------------------------------------------*

GGS_lexicalSendSearch lexique_LL1_grammar::
nt_search_in_lexical_send_ (galgas_scanner & _inLexique) {
  GGS_lexicalSendSearch _outReturnedModelInstance ;
  _outReturnedModelInstance = pr_search_in_lexical_send_lexique_model_builder_162_6_ (_inLexique) ;
  return _outReturnedModelInstance ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//            'default_send_action' non terminal implementation              *
//                                                                           *
//---------------------------------------------------------------------------*

GGS_lexicalSendDefaultAction lexique_LL1_grammar::
nt_default_send_action_ (galgas_scanner & _inLexique) {
  GGS_lexicalSendDefaultAction _outReturnedModelInstance ;
  switch (_inLexique.nextProductionIndex ()) {
  case 1 :
    _outReturnedModelInstance = pr_default_send_action_lexique_model_builder_171_6_ (_inLexique) ;
    break ;
  case 2 :
    _outReturnedModelInstance = pr_default_send_action_lexique_model_builder_177_6_ (_inLexique) ;
    break ;
  default :
    break ;
  }
  return _outReturnedModelInstance ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//            'repeat_while_branch' non terminal implementation              *
//                                                                           *
//---------------------------------------------------------------------------*

GGS_lexicalWhileBranch lexique_LL1_grammar::
nt_repeat_while_branch_ (galgas_scanner & _inLexique) {
  GGS_lexicalWhileBranch _outReturnedModelInstance ;
  _outReturnedModelInstance = pr_repeat_while_branch_lexique_model_builder_201_6_ (_inLexique) ;
  return _outReturnedModelInstance ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//           'lexical_select_branch' non terminal implementation             *
//                                                                           *
//---------------------------------------------------------------------------*

GGS_lexicalSelectBranch lexique_LL1_grammar::
nt_lexical_select_branch_ (galgas_scanner & _inLexique) {
  GGS_lexicalSelectBranch _outReturnedModelInstance ;
  _outReturnedModelInstance = pr_lexical_select_branch_lexique_model_builder_231_6_ (_inLexique) ;
  return _outReturnedModelInstance ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//              'build_lexical_or' non terminal implementation               *
//                                                                           *
//---------------------------------------------------------------------------*

GGS_lexicalExpression lexique_LL1_grammar::
nt_build_lexical_or_ (galgas_scanner & _inLexique,
                                const GGS_lexicalExpression & parameter_1,
                                const GGS_lexicalExpression & parameter_2) {
  GGS_lexicalExpression _outReturnedModelInstance ;
  _outReturnedModelInstance = pr_build_lexical_or_lexique_model_builder_368_6_ (_inLexique, parameter_1, parameter_2) ;
  return _outReturnedModelInstance ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//           'character_or_interval' non terminal implementation             *
//                                                                           *
//---------------------------------------------------------------------------*

GGS_lexicalExpression lexique_LL1_grammar::
nt_character_or_interval_ (galgas_scanner & _inLexique,
                                const GGS_lchar & parameter_1) {
  GGS_lexicalExpression _outReturnedModelInstance ;
  switch (_inLexique.nextProductionIndex ()) {
  case 1 :
    _outReturnedModelInstance = pr_character_or_interval_lexique_model_builder_401_6_ (_inLexique, parameter_1) ;
    break ;
  case 2 :
    _outReturnedModelInstance = pr_character_or_interval_lexique_model_builder_407_6_ (_inLexique, parameter_1) ;
    break ;
  default :
    break ;
  }
  return _outReturnedModelInstance ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//'select_repeat_lexique_model_builder_0' added non terminal implementation  *
//                                                                           *
//---------------------------------------------------------------------------*


sint16 lexique_LL1_grammar::select_repeat_lexique_model_builder_0 (galgas_scanner & _inLexique) {
  return _inLexique.nextProductionIndex () ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//    'select_lexique_model_builder_1' added non terminal implementation     *
//                                                                           *
//---------------------------------------------------------------------------*


sint16 lexique_LL1_grammar::select_lexique_model_builder_1 (galgas_scanner & _inLexique) {
  return _inLexique.nextProductionIndex () ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//'select_repeat_lexique_model_builder_2' added non terminal implementation  *
//                                                                           *
//---------------------------------------------------------------------------*


sint16 lexique_LL1_grammar::select_repeat_lexique_model_builder_2 (galgas_scanner & _inLexique) {
  return _inLexique.nextProductionIndex () ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//'select_repeat_lexique_model_builder_3' added non terminal implementation  *
//                                                                           *
//---------------------------------------------------------------------------*


sint16 lexique_LL1_grammar::select_repeat_lexique_model_builder_3 (galgas_scanner & _inLexique) {
  return _inLexique.nextProductionIndex () ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//'select_repeat_lexique_model_builder_4' added non terminal implementation  *
//                                                                           *
//---------------------------------------------------------------------------*


sint16 lexique_LL1_grammar::select_repeat_lexique_model_builder_4 (galgas_scanner & _inLexique) {
  return _inLexique.nextProductionIndex () ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//'select_repeat_lexique_model_builder_5' added non terminal implementation  *
//                                                                           *
//---------------------------------------------------------------------------*


sint16 lexique_LL1_grammar::select_repeat_lexique_model_builder_5 (galgas_scanner & _inLexique) {
  return _inLexique.nextProductionIndex () ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//'select_repeat_lexique_model_builder_6' added non terminal implementation  *
//                                                                           *
//---------------------------------------------------------------------------*


sint16 lexique_LL1_grammar::select_repeat_lexique_model_builder_6 (galgas_scanner & _inLexique) {
  return _inLexique.nextProductionIndex () ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//'select_repeat_lexique_model_builder_7' added non terminal implementation  *
//                                                                           *
//---------------------------------------------------------------------------*


sint16 lexique_LL1_grammar::select_repeat_lexique_model_builder_7 (galgas_scanner & _inLexique) {
  return _inLexique.nextProductionIndex () ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//'select_repeat_lexique_model_builder_8' added non terminal implementation  *
//                                                                           *
//---------------------------------------------------------------------------*


sint16 lexique_LL1_grammar::select_repeat_lexique_model_builder_8 (galgas_scanner & _inLexique) {
  return _inLexique.nextProductionIndex () ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//'select_repeat_lexique_model_builder_9' added non terminal implementation  *
//                                                                           *
//---------------------------------------------------------------------------*


sint16 lexique_LL1_grammar::select_repeat_lexique_model_builder_9 (galgas_scanner & _inLexique) {
  return _inLexique.nextProductionIndex () ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//'select_repeat_lexique_model_builder_10' added non terminal implementation *
//                                                                           *
//---------------------------------------------------------------------------*


sint16 lexique_LL1_grammar::select_repeat_lexique_model_builder_10 (galgas_scanner & _inLexique) {
  return _inLexique.nextProductionIndex () ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//   'select_lexique_model_builder_11' added non terminal implementation     *
//                                                                           *
//---------------------------------------------------------------------------*


sint16 lexique_LL1_grammar::select_lexique_model_builder_11 (galgas_scanner & _inLexique) {
  return _inLexique.nextProductionIndex () ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//'select_repeat_lexique_model_builder_12' added non terminal implementation *
//                                                                           *
//---------------------------------------------------------------------------*


sint16 lexique_LL1_grammar::select_repeat_lexique_model_builder_12 (galgas_scanner & _inLexique) {
  return _inLexique.nextProductionIndex () ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//'select_repeat_lexique_model_builder_13' added non terminal implementation *
//                                                                           *
//---------------------------------------------------------------------------*


sint16 lexique_LL1_grammar::select_repeat_lexique_model_builder_13 (galgas_scanner & _inLexique) {
  return _inLexique.nextProductionIndex () ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//'select_repeat_lexique_model_builder_14' added non terminal implementation *
//                                                                           *
//---------------------------------------------------------------------------*


sint16 lexique_LL1_grammar::select_repeat_lexique_model_builder_14 (galgas_scanner & _inLexique) {
  return _inLexique.nextProductionIndex () ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//'select_repeat_lexique_model_builder_15' added non terminal implementation *
//                                                                           *
//---------------------------------------------------------------------------*


sint16 lexique_LL1_grammar::select_repeat_lexique_model_builder_15 (galgas_scanner & _inLexique) {
  return _inLexique.nextProductionIndex () ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//   'select_lexique_model_builder_16' added non terminal implementation     *
//                                                                           *
//---------------------------------------------------------------------------*


sint16 lexique_LL1_grammar::select_lexique_model_builder_16 (galgas_scanner & _inLexique) {
  return _inLexique.nextProductionIndex () ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//'select_repeat_lexique_model_builder_17' added non terminal implementation *
//                                                                           *
//---------------------------------------------------------------------------*


sint16 lexique_LL1_grammar::select_repeat_lexique_model_builder_17 (galgas_scanner & _inLexique) {
  return _inLexique.nextProductionIndex () ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//   'select_lexique_model_builder_18' added non terminal implementation     *
//                                                                           *
//---------------------------------------------------------------------------*


sint16 lexique_LL1_grammar::select_lexique_model_builder_18 (galgas_scanner & _inLexique) {
  return _inLexique.nextProductionIndex () ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//'select_repeat_lexique_model_builder_19' added non terminal implementation *
//                                                                           *
//---------------------------------------------------------------------------*


sint16 lexique_LL1_grammar::select_repeat_lexique_model_builder_19 (galgas_scanner & _inLexique) {
  return _inLexique.nextProductionIndex () ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//   'select_lexique_model_builder_20' added non terminal implementation     *
//                                                                           *
//---------------------------------------------------------------------------*


sint16 lexique_LL1_grammar::select_lexique_model_builder_20 (galgas_scanner & _inLexique) {
  return _inLexique.nextProductionIndex () ;
}

//---------------------------------------------------------------------------*

