//---------------------------------------------------------------------------*
//                                                                           *
//                       File 'metamodelLL1grammar.h'                        *
//         Generated by version GALGAS_BETA_VERSION (LL(1) grammar)          *
//                      april 24th, 2007, at 22h24'35"                       *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

#ifndef GRAMMAR_metamodelLL1grammar_HAS_BEEN_DEFINED
#define GRAMMAR_metamodelLL1grammar_HAS_BEEN_DEFINED

//---------------------------------------------------------------------------*

#include "metamodelModelBuilder.h"

//--- START OF USER ZONE 2


//--- END OF USER ZONE 2

//---------------------------------------------------------------------------*

class metamodelLL1grammar : public metamodelModelBuilder {
  public : virtual GGS_metamodelComponentRoot nt_metamodel_component_start_symbol_ (galgas_scanner &) ;
  public : GGS_metamodelComponentRoot startParsing_ (galgas_scanner &) ;
  public : virtual GGS_metamodelEntity nt_entity_declaration_ (galgas_scanner &) ;
  public : virtual void nt_component_importation_ (galgas_scanner &,
                                GGS_lstringlist &) ;
  public : virtual GGS_metamodelAttribute nt_attribute_or_single_reference_declaration_ (galgas_scanner &,
                                const GGS_lstring) ;
  public : virtual GGS_metamodelMultipleReference nt_multiple_reference_declaration_ (galgas_scanner &,
                                const GGS_lstring) ;
  public : virtual sint16 select_metamodelModelBuilder_0 (galgas_scanner &) ;
  public : virtual sint16 select_metamodelModelBuilder_1 (galgas_scanner &) ;
  public : virtual sint16 select_repeat_metamodelModelBuilder_2 (galgas_scanner &) ;
  public : virtual sint16 select_metamodelModelBuilder_3 (galgas_scanner &) ;
  public : virtual sint16 select_repeat_metamodelModelBuilder_4 (galgas_scanner &) ;
  public : virtual sint16 select_repeat_metamodelModelBuilder_5 (galgas_scanner &) ;
  public : virtual sint16 select_repeat_metamodelModelBuilder_6 (galgas_scanner &) ;
  public : virtual sint16 select_metamodelModelBuilder_7 (galgas_scanner &) ;
  public : virtual sint16 select_metamodelModelBuilder_8 (galgas_scanner &) ;
  public : virtual sint16 select_metamodelModelBuilder_9 (galgas_scanner &) ;
  public : virtual sint16 select_repeat_metamodelModelBuilder_10 (galgas_scanner &) ;
  public : virtual sint16 select_metamodelModelBuilder_11 (galgas_scanner &) ;
  public : virtual sint16 select_metamodelModelBuilder_12 (galgas_scanner &) ;
  public : virtual sint16 select_metamodelModelBuilder_13 (galgas_scanner &) ;
  public : virtual sint16 select_metamodelModelBuilder_14 (galgas_scanner &) ;
} ;

//---------------------------------------------------------------------------*

#endif
