//---------------------------------------------------------------------------*
//                                                                           *
//                    File 'parameterArgumentBuilder.h'                      *
//                 Generated by version GALGAS_BETA_VERSION                  *
//                     february 7th, 2010, at 20h25'35"                      *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

#ifndef parameterArgumentBuilder_DEFINED
#define parameterArgumentBuilder_DEFINED

#include <string.h>

//---------------------------------------------------------------------------*

#include "galgas/GGS__header.h"
#include "galgas_scanner.h"

//---------------------------------------------------------------------------*

// Include imported semantics
#include "expressionMetamodel.h"
#include "parameterArgumentMetamodel.h"

//--- START OF USER ZONE 2


//--- END OF USER ZONE 2

//---------------------------------------------------------------------------*
//                                                                           *
//                          Class Predeclarations                            *
//                                                                           *
//---------------------------------------------------------------------------*


//---------------------------------------------------------------------------*
//                                                                           *
//            Parser class parameterArgumentBuilder declaration              *
//                                                                           *
//---------------------------------------------------------------------------*

class parameterArgumentBuilder {
  public : virtual ~parameterArgumentBuilder (void) {}

  protected : virtual void nt_expression_ (C_Lexique_galgas_5F_scanner &,
                                GGS_semanticExpression  &) = 0 ;

  protected : virtual void nt_formal_parameter_list_ (C_Lexique_galgas_5F_scanner &,
                                GGS_formalParameterList  &) = 0 ;

  protected : virtual void nt_formal_input_parameter_list_ (C_Lexique_galgas_5F_scanner &,
                                GGS_formalInputParameterList  &) = 0 ;

  protected : virtual void nt_actual_parameter_list_ (C_Lexique_galgas_5F_scanner &,
                                GGS_actualParameterList  &) = 0 ;

  protected : virtual void nt_actual_input_parameter_list_ (C_Lexique_galgas_5F_scanner &,
                                GGS_actualInputParameterList  &) = 0 ;

  protected : void pr_formal_parameter_list_parameterArgumentBuilder_49_28_ (C_Lexique_galgas_5F_scanner &,
                                GGS_formalParameterList  &) ;

  protected : virtual PMSInt16 select_parameterArgumentBuilder_0 (C_Lexique_galgas_5F_scanner &) = 0 ;

  protected : virtual PMSInt16 select_parameterArgumentBuilder_1 (C_Lexique_galgas_5F_scanner &) = 0 ;

  protected : virtual PMSInt16 select_parameterArgumentBuilder_2 (C_Lexique_galgas_5F_scanner &) = 0 ;

  protected : void pr_actual_parameter_list_parameterArgumentBuilder_91_28_ (C_Lexique_galgas_5F_scanner &,
                                GGS_actualParameterList  &) ;

  protected : virtual PMSInt16 select_parameterArgumentBuilder_3 (C_Lexique_galgas_5F_scanner &) = 0 ;

  protected : virtual PMSInt16 select_parameterArgumentBuilder_4 (C_Lexique_galgas_5F_scanner &) = 0 ;

  protected : virtual PMSInt16 select_parameterArgumentBuilder_5 (C_Lexique_galgas_5F_scanner &) = 0 ;

  protected : virtual PMSInt16 select_parameterArgumentBuilder_6 (C_Lexique_galgas_5F_scanner &) = 0 ;

  protected : void pr_formal_input_parameter_list_parameterArgumentBuilder_151_34_ (C_Lexique_galgas_5F_scanner &,
                                GGS_formalInputParameterList  &) ;

  protected : virtual PMSInt16 select_parameterArgumentBuilder_7 (C_Lexique_galgas_5F_scanner &) = 0 ;

  protected : virtual PMSInt16 select_parameterArgumentBuilder_8 (C_Lexique_galgas_5F_scanner &) = 0 ;

  protected : void pr_actual_input_parameter_list_parameterArgumentBuilder_179_34_ (C_Lexique_galgas_5F_scanner &,
                                GGS_actualInputParameterList  &) ;

  protected : virtual PMSInt16 select_parameterArgumentBuilder_9 (C_Lexique_galgas_5F_scanner &) = 0 ;

  protected : virtual PMSInt16 select_parameterArgumentBuilder_10 (C_Lexique_galgas_5F_scanner &) = 0 ;

  protected : virtual PMSInt16 select_parameterArgumentBuilder_11 (C_Lexique_galgas_5F_scanner &) = 0 ;

} ;

//---------------------------------------------------------------------------*

#endif
