//---------------------------------------------------------------------------*
//                                                                           *
//                  File 'programComponentCompilation.cpp'                   *
//             Generated by version version GALGAS_BETA_VERSION              *
//                    november 24th, 2010, at 13h32'27"                      *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

#include "version_libpm.h"
#if CURRENT_LIBPM_VERSION != VERSION_OF_LIBPM_USED_BY_GALGAS_COMPILER
  #error "This file has been compiled with a version of GALGAS that uses libpm version VERSION_OF_LIBPM_USED_BY_GALGAS_COMPILER, different than the current version (CURRENT_LIBPM_VERSION) of libpm"
#endif

//---------------------------------------------------------------------------*

#include "programComponentCompilation.h"
#include "galgas2/C_Compiler.h"
#include "galgas2/C_galgas_CLI_Options.h"

//---------------------------------------------------------------------------*

#include "optionLL1grammar.h"
#include "templateGrammar.h"
#include "galgas_cli_options.h"
#include "grammarLL1grammar.h"
#include "syntaxSLRgrammar.h"
#include "semanticsSLRgrammar.h"
#include "lexiqueLL1grammar.h"
#include "programSLRgrammar.h"

//---------------------------------------------------------------------------*

#ifndef DO_NOT_GENERATE_CHECKINGS
  #define SOURCE_FILE_AT_LINE(line) "programComponentCompilation.gSemantics", line
  #define COMMA_SOURCE_FILE_AT_LINE(line) , SOURCE_FILE_AT_LINE(line)
#else
  #define SOURCE_FILE_AT_LINE(line) 
  #define COMMA_SOURCE_FILE_AT_LINE(line) 
#endif

//---------------------------------------------------------------------------*
//                                                                           *
//                Filewrapper 'programFileGenerationTemplate'                *
//                                                                           *
//---------------------------------------------------------------------------*


extern const cDirectoryWrapper gWrapperDirectory_0_programFileGenerationTemplate ;

//---------------------------------------------------------------------------*
//                                                                           *
//  Filewrapper template 'programFileGenerationTemplate programFileHeader'   *
//                                                                           *
//---------------------------------------------------------------------------*

GALGAS_string filewrapperTemplate_programFileGenerationTemplate_programFileHeader (C_Compiler * inCompiler,
                                                                                   const GALGAS_string & in_COMPONENT_5F_NAME,
                                                                                   const GALGAS_stringlist & in_IMPORTED_5F_COMPONENT_5F_LIST,
                                                                                   const GALGAS_lstringlist & in_TYPE_5F_PREDECLARATION_5F_LIST
                                                                                   COMMA_LOCATION_ARGS) ;

//---------------------------------------------------------------------------*
//                                                                           *
//Filewrapper template 'programFileGenerationTemplate programFileImplementation'*
//                                                                           *
//---------------------------------------------------------------------------*

GALGAS_string filewrapperTemplate_programFileGenerationTemplate_programFileImplementation (C_Compiler * inCompiler,
                                                                                           const GALGAS_string & in_COMPONENT_5F_NAME,
                                                                                           const GALGAS_stringlist & in_IMPORTED_5F_COMPONENT_5F_LIST,
                                                                                           const GALGAS_programRuleList & in_PROGRAM_5F_RULE_5F_LIST,
                                                                                           const GALGAS_string & in_VERSION
                                                                                           COMMA_LOCATION_ARGS) ;

//---------------------------------------------------------------------------*
//                                                                           *
//                       Routine 'compileBeforeClause'                       *
//                                                                           *
//---------------------------------------------------------------------------*

void routine_compileBeforeClause (const GALGAS_analysisContext constinArgument0,
                                  const GALGAS_programComponentAST constinArgument1,
                                  GALGAS_semanticDeclarationSortedListForGeneration & ioArgument2,
                                  C_Compiler * inCompiler
                                  COMMA_LOCATION_ARGS) ;

//---------------------------------------------------------------------------*
//                                                                           *
//                       Routine 'compileProgramRules'                       *
//                                                                           *
//---------------------------------------------------------------------------*

void routine_compileProgramRules (const GALGAS_analysisContext constinArgument0,
                                  const GALGAS_programComponentAST constinArgument1,
                                  GALGAS_semanticDeclarationSortedListForGeneration & ioArgument2,
                                  C_Compiler * inCompiler
                                  COMMA_LOCATION_ARGS) ;

//---------------------------------------------------------------------------*
//                                                                           *
//                       Routine 'compileAfterClause'                        *
//                                                                           *
//---------------------------------------------------------------------------*

void routine_compileAfterClause (const GALGAS_analysisContext constinArgument0,
                                 const GALGAS_programComponentAST constinArgument1,
                                 GALGAS_semanticDeclarationSortedListForGeneration & ioArgument2,
                                 C_Compiler * inCompiler
                                 COMMA_LOCATION_ARGS) ;

//---------------------------------------------------------------------------*
//                                                                           *
//                Filewrapper 'programFileGenerationTemplate'                *
//                                                                           *
//---------------------------------------------------------------------------*

//--- All files of '' directory

static const cRegularFileWrapper * gWrapperAllFiles_programFileGenerationTemplate_0 [1] = {
  NULL
} ;

//--- All sub-directories of '' directory

static const cDirectoryWrapper * gWrapperAllDirectories_programFileGenerationTemplate_0 [1] = {
  NULL
} ;

//--- Directory ''

const cDirectoryWrapper gWrapperDirectory_0_programFileGenerationTemplate (
  "",
  0,
  gWrapperAllFiles_programFileGenerationTemplate_0,
  0,
  gWrapperAllDirectories_programFileGenerationTemplate_0
) ;


//---------------------------------------------------------------------------*
//                                                                           *
//  Filewrapper template 'programFileGenerationTemplate programFileHeader'   *
//                                                                           *
//---------------------------------------------------------------------------*

GALGAS_string filewrapperTemplate_programFileGenerationTemplate_programFileHeader (C_Compiler * /* inCompiler */,
                                                                                   const GALGAS_string & in_COMPONENT_5F_NAME,
                                                                                   const GALGAS_stringlist & in_IMPORTED_5F_COMPONENT_5F_LIST,
                                                                                   const GALGAS_lstringlist & in_TYPE_5F_PREDECLARATION_5F_LIST
                                                                                   COMMA_UNUSED_LOCATION_ARGS) {
  C_String result ;
  result << "#ifndef " ;
  result << in_COMPONENT_5F_NAME.stringValue () ;
  result << "_ENTITIES_DEFINED\n"
    "#define " ;
  result << in_COMPONENT_5F_NAME.stringValue () ;
  result << "_ENTITIES_DEFINED\n"
    "\n"
    "//---------------------------------------------------------------------------*\n"
    "\n"
    "#include \"galgas2/predefined-types.h\"\n"
    "\n"
    "//---------------------------------------------------------------------------*\n"
    "\n" ;
  GALGAS_uint index_339_ (0) ;
  if (in_IMPORTED_5F_COMPONENT_5F_LIST.isValid ()) {
    cEnumerator_stringlist enumerator_339 (in_IMPORTED_5F_COMPONENT_5F_LIST, true) ;
    while (enumerator_339.hasCurrentObject ()) {
      result << "#include \"" ;
      result << enumerator_339.current_mValue (HERE).stringValue () ;
      result << ".h\"\n" ;
      index_339_.increment () ;
      enumerator_339.gotoNextObject () ;
    }
  }
  result << "\n"
    "//---------------------------------------------------------------------------*\n"
    "\n" ;
  GALGAS_uint index_504_ (0) ;
  if (in_TYPE_5F_PREDECLARATION_5F_LIST.isValid ()) {
    cEnumerator_lstringlist enumerator_504 (in_TYPE_5F_PREDECLARATION_5F_LIST, true) ;
    while (enumerator_504.hasCurrentObject ()) {
      result << "class GALGAS_" ;
      result << enumerator_504.current_mValue (HERE).mAttribute_string.reader_identifierRepresentation (SOURCE_FILE_AT_LINE (17)).stringValue () ;
      result << " ;\n" ;
      index_504_.increment () ;
      enumerator_504.gotoNextObject () ;
    }
  }
  result << "\n" ;
  return GALGAS_string (result) ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//Filewrapper template 'programFileGenerationTemplate programFileImplementation'*
//                                                                           *
//---------------------------------------------------------------------------*

GALGAS_string filewrapperTemplate_programFileGenerationTemplate_programFileImplementation (C_Compiler * /* inCompiler */,
                                                                                           const GALGAS_string & in_COMPONENT_5F_NAME,
                                                                                           const GALGAS_stringlist & in_IMPORTED_5F_COMPONENT_5F_LIST,
                                                                                           const GALGAS_programRuleList & in_PROGRAM_5F_RULE_5F_LIST,
                                                                                           const GALGAS_string & in_VERSION
                                                                                           COMMA_UNUSED_LOCATION_ARGS) {
  C_String result ;
  result << "#include \"version_libpm.h\"\n"
    "#if CURRENT_LIBPM_VERSION != VERSION_OF_LIBPM_USED_BY_GALGAS_COMPILER\n"
    "  #error \"This file has been compiled with a version of GALGAS that uses libpm version VERSION_OF_LIBPM_USED_BY_GALGAS_COMPILER, different than the cu"
    "rrent version (CURRENT_LIBPM_VERSION) of libpm\"\n"
    "#endif\n"
    "\n"
    "//---------------------------------------------------------------------------*\n"
    "\n"
    "#include \"" ;
  result << in_COMPONENT_5F_NAME.stringValue () ;
  result << ".h\"\n"
    "#include \"galgas2/C_galgas_CLI_Options.h\"\n"
    "#include \"utilities/F_DisplayException.h\"\n"
    "#include \"utilities/basic-allocation.h\"\n"
    "#include \"utilities/cpp-allocation.h\"\n"
    "#include \"command_line_interface/mainForLIBPM.h\"\n"
    "#include \"command_line_interface/F_Analyze_CLI_Options.h\"\n"
    "#include \"command_line_interface/C_builtin_CLI_Options.h\"\n"
    "\n"
    "//---------------------------------------------------------------------------*\n"
    "\n" ;
  GALGAS_uint index_875_ (0) ;
  if (in_IMPORTED_5F_COMPONENT_5F_LIST.isValid ()) {
    cEnumerator_stringlist enumerator_875 (in_IMPORTED_5F_COMPONENT_5F_LIST, true) ;
    while (enumerator_875.hasCurrentObject ()) {
      result << "#include \"" ;
      result << enumerator_875.current_mValue (HERE).stringValue () ;
      result << ".h\"\n" ;
      index_875_.increment () ;
      enumerator_875.gotoNextObject () ;
    }
  }
  result << "\n"
    "//---------------------------------------------------------------------------*\n"
    "\n"
    "#ifndef DO_NOT_GENERATE_CHECKINGS\n"
    "  #define SOURCE_FILE_AT_LINE(line) \"" ;
  result << in_COMPONENT_5F_NAME.stringValue () ;
  result << ".gProgram\", line\n"
    "  #define COMMA_SOURCE_FILE_AT_LINE(line) , SOURCE_FILE_AT_LINE(line)\n"
    "#else\n"
    "  #define SOURCE_FILE_AT_LINE(line) \n"
    "  #define COMMA_SOURCE_FILE_AT_LINE(line) \n"
    "#endif\n"
    "\n"
    "//---------------------------------------------------------------------------*\n"
    "//                                                                           *\n"
    "//                      M A I N    F O R    L I B P M                        *\n"
    "//                                                                           *\n"
    "//---------------------------------------------------------------------------*\n"
    "\n"
    "int mainForLIBPM  (const int argc, const char * argv []) {\n"
    "  bool verboseOptionOn = true ;\n"
    "  PMSInt16 returnCode = 0 ; // No error\n"
    "  {\n"
    "  //--- Input/output parameters\n"
    "    const char * extensions [] = {\n" ;
  GALGAS_uint index_1897_ (0) ;
  if (in_PROGRAM_5F_RULE_5F_LIST.isValid ()) {
    cEnumerator_programRuleList enumerator_1897 (in_PROGRAM_5F_RULE_5F_LIST, true) ;
    while (enumerator_1897.hasCurrentObject ()) {
      result << "      " ;
      result << enumerator_1897.current_mSourceFileExtension (HERE).mAttribute_string.reader_utf_38_Representation (SOURCE_FILE_AT_LINE (46)).stringValue () ;
      result << ",\n" ;
      index_1897_.increment () ;
      enumerator_1897.gotoNextObject () ;
    }
  }
  result << "      NULL\n"
    "    } ;    \n"
    "    const char * helpMessages [] = {\n" ;
  GALGAS_uint index_2065_ (0) ;
  if (in_PROGRAM_5F_RULE_5F_LIST.isValid ()) {
    cEnumerator_programRuleList enumerator_2065 (in_PROGRAM_5F_RULE_5F_LIST, true) ;
    while (enumerator_2065.hasCurrentObject ()) {
      result << "      " ;
      result << enumerator_2065.current_mSourceFileHelp (HERE).mAttribute_string.reader_utf_38_Representation (SOURCE_FILE_AT_LINE (53)).stringValue () ;
      result << ",\n" ;
      index_2065_.increment () ;
      enumerator_2065.gotoNextObject () ;
    }
  }
  result << "      NULL\n"
    "    } ;    \n"
    "    TC_UniqueArray <C_String> sourceFilesArray ;\n"
    "  //--- Analyze Command Line Options\n"
    "    F_Analyze_CLI_Options (argc, argv,\n"
    "      #ifndef DO_NOT_GENERATE_CHECKINGS\n"
    "        \"version \" " ;
  result << in_VERSION.reader_utf_38_Representation (SOURCE_FILE_AT_LINE (61)).stringValue () ;
  result << " \" [debug]\",\n"
    "      #else\n"
    "        \"version \" " ;
  result << in_VERSION.reader_utf_38_Representation (SOURCE_FILE_AT_LINE (63)).stringValue () ;
  result << ",\n"
    "      #endif\n"
    "                           sourceFilesArray,\n"
    "                           extensions,\n"
    "                           helpMessages) ;\n"
    "  //--- Build galgas io object\n"
    "    C_galgas_io * galgasIOptr = NULL ;\n"
    "    macroMyNew (galgasIOptr, C_galgas_io (HERE)) ;\n"
    "  //--- Common lexique object\n"
    "    C_Compiler * commonLexique = NULL ;\n"
    "    macroMyNew (commonLexique, C_Compiler (NULL, \"\", \"\", galgasIOptr COMMA_HERE)) ;\n"
    "  //--- Ask Save On Close \? (Carbon and Windows SIOUX Only)\n"
    "    #ifdef SIOUX_IS_IMPLEMENTED\n"
    "      SIOUXSettings.asktosaveonclose = gOption_generic_5F_cli_5F_options_options_asktosaveonclose.mValue ;\n"
    "    #endif\n"
    "  //--- Enable 64 bit alloc debug \? Only if compiled in 64 bit and in debug mode\n"
    "    #ifndef DO_NOT_GENERATE_CHECKINGS\n"
    "      #ifdef __LP64__\n"
    "        if (gOption_generic_5F_cli_5F_options_enable_5F_allocation_5F_debugging.mValue) {\n"
    "          enableAllocDebugFor64BitTool () ;\n"
    "        }\n"
    "      #endif\n"
    "    #endif\n"
    "    try{\n"
    "      verboseOptionOn = gOption_galgas_5F_cli_5F_options_verbose_5F_output.mValue ;\n"
    "      routine_before (commonLexique COMMA_HERE) ;\n"
    "      for (PMSInt32 i=0 ; i<sourceFilesArray.count () ; i++) {\n"
    "        const C_String fileExtension = sourceFilesArray (i COMMA_HERE).pathExtension () ;\n"
    "        const GALGAS_string sfp = GALGAS_string (sourceFilesArray (i COMMA_HERE)) ;\n"
    "        const GALGAS_location location = commonLexique->here () ;\n"
    "        const GALGAS_lstring sourceFilePath (sfp, location) ;\n"
    "        PMSInt16 r = 0 ;\n"
    "        " ;
  GALGAS_uint index_3958_IDX (0) ;
  if (in_PROGRAM_5F_RULE_5F_LIST.isValid ()) {
    cEnumerator_programRuleList enumerator_3958 (in_PROGRAM_5F_RULE_5F_LIST, true) ;
    while (enumerator_3958.hasCurrentObject ()) {
      result << "if (fileExtension == " ;
      result << enumerator_3958.current_mSourceFileExtension (HERE).mAttribute_string.reader_utf_38_Representation (SOURCE_FILE_AT_LINE (98)).stringValue () ;
      result << ") {\n"
        "          routine_" ;
      result << GALGAS_string ("programRule_").operator_concat (index_3958_IDX.reader_string (SOURCE_FILE_AT_LINE (99)) COMMA_SOURCE_FILE_AT_LINE (99)).reader_identifierRepresentation (SOURCE_FILE_AT_LINE (99)).stringValue () ;
      result << " (sourceFilePath, commonLexique COMMA_HERE) ;\n" ;
      if (enumerator_3958.hasNextObject ()) {
        result << "        }else " ;
      }
      index_3958_IDX.increment () ;
      enumerator_3958.gotoNextObject () ;
    }
  }
  result << "        }else{\n"
    "          printf (\"*** Error: unhandled extension for file '%s' ***\\n\", sourceFilesArray (i COMMA_HERE).cString (HERE)) ;\n"
    "          r = 1 ;\n"
    "        }\n"
    "        if (r != 0) {\n"
    "          returnCode = r ;\n"
    "        }\n"
    "      }\n"
    "    //--- Error or warnings \?\n"
    "      if (commonLexique->totalErrorCount () > 0) {\n"
    "        returnCode = 1 ; // Error code\n"
    "      }else if (commonLexique->totalWarningCount () > 0) {\n"
    "        if (gOption_galgas_5F_cli_5F_options_treat_5F_warnings_5F_as_5F_error.mValue) {\n"
    "          returnCode = 1 ; // Error code\n"
    "          if (verboseOptionOn) {\n"
    "            printf (\"** Note: warnings are treated as errors. **\\n\") ;\n"
    "          }\n"
    "        }\n"
    "      }\n"
    "    //--- Epilogue\n"
    "      routine_after (commonLexique COMMA_HERE) ;\n"
    "    //--- Display error and warnings count\n"
    "      if (gOption_galgas_5F_cli_5F_options_verbose_5F_output.mValue || (commonLexique->totalWarningCount () > 0) || (commonLexique->totalErrorCount ()"
    " > 0)) {\n"
    "        if (commonLexique->totalWarningCount () == 0) {\n"
    "          printf (\"No warning\") ;\n"
    "        }else if (commonLexique->totalWarningCount () == 1) {\n"
    "          printf (\"1 warning\") ;\n"
    "        }else{\n"
    "          printf (\"%u warnings\", commonLexique->totalWarningCount ()) ;\n"
    "        }\n"
    "        printf (\", \") ;\n"
    "        if (commonLexique->totalErrorCount () == 0) {\n"
    "          printf (\"no error\") ;\n"
    "        }else if (commonLexique->totalErrorCount () == 1) {\n"
    "          printf (\"1 error\") ;\n"
    "        }else{\n"
    "          printf (\"%u errors\", commonLexique->totalErrorCount ()) ;\n"
    "        }\n"
    "        printf (\".\\n\") ;\n"
    "      }\n"
    "    }catch (const M_STD_NAMESPACE exception & e) {\n"
    "      F_default_display_exception (e) ;\n"
    "      returnCode = 1 ; // Error code\n"
    "    }catch (...) {\n"
    "      throw ;\n"
    "    }\n"
    "    macroDetachSharedObject (galgasIOptr) ;\n"
    "    macroDetachSharedObject (commonLexique) ;\n"
    "  }\n"
    "  return returnCode ;\n"
    "}\n"
    "\n" ;
  return GALGAS_string (result) ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//                       Routine 'compileBeforeClause'                       *
//                                                                           *
//---------------------------------------------------------------------------*

void routine_compileBeforeClause (const GALGAS_analysisContext constinArgument_inAnalysisContext,
                                  const GALGAS_programComponentAST constinArgument_inProgramComponentAST,
                                  GALGAS_semanticDeclarationSortedListForGeneration & ioArgument_ioDecoratedDeclarationListForGeneration,
                                  C_Compiler * inCompiler
                                  COMMA_UNUSED_LOCATION_ARGS) {
  //-------- @localVariableDeclarationForGeneration
  GALGAS_semanticInstructionListForGeneration var_semanticInstructionListForGeneration ;
  { //-------- @routineCallInstructionForGeneration
  GALGAS_formalParameterListForGeneration joker_3407_0 ; // Joker input parameter
  routine_analyzeRoutineBody (constinArgument_inAnalysisContext, GALGAS_formalParameterListAST::constructor_emptyList (SOURCE_FILE_AT_LINE (60)), GALGAS_localConstantList::constructor_emptyList (SOURCE_FILE_AT_LINE (61)), GALGAS_typedAttributeList::constructor_emptyList (SOURCE_FILE_AT_LINE (62)), GALGAS_string (""), constinArgument_inProgramComponentAST.reader_mPrologueInstructionList (SOURCE_FILE_AT_LINE (64)), constinArgument_inProgramComponentAST.reader_mEndOfPrologue (SOURCE_FILE_AT_LINE (65)), var_semanticInstructionListForGeneration, joker_3407_0, inCompiler COMMA_SOURCE_FILE_AT_LINE (58)) ;
  } //-------- @routineCallInstructionForGeneration
  //-------- @addAssignInstructionForGeneration
  ioArgument_ioDecoratedDeclarationListForGeneration.addAssign_operation (GALGAS_routineImplementationForGeneration::constructor_new (GALGAS_bool (true), GALGAS_string ("before"), GALGAS_formalParameterListForGeneration::constructor_emptyList (SOURCE_FILE_AT_LINE (72)), var_semanticInstructionListForGeneration COMMA_SOURCE_FILE_AT_LINE (69)), GALGAS_string ("") COMMA_SOURCE_FILE_AT_LINE (69)) ;
}


//---------------------------------------------------------------------------*
//                                                                           *
//                       Routine 'compileProgramRules'                       *
//                                                                           *
//---------------------------------------------------------------------------*

void routine_compileProgramRules (const GALGAS_analysisContext constinArgument_inAnalysisContext,
                                  const GALGAS_programComponentAST constinArgument_inProgramComponentAST,
                                  GALGAS_semanticDeclarationSortedListForGeneration & ioArgument_ioDecoratedDeclarationListForGeneration,
                                  C_Compiler * inCompiler
                                  COMMA_UNUSED_LOCATION_ARGS) {
  //-------- @localVariableOrConstantDeclarationWithSourceExpressionForGeneration
  GALGAS_uint var_ruleIndex = GALGAS_uint ((PMUInt32) 0U) ;
  //-------- @foreachInstructionForGeneration
  cEnumerator_programRuleList enumerator_4345 (constinArgument_inProgramComponentAST.reader_mProgramRules (SOURCE_FILE_AT_LINE (91)), true) ;
  //--- simple foreach instruction
  while (enumerator_4345.hasCurrentObject ()) {
    //-------- @localVariableOrConstantDeclarationWithConstructorCallForGeneration
    GALGAS_formalParameterListAST var_argumentList = GALGAS_formalParameterListAST::constructor_emptyList (SOURCE_FILE_AT_LINE (92)) ;
    //-------- @addAssignInstructionForGeneration
    var_argumentList.addAssign_operation (GALGAS_formalArgumentPassingModeAST::constructor_argumentConstantIn (SOURCE_FILE_AT_LINE (94)), GALGAS_lstring::constructor_new (GALGAS_string ("lstring"), inCompiler->here () COMMA_SOURCE_FILE_AT_LINE (95)), enumerator_4345.current_mSourceFileVariableName (HERE), enumerator_4345.current_mSourceFileVariableNameIsUnused (HERE) COMMA_SOURCE_FILE_AT_LINE (93)) ;
    //-------- @localVariableDeclarationForGeneration
    GALGAS_semanticInstructionListForGeneration var_semanticInstructionListForGeneration ;
    //-------- @localVariableDeclarationForGeneration
    GALGAS_formalParameterListForGeneration var_routineSignature ;
    { //-------- @routineCallInstructionForGeneration
    routine_analyzeRoutineBody (constinArgument_inAnalysisContext, var_argumentList, GALGAS_localConstantList::constructor_emptyList (SOURCE_FILE_AT_LINE (104)), GALGAS_typedAttributeList::constructor_emptyList (SOURCE_FILE_AT_LINE (105)), GALGAS_string (""), enumerator_4345.current_mInstructionList (HERE), enumerator_4345.current_mEndOfInstructionList (HERE), var_semanticInstructionListForGeneration, var_routineSignature, inCompiler COMMA_SOURCE_FILE_AT_LINE (101)) ;
    } //-------- @routineCallInstructionForGeneration
    //-------- @addAssignInstructionForGeneration
    ioArgument_ioDecoratedDeclarationListForGeneration.addAssign_operation (GALGAS_routineImplementationForGeneration::constructor_new (GALGAS_bool (true), GALGAS_string ("programRule_").operator_concat (var_ruleIndex.reader_string (SOURCE_FILE_AT_LINE (114)) COMMA_SOURCE_FILE_AT_LINE (114)), var_routineSignature, var_semanticInstructionListForGeneration COMMA_SOURCE_FILE_AT_LINE (112)), GALGAS_string ("") COMMA_SOURCE_FILE_AT_LINE (112)) ;
    //-------- @incrementInstructionForGeneration
    var_ruleIndex.increment_operation (inCompiler COMMA_SOURCE_FILE_AT_LINE (120)) ;
    enumerator_4345.gotoNextObject () ;
  }
}


//---------------------------------------------------------------------------*
//                                                                           *
//                       Routine 'compileAfterClause'                        *
//                                                                           *
//---------------------------------------------------------------------------*

void routine_compileAfterClause (const GALGAS_analysisContext constinArgument_inAnalysisContext,
                                 const GALGAS_programComponentAST constinArgument_inProgramComponentAST,
                                 GALGAS_semanticDeclarationSortedListForGeneration & ioArgument_ioDecoratedDeclarationListForGeneration,
                                 C_Compiler * inCompiler
                                 COMMA_UNUSED_LOCATION_ARGS) {
  //-------- @localVariableDeclarationForGeneration
  GALGAS_semanticInstructionListForGeneration var_semanticInstructionListForGeneration ;
  { //-------- @routineCallInstructionForGeneration
  GALGAS_formalParameterListForGeneration joker_6441_0 ; // Joker input parameter
  routine_analyzeRoutineBody (constinArgument_inAnalysisContext, GALGAS_formalParameterListAST::constructor_emptyList (SOURCE_FILE_AT_LINE (138)), GALGAS_localConstantList::constructor_emptyList (SOURCE_FILE_AT_LINE (139)), GALGAS_typedAttributeList::constructor_emptyList (SOURCE_FILE_AT_LINE (140)), GALGAS_string (""), constinArgument_inProgramComponentAST.reader_mEpilogueInstructionList (SOURCE_FILE_AT_LINE (142)), constinArgument_inProgramComponentAST.reader_mEndOfEpilogue (SOURCE_FILE_AT_LINE (143)), var_semanticInstructionListForGeneration, joker_6441_0, inCompiler COMMA_SOURCE_FILE_AT_LINE (136)) ;
  } //-------- @routineCallInstructionForGeneration
  //-------- @addAssignInstructionForGeneration
  ioArgument_ioDecoratedDeclarationListForGeneration.addAssign_operation (GALGAS_routineImplementationForGeneration::constructor_new (GALGAS_bool (true), GALGAS_string ("after"), GALGAS_formalParameterListForGeneration::constructor_emptyList (SOURCE_FILE_AT_LINE (150)), var_semanticInstructionListForGeneration COMMA_SOURCE_FILE_AT_LINE (147)), GALGAS_string ("") COMMA_SOURCE_FILE_AT_LINE (147)) ;
}


//---------------------------------------------------------------------------*
//                                                                           *
//                     Routine 'compileProgramComponent'                     *
//                                                                           *
//---------------------------------------------------------------------------*

void routine_compileProgramComponent (const GALGAS_lstring constinArgument_inSourceFile,
                                      const GALGAS_string constinArgument_inOutputDirectory,
                                      GALGAS_parsedComponentStruct & ioArgument_ioParsedComponentStruct,
                                      C_Compiler * inCompiler
                                      COMMA_UNUSED_LOCATION_ARGS) {
  //-------- @localVariableOrConstantDeclarationWithSourceExpressionForGeneration
  GALGAS_string var_basename = constinArgument_inSourceFile.mAttribute_string.reader_lastPathComponent (SOURCE_FILE_AT_LINE (169)).reader_stringByDeletingPathExtension (SOURCE_FILE_AT_LINE (169)) ;
  //-------- @localVariableOrConstantDeclarationWithConstructorCallForGeneration
  GALGAS_lstring var_basenameKey = GALGAS_lstring::constructor_new (var_basename, inCompiler->here () COMMA_SOURCE_FILE_AT_LINE (170)) ;
  //-------- @localVariableDeclarationForGeneration
  GALGAS_programComponentAST var_programComponentAST ;
  //-------- @ifInstructionForGeneration
  if (ioArgument_ioParsedComponentStruct.mAttribute_mParsedSyntaxComponentMap.reader_hasKey (var_basename COMMA_SOURCE_FILE_AT_LINE (172)).isValidAndTrue ()) {
    //-------- @methodCallInstructionForGeneration
    ioArgument_ioParsedComponentStruct.mAttribute_mParsedProgramComponentMap.method_searchKey (var_basenameKey, var_programComponentAST, inCompiler COMMA_SOURCE_FILE_AT_LINE (173)) ;
    //-------- END @methodCallInstructionForGeneration
  }else{
    { //-------- @grammarInstructionWithSourceFileForGeneration
    cGrammar_programSLRgrammar::_performSourceFileParsing_ (inCompiler, constinArgument_inSourceFile, var_programComponentAST COMMA_SOURCE_FILE_AT_LINE (175)) ;
    } //-------- END @grammarInstructionWithSourceFileForGeneration
    { //-------- @modifierCallInstructionForGeneration
    ioArgument_ioParsedComponentStruct.mAttribute_mParsedProgramComponentMap.modifier_insertKey (var_basenameKey, var_programComponentAST, inCompiler COMMA_SOURCE_FILE_AT_LINE (176)) ;
    } //-------- END @typeMethodInstructionForGeneration
  }
  //-------- @localVariableOrConstantDeclarationWithSourceExpressionForGeneration
  GALGAS_lstring var_componentName = var_programComponentAST.reader_mProgramComponentName (SOURCE_FILE_AT_LINE (179)) ;
  //-------- @ifInstructionForGeneration
  if (GALGAS_bool (kIsNotEqual, var_componentName.reader_string (SOURCE_FILE_AT_LINE (180)).objectCompare (var_basename)).isValidAndTrue ()) {
    //-------- @warningInstructionForGeneration
    GALGAS_location location_0 (var_componentName.reader_location (HERE)) ; // Implicit use of 'location' reader
    inCompiler->emitSemanticWarning (location_0, GALGAS_string ("GALGAS checks the component name ('").operator_concat (var_componentName.reader_string (SOURCE_FILE_AT_LINE (182)) COMMA_SOURCE_FILE_AT_LINE (182)).operator_concat (GALGAS_string ("') against the source file base name ('") COMMA_SOURCE_FILE_AT_LINE (183)).operator_concat (var_basename COMMA_SOURCE_FILE_AT_LINE (183)).operator_concat (GALGAS_string ("'): they should be identical") COMMA_SOURCE_FILE_AT_LINE (183)) COMMA_SOURCE_FILE_AT_LINE (181)) ;
  }
  //-------- @localVariableOrConstantDeclarationWithSourceExpressionForGeneration
  GALGAS_semanticDeclarationListAST var_semanticDeclarationList = var_programComponentAST.reader_mSemanticDeclarationList (SOURCE_FILE_AT_LINE (187)) ;
  //-------- @localVariableOrConstantDeclarationWithConstructorCallForGeneration
  GALGAS_stringset var_parsedFileSet = GALGAS_stringset::constructor_setWithString (constinArgument_inSourceFile.reader_string (SOURCE_FILE_AT_LINE (188)) COMMA_SOURCE_FILE_AT_LINE (188)) ;
  //-------- @localVariableOrConstantDeclarationWithConstructorCallForGeneration
  GALGAS_lstringlist var_optionComponentFileNameList = GALGAS_lstringlist::constructor_emptyList (SOURCE_FILE_AT_LINE (189)) ;
  //-------- @localVariableOrConstantDeclarationWithConstructorCallForGeneration
  GALGAS_grammarComponentASTList var_grammarComponentASTList = GALGAS_grammarComponentASTList::constructor_emptyList (SOURCE_FILE_AT_LINE (190)) ;
  //-------- @localVariableOrConstantDeclarationWithConstructorCallForGeneration
  GALGAS_stringlist var_headerIncludeList = GALGAS_stringlist::constructor_emptyList (SOURCE_FILE_AT_LINE (191)) ;
  //-------- @localVariableOrConstantDeclarationWithConstructorCallForGeneration
  GALGAS_stringlist var_implementationIncludeList = GALGAS_stringlist::constructor_emptyList (SOURCE_FILE_AT_LINE (192)) ;
  { //-------- @routineCallInstructionForGeneration
  routine_recursivelyImportSemanticComponent (ioArgument_ioParsedComponentStruct, var_optionComponentFileNameList, var_grammarComponentASTList, var_semanticDeclarationList, var_parsedFileSet, var_headerIncludeList, var_implementationIncludeList, var_programComponentAST.reader_mImportedComponentFileNameList (SOURCE_FILE_AT_LINE (201)), constinArgument_inSourceFile.mAttribute_string.reader_stringByDeletingLastPathComponent (SOURCE_FILE_AT_LINE (202)), inCompiler COMMA_SOURCE_FILE_AT_LINE (193)) ;
  } //-------- @routineCallInstructionForGeneration
  //-------- @localVariableOrConstantDeclarationWithSourceExpressionForGeneration
  GALGAS_semanticDeclarationListAST var_semanticDeclarationListWithPredefinedTypes = var_semanticDeclarationList ;
  { //-------- @routineCallInstructionForGeneration
  routine_appendPredefinedTypesASTs (var_semanticDeclarationListWithPredefinedTypes, inCompiler COMMA_SOURCE_FILE_AT_LINE (206)) ;
  } //-------- @routineCallInstructionForGeneration
  //-------- @localVariableDeclarationForGeneration
  GALGAS_semanticContext var_semanticContext ;
  { //-------- @routineCallInstructionForGeneration
  routine_buildSemanticContext (constinArgument_inSourceFile.reader_string (SOURCE_FILE_AT_LINE (210)), var_semanticDeclarationListWithPredefinedTypes, var_programComponentAST.reader_mEndOfSourceFile (SOURCE_FILE_AT_LINE (212)), var_semanticContext, inCompiler COMMA_SOURCE_FILE_AT_LINE (209)) ;
  } //-------- @routineCallInstructionForGeneration
  { //-------- @routineCallInstructionForGeneration
  routine_buildGrammarComponentMapForSemanticAnalysis (var_grammarComponentASTList, var_semanticContext, inCompiler COMMA_SOURCE_FILE_AT_LINE (216)) ;
  } //-------- @routineCallInstructionForGeneration
  { //-------- @routineCallInstructionForGeneration
  routine_buildOptionComponentMapForSemanticAnalysis (var_optionComponentFileNameList, ioArgument_ioParsedComponentStruct, var_semanticContext.mAttribute_mOptionComponentMapForSemanticAnalysis, inCompiler COMMA_SOURCE_FILE_AT_LINE (221)) ;
  } //-------- @routineCallInstructionForGeneration
  //-------- @localVariableDeclarationForGeneration
  GALGAS_semanticDeclarationSortedListForGeneration var_decoratedDeclarationListForGeneration ;
  { //-------- @routineCallInstructionForGeneration
  routine_performSemanticAnalysis (var_programComponentAST.reader_mSemanticDeclarationList (SOURCE_FILE_AT_LINE (229)), var_semanticContext, var_decoratedDeclarationListForGeneration, inCompiler COMMA_SOURCE_FILE_AT_LINE (228)) ;
  } //-------- @routineCallInstructionForGeneration
  //-------- @localVariableOrConstantDeclarationWithConstructorCallForGeneration
  GALGAS_analysisContext var_analysisContext = GALGAS_analysisContext::constructor_new (var_semanticContext, function_buildPredefinedTypes (var_semanticContext, inCompiler COMMA_SOURCE_FILE_AT_LINE (236)), GALGAS_unifiedTypeMapProxy::constructor_null (SOURCE_FILE_AT_LINE (237)), GALGAS_string ("") COMMA_SOURCE_FILE_AT_LINE (234)) ;
  { //-------- @routineCallInstructionForGeneration
  routine_compileBeforeClause (var_analysisContext, var_programComponentAST, var_decoratedDeclarationListForGeneration, inCompiler COMMA_SOURCE_FILE_AT_LINE (241)) ;
  } //-------- @routineCallInstructionForGeneration
  { //-------- @routineCallInstructionForGeneration
  routine_compileProgramRules (var_analysisContext, var_programComponentAST, var_decoratedDeclarationListForGeneration, inCompiler COMMA_SOURCE_FILE_AT_LINE (247)) ;
  } //-------- @routineCallInstructionForGeneration
  { //-------- @routineCallInstructionForGeneration
  routine_compileAfterClause (var_analysisContext, var_programComponentAST, var_decoratedDeclarationListForGeneration, inCompiler COMMA_SOURCE_FILE_AT_LINE (253)) ;
  } //-------- @routineCallInstructionForGeneration
  //-------- @ifInstructionForGeneration
  if (GALGAS_bool (kIsEqual, GALGAS_uint::constructor_errorCount (inCompiler COMMA_SOURCE_FILE_AT_LINE (259)).objectCompare (GALGAS_uint ((PMUInt32) 0U))).isValidAndTrue ()) {
    //-------- @localVariableOrConstantDeclarationWithSourceExpressionForGeneration
    GALGAS_string var_headerString = GALGAS_string (filewrapperTemplate_programFileGenerationTemplate_programFileHeader (inCompiler, var_componentName.reader_string (SOURCE_FILE_AT_LINE (261)), var_headerIncludeList, var_semanticContext.mAttribute_mTypeMap.reader_allKeyList (SOURCE_FILE_AT_LINE (263)) COMMA_SOURCE_FILE_AT_LINE (260))) ;
    //-------- @foreachInstructionForGeneration
    cEnumerator_semanticDeclarationSortedListForGeneration enumerator_11013 (var_decoratedDeclarationListForGeneration, true) ;
    //--- simple foreach instruction
    while (enumerator_11013.hasCurrentObject ()) {
      //-------- @appendInstructionForGeneration
      var_headerString.dotAssign_operation (callCategoryReader_appendDeclaration_31_ ((const cPtr_semanticDeclarationForGeneration *) enumerator_11013.current_mDeclaration (HERE).ptr (), inCompiler COMMA_SOURCE_FILE_AT_LINE (266)) COMMA_SOURCE_FILE_AT_LINE (266)) ;
      enumerator_11013.gotoNextObject () ;
    }
    //-------- @foreachInstructionForGeneration
    cEnumerator_semanticDeclarationSortedListForGeneration enumerator_11142 (var_decoratedDeclarationListForGeneration, true) ;
    //--- simple foreach instruction
    while (enumerator_11142.hasCurrentObject ()) {
      //-------- @appendInstructionForGeneration
      var_headerString.dotAssign_operation (callCategoryReader_appendDeclaration_32_ ((const cPtr_semanticDeclarationForGeneration *) enumerator_11142.current_mDeclaration (HERE).ptr (), constinArgument_inOutputDirectory, inCompiler COMMA_SOURCE_FILE_AT_LINE (269)) COMMA_SOURCE_FILE_AT_LINE (269)) ;
      enumerator_11142.gotoNextObject () ;
    }
    { //-------- @typeMethodInstructionForGeneration
    GALGAS_string::class_method_generateFile (constinArgument_inOutputDirectory, var_componentName.reader_string (SOURCE_FILE_AT_LINE (273)).operator_concat (GALGAS_string (".h") COMMA_SOURCE_FILE_AT_LINE (273)), GALGAS_string ("//"), GALGAS_string ("\n"
      "\n"), var_headerString, GALGAS_string ("\n"
      "\n"), GALGAS_string ("#endif\n"), inCompiler COMMA_SOURCE_FILE_AT_LINE (271)) ;
    } //-------- @routineCallInstructionForGeneration
  }
  //-------- @ifInstructionForGeneration
  if (GALGAS_bool (kIsEqual, GALGAS_uint::constructor_errorCount (inCompiler COMMA_SOURCE_FILE_AT_LINE (282)).objectCompare (GALGAS_uint ((PMUInt32) 0U))).isValidAndTrue ()) {
    //-------- @localVariableOrConstantDeclarationWithSourceExpressionForGeneration
    GALGAS_string var_implementationString = GALGAS_string (filewrapperTemplate_programFileGenerationTemplate_programFileImplementation (inCompiler, var_componentName.reader_string (SOURCE_FILE_AT_LINE (284)), var_implementationIncludeList, var_programComponentAST.reader_mProgramRules (SOURCE_FILE_AT_LINE (286)), var_programComponentAST.reader_mVersionString (SOURCE_FILE_AT_LINE (287)).reader_string (SOURCE_FILE_AT_LINE (287)) COMMA_SOURCE_FILE_AT_LINE (283))) ;
    //-------- @foreachInstructionForGeneration
    cEnumerator_semanticDeclarationSortedListForGeneration enumerator_11858 (var_decoratedDeclarationListForGeneration, true) ;
    //--- simple foreach instruction
    while (enumerator_11858.hasCurrentObject ()) {
      //-------- @appendInstructionForGeneration
      var_implementationString.dotAssign_operation (callCategoryReader_appendTypeGenericImplementation ((const cPtr_semanticDeclarationForGeneration *) enumerator_11858.current_mDeclaration (HERE).ptr (), inCompiler COMMA_SOURCE_FILE_AT_LINE (290)) COMMA_SOURCE_FILE_AT_LINE (290)) ;
      //-------- @appendInstructionForGeneration
      var_implementationString.dotAssign_operation (callCategoryReader_appendSpecificImplementation ((const cPtr_semanticDeclarationForGeneration *) enumerator_11858.current_mDeclaration (HERE).ptr (), inCompiler COMMA_SOURCE_FILE_AT_LINE (291)) COMMA_SOURCE_FILE_AT_LINE (291)) ;
      enumerator_11858.gotoNextObject () ;
    }
    { //-------- @typeMethodInstructionForGeneration
    GALGAS_string::class_method_generateFile (constinArgument_inOutputDirectory, var_componentName.reader_string (SOURCE_FILE_AT_LINE (295)).operator_concat (GALGAS_string (".cpp") COMMA_SOURCE_FILE_AT_LINE (295)), GALGAS_string ("//"), GALGAS_string ("\n"
      "\n"), var_implementationString, GALGAS_string ("\n"
      "\n"), GALGAS_string ("\n"), inCompiler COMMA_SOURCE_FILE_AT_LINE (293)) ;
    } //-------- @routineCallInstructionForGeneration
  }
}


//--- START OF USER ZONE 2


//--- END OF USER ZONE 2


