//---------------------------------------------------------------------------*
//                                                                           *
//               File 'semanticInstructionListModelBuilder.h'                *
//         Generated by version GALGAS_BETA_VERSION (LL(1) grammar)          *
//                     august 30th, 2007, at 14h41'28"                       *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

#ifndef semanticInstructionListModelBuilder_DEFINED
#define semanticInstructionListModelBuilder_DEFINED

#include <string.h>

//---------------------------------------------------------------------------*

#include "galgas/C_GGS_Object.h"
#include "galgas/GGS_location.h"
#include "galgas/GGS_lbool.h"
#include "galgas/GGS_lchar.h"
#include "galgas/GGS_lstring.h"
#include "galgas/GGS_ldouble.h"
#include "galgas/GGS_luint.h"
#include "galgas/GGS_lsint.h"
#include "galgas/GGS_luint64.h"
#include "galgas/GGS_lsint64.h"
#include "galgas/GGS_stringset.h"
#include "galgas/GGS_binaryset.h"
#include "galgas/predefined_types.h"
#include "galgas/AC_galgas_class.h"
#include "galgas/AC_galgas_entity.h"
#include "galgas/AC_galgas_domain.h"
#include "galgas/AC_galgas_mapindex.h"
#include "galgas/AC_galgas_map.h"
#include "galgas/AC_galgas_list.h"
#include "galgas/AC_galgas_sortedlist.h"

//---------------------------------------------------------------------------*

#include "galgas_scanner.h"

// Include imported semantics
#include "expressionMetamodel.h"
#include "instructionMetamodel.h"
#include "parameterArgumentMetamodel.h"

//--- START OF USER ZONE 2


//--- END OF USER ZONE 2

//---------------------------------------------------------------------------*
//                                                                           *
//                          Class Predeclarations                            *
//                                                                           *
//---------------------------------------------------------------------------*


//---------------------------------------------------------------------------*
//                                                                           *
//       Parser class semanticInstructionListModelBuilder declaration        *
//                                                                           *
//---------------------------------------------------------------------------*

class semanticInstructionListModelBuilder {
  public : virtual ~semanticInstructionListModelBuilder (void) {}

  protected : virtual GGS_semanticInstructions nt_semantic_instruction_list_ (galgas_scanner &) = 0 ;

  protected : virtual GGS_semanticInstruction nt_semantic_instruction_ (galgas_scanner &) = 0 ;

  protected : virtual GGS_semanticExpression nt_expression_ (galgas_scanner &) = 0 ;

  protected : virtual GGS_foreachInstructionEnumeratedObject nt_foreach_enumerated_object_ (galgas_scanner &) = 0 ;

  protected : virtual GGS_actualParameters nt_actual_parameter_list_ (galgas_scanner &) = 0 ;

  protected : virtual GGS_matchInstructionBranch nt_match_instruction_branch_ (galgas_scanner &) = 0 ;

  protected : virtual GGS_castInstructionBranch nt_cast_instruction_branch_ (galgas_scanner &) = 0 ;

  protected : virtual GGS_elseOrDefaultForCastInstruction nt_cast_else_or_default_ (galgas_scanner &) = 0 ;

  protected : virtual GGS_outExpressionList nt_output_expression_list_ (galgas_scanner &) = 0 ;

  protected : virtual GGS_matchEntry nt_match_entry_ (galgas_scanner &) = 0 ;

  protected : virtual GGS_semanticDeclaration nt_semantic_declaration_ (galgas_scanner &) = 0 ;

  protected : virtual GGS_formalParameters nt_formal_parameter_list_ (galgas_scanner &) = 0 ;

  protected : GGS_semanticInstructions pr_semantic_instruction_list_semanticInstructionListModelBuilder_58_5_ (galgas_scanner &) ;

  protected : virtual sint16 select_repeat_semanticInstructionListModelBuilder_0 (galgas_scanner &) = 0 ;

  protected : GGS_routineDeclaration pr_semantic_declaration_semanticInstructionListModelBuilder_71_5_ (galgas_scanner &) ;

  protected : GGS_externRoutineDeclaration pr_semantic_declaration_semanticInstructionListModelBuilder_88_5_ (galgas_scanner &) ;

  protected : GGS_semanticInstruction pr_semantic_instruction_semanticInstructionListModelBuilder_102_5_ (galgas_scanner &) ;

  protected : virtual sint16 select_semanticInstructionListModelBuilder_1 (galgas_scanner &) = 0 ;

  protected : GGS_assignmentInstruction pr_semantic_instruction_semanticInstructionListModelBuilder_132_5_ (galgas_scanner &) ;

  protected : GGS_incrementInstruction pr_semantic_instruction_semanticInstructionListModelBuilder_145_5_ (galgas_scanner &) ;

  protected : GGS_decrementInstruction pr_semantic_instruction_semanticInstructionListModelBuilder_157_5_ (galgas_scanner &) ;

  protected : GGS_foreachInstructionEnumeratedObject pr_foreach_enumerated_object_semanticInstructionListModelBuilder_169_5_ (galgas_scanner &) ;

  protected : virtual sint16 select_repeat_semanticInstructionListModelBuilder_2 (galgas_scanner &) = 0 ;

  protected : virtual sint16 select_semanticInstructionListModelBuilder_3 (galgas_scanner &) = 0 ;

  protected : GGS_foreachInstruction pr_semantic_instruction_semanticInstructionListModelBuilder_208_5_ (galgas_scanner &) ;

  protected : virtual sint16 select_repeat_semanticInstructionListModelBuilder_4 (galgas_scanner &) = 0 ;

  protected : virtual sint16 select_semanticInstructionListModelBuilder_5 (galgas_scanner &) = 0 ;

  protected : GGS_ifInstruction pr_semantic_instruction_semanticInstructionListModelBuilder_234_5_ (galgas_scanner &) ;

  protected : virtual sint16 select_repeat_semanticInstructionListModelBuilder_6 (galgas_scanner &) = 0 ;

  protected : virtual sint16 select_semanticInstructionListModelBuilder_7 (galgas_scanner &) = 0 ;

  protected : GGS_methodCallInstruction pr_semantic_instruction_semanticInstructionListModelBuilder_259_5_ (galgas_scanner &) ;

  protected : GGS_modifierCallInstruction pr_semantic_instruction_semanticInstructionListModelBuilder_274_5_ (galgas_scanner &) ;

  protected : GGS_errorInstruction pr_semantic_instruction_semanticInstructionListModelBuilder_290_5_ (galgas_scanner &) ;

  protected : virtual sint16 select_semanticInstructionListModelBuilder_8 (galgas_scanner &) = 0 ;

  protected : virtual sint16 select_repeat_semanticInstructionListModelBuilder_9 (galgas_scanner &) = 0 ;

  protected : GGS_warningInstruction pr_semantic_instruction_semanticInstructionListModelBuilder_316_5_ (galgas_scanner &) ;

  protected : GGS_routineCallInstruction pr_semantic_instruction_semanticInstructionListModelBuilder_330_5_ (galgas_scanner &) ;

  protected : GGS_constantMatchEntry pr_match_entry_semanticInstructionListModelBuilder_342_5_ (galgas_scanner &) ;

  protected : GGS_classMatchEntry pr_match_entry_semanticInstructionListModelBuilder_348_5_ (galgas_scanner &) ;

  protected : virtual sint16 select_repeat_semanticInstructionListModelBuilder_10 (galgas_scanner &) = 0 ;

  protected : virtual sint16 select_semanticInstructionListModelBuilder_11 (galgas_scanner &) = 0 ;

  protected : GGS_matchInstructionBranch pr_match_instruction_branch_semanticInstructionListModelBuilder_387_5_ (galgas_scanner &) ;

  protected : virtual sint16 select_repeat_semanticInstructionListModelBuilder_12 (galgas_scanner &) = 0 ;

  protected : GGS_matchInstruction pr_semantic_instruction_semanticInstructionListModelBuilder_400_5_ (galgas_scanner &) ;

  protected : virtual sint16 select_repeat_semanticInstructionListModelBuilder_13 (galgas_scanner &) = 0 ;

  protected : virtual sint16 select_repeat_semanticInstructionListModelBuilder_14 (galgas_scanner &) = 0 ;

  protected : virtual sint16 select_semanticInstructionListModelBuilder_15 (galgas_scanner &) = 0 ;

  protected : GGS_castInstructionBranch pr_cast_instruction_branch_semanticInstructionListModelBuilder_434_5_ (galgas_scanner &) ;

  protected : virtual sint16 select_semanticInstructionListModelBuilder_16 (galgas_scanner &) = 0 ;

  protected : virtual sint16 select_semanticInstructionListModelBuilder_17 (galgas_scanner &) = 0 ;

  protected : GGS_elseForCastInstruction pr_cast_else_or_default_semanticInstructionListModelBuilder_461_5_ (galgas_scanner &) ;

  protected : GGS_defaultForCastInstruction pr_cast_else_or_default_semanticInstructionListModelBuilder_468_5_ (galgas_scanner &) ;

  protected : GGS_castInstruction pr_semantic_instruction_semanticInstructionListModelBuilder_476_5_ (galgas_scanner &) ;

  protected : virtual sint16 select_repeat_semanticInstructionListModelBuilder_18 (galgas_scanner &) = 0 ;

  protected : GGS_addInstruction pr_semantic_instruction_semanticInstructionListModelBuilder_496_5_ (galgas_scanner &) ;

  protected : GGS_appendInstruction pr_semantic_instruction_semanticInstructionListModelBuilder_509_5_ (galgas_scanner &) ;

  protected : GGS_loopInstruction pr_semantic_instruction_semanticInstructionListModelBuilder_522_5_ (galgas_scanner &) ;

  protected : GGS_messageInstruction pr_semantic_instruction_semanticInstructionListModelBuilder_542_5_ (galgas_scanner &) ;

  protected : GGS_logInstruction pr_semantic_instruction_semanticInstructionListModelBuilder_554_5_ (galgas_scanner &) ;

  protected : virtual sint16 select_repeat_semanticInstructionListModelBuilder_19 (galgas_scanner &) = 0 ;

  protected : GGS_grammarInstruction pr_semantic_instruction_semanticInstructionListModelBuilder_573_5_ (galgas_scanner &) ;

  protected : virtual sint16 select_semanticInstructionListModelBuilder_20 (galgas_scanner &) = 0 ;

  protected : virtual sint16 select_semanticInstructionListModelBuilder_21 (galgas_scanner &) = 0 ;

  protected : GGS_treewalkingInstruction pr_semantic_instruction_semanticInstructionListModelBuilder_600_5_ (galgas_scanner &) ;

  protected : GGS_typeMethodInstruction pr_semantic_instruction_semanticInstructionListModelBuilder_615_5_ (galgas_scanner &) ;

} ;

//---------------------------------------------------------------------------*

#endif
