//---------------------------------------------------------------------------*
//                                                                           *
//                       File 'semanticAnalysis.cpp'                         *
//                 Generated by version GALGAS_BETA_VERSION                  *
//                      march 22th, 2010, at 17h23'29"                       *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

//---------------------------------------------------------------------------*

#include "version_libpm.h"
#if CURRENT_LIBPM_VERSION != VERSION_OF_LIBPM_USED_BY_GALGAS_COMPILER
  #error "This file has been compiled with a version of GALGAS that uses libpm version VERSION_OF_LIBPM_USED_BY_GALGAS_COMPILER, different than the current version (CURRENT_LIBPM_VERSION) of libpm"
#endif

//---------------------------------------------------------------------------*

#include <typeinfo>
#include "utilities/MF_MemoryControl.h"
#include "files/C_TextFileWrite.h"
#include "galgas/C_galgas_CLI_Options.h"
#include "semanticAnalysis.h"

//---------------------------------------------------------------------------*

#ifndef DO_NOT_GENERATE_CHECKINGS
  #define SOURCE_FILE_AT_LINE(line) "semanticAnalysis.gSemantics", line
  #define COMMA_SOURCE_FILE_AT_LINE(line) , SOURCE_FILE_AT_LINE(line)
#else
  #define SOURCE_FILE_AT_LINE(line) 
  #define COMMA_SOURCE_FILE_AT_LINE(line) 
#endif


//--- START OF USER ZONE 2


//--- END OF USER ZONE 2

//---------------------------------------------------------------------------*
//                                                                           *
//            Implementation of routine "checkMethodSignatures"              *
//                                                                           *
//---------------------------------------------------------------------------*

void routine_checkMethodSignatures (C_Compiler & inLexique,
                                const GGS_formalParameterListForGeneration   var_cas_inTestedSignature,
                                const GGS_location   var_cas_inErrorLocation,
                                const GGS_formalParameterSignature   var_cas_inReferenceSignature,
                                const GGS_location   var_cas_inReferenceLocation COMMA_UNUSED_LOCATION_ARGS) {
  #ifdef DEBUG_TRACE_ENABLED
    printf ("ENTER routine_checkMethodSignatures at %s:%d\n", __FILE__, __LINE__) ;
  #endif
  const GGS_bool cond_2501 = (var_cas_inTestedSignature.reader_length ()).operator_isNotEqual (var_cas_inReferenceSignature.reader_length ()) ;
  if (cond_2501.isBuiltAndTrue ()) {
    var_cas_inErrorLocation.reader_location (inLexique COMMA_HERE).signalGGSSemanticError (inLexique, (((GGS_string ("this method declares ")).operator_concat (var_cas_inTestedSignature.reader_length ().reader_string (inLexique COMMA_SOURCE_FILE_AT_LINE (37)))).operator_concat (GGS_string (" formal parameter(s), but overriden method declares "))).operator_concat (var_cas_inReferenceSignature.reader_length ().reader_string (inLexique COMMA_SOURCE_FILE_AT_LINE (38))) COMMA_SOURCE_FILE_AT_LINE (40)) ;
    var_cas_inReferenceLocation.reader_location (inLexique COMMA_HERE).signalGGSSemanticError (inLexique, GGS_string ("overriden method is declared here") COMMA_SOURCE_FILE_AT_LINE (41)) ;
  }else if (cond_2501.isBuiltAndFalse ()) {
    {
      GGS_formalParameterSignature::cEnumerator enumerator_2534 (var_cas_inReferenceSignature, true) ;
      const GGS_formalParameterSignature::cElement * operand_2534 = NULL ;
      GGS_formalParameterListForGeneration::cEnumerator enumerator_2569 (var_cas_inTestedSignature, true) ;
      const GGS_formalParameterListForGeneration::cElement * operand_2569 = NULL ;
      while (((operand_2534 = enumerator_2534.nextObject ()))
          && ((operand_2569 = enumerator_2569.nextObject ()))) {
        macroValidPointer (operand_2534) ;
        macroValidPointer (operand_2569) ;
        const GGS_bool cond_3012 = (operand_2534->mFormalParameterPassingMode).operator_isNotEqual (operand_2569->mFormalParameterPassingMode) ;
        if (cond_3012.isBuiltAndTrue ()) {
          operand_2569->mFormalParameterName.reader_location (inLexique COMMA_HERE).signalGGSSemanticError (inLexique, (((((GGS_string ("the '")).operator_concat (operand_2569->mFormalParameterName)).operator_concat (GGS_string ("' formal parameter is declared as "))).operator_concat (operand_2569->mFormalParameterPassingMode.reader_formalArgumentMessage (inLexique COMMA_SOURCE_FILE_AT_LINE (45)))).operator_concat (GGS_string (", but overriden method declares it as "))).operator_concat (operand_2534->mFormalParameterPassingMode.reader_formalArgumentMessage (inLexique COMMA_SOURCE_FILE_AT_LINE (46))) COMMA_SOURCE_FILE_AT_LINE (47)) ;
          var_cas_inReferenceLocation.reader_location (inLexique COMMA_HERE).signalGGSSemanticError (inLexique, GGS_string ("overriden method is declared here") COMMA_SOURCE_FILE_AT_LINE (48)) ;
        }
        const GGS_bool cond_3428 = (operand_2569->mFormalParameterType.reader_key (inLexique COMMA_SOURCE_FILE_AT_LINE (49)).reader_string (inLexique COMMA_SOURCE_FILE_AT_LINE (49))).operator_isNotEqual (operand_2534->mParameterType.reader_key (inLexique COMMA_SOURCE_FILE_AT_LINE (49)).reader_string (inLexique COMMA_SOURCE_FILE_AT_LINE (49))) ;
        if (cond_3428.isBuiltAndTrue ()) {
          operand_2569->mFormalParameterName.reader_location (inLexique COMMA_HERE).signalGGSSemanticError (inLexique, ((((((GGS_string ("the '")).operator_concat (operand_2569->mFormalParameterName)).operator_concat (GGS_string ("' formal parameter has the '@"))).operator_concat (operand_2569->mFormalParameterType.reader_key (inLexique COMMA_SOURCE_FILE_AT_LINE (51)))).operator_concat (GGS_string ("' type, but overriden method declares with the '@"))).operator_concat (operand_2534->mParameterType.reader_key (inLexique COMMA_SOURCE_FILE_AT_LINE (52)))).operator_concat (GGS_string ("' type")) COMMA_SOURCE_FILE_AT_LINE (53)) ;
          var_cas_inReferenceLocation.reader_location (inLexique COMMA_HERE).signalGGSSemanticError (inLexique, GGS_string ("overriden method is declared here") COMMA_SOURCE_FILE_AT_LINE (54)) ;
        }
      }
    }
  }
  #ifdef DEBUG_TRACE_ENABLED
    printf ("LEAVE routine_checkMethodSignatures\n") ;
  #endif
}

//---------------------------------------------------------------------------*
//                                                                           *
//    Category method '@semanticDeclarationAST.performSemanticAnalysis'      *
//                                                                           *
//---------------------------------------------------------------------------*

static void
category_method__semanticDeclarationAST__performSemanticAnalysis (C_Compiler &,
                                const cPtr_semanticDeclarationAST * operand_3923,
                                GGS_semanticContext & /* var_cas_inSemanticContext */,
                                GGS_semanticDeclarationListForGeneration  & /* var_cas_ioSemanticDeclarationListForGeneration */
                                COMMA_UNUSED_LOCATION_ARGS) {
  if (operand_3923 != NULL) {
  }
}

//---------------------------------------------------------------------------*
//                                                                           *
//Virtual Table for category method '@semanticDeclarationAST.performSemanticAnalysis'*
//                                                                           *
//---------------------------------------------------------------------------*

static TC_UniqueArray <typeCategoryMethod__semanticDeclarationAST__performSemanticAnalysis> gDispatchTableForMethod__semanticDeclarationAST__performSemanticAnalysis ;

//---------------------------------------------------------------------------*

void
enterCategoryMethod__semanticDeclarationAST__performSemanticAnalysis (typeCategoryMethod__semanticDeclarationAST__performSemanticAnalysis inRoutine,
                     const PMSInt32 inClassID) {
  gDispatchTableForMethod__semanticDeclarationAST__performSemanticAnalysis.forceObjectAtIndex (inClassID, inRoutine, NULL COMMA_HERE) ;
}

//---------------------------------------------------------------------------*

typeCategoryMethod__semanticDeclarationAST__performSemanticAnalysis
findCategoryMethod__semanticDeclarationAST__performSemanticAnalysis (AC_galgasClassRunTimeInformationEX * inClassPtr) {
  typeCategoryMethod__semanticDeclarationAST__performSemanticAnalysis result = NULL ;
  if (inClassPtr->slotID () < gDispatchTableForMethod__semanticDeclarationAST__performSemanticAnalysis.count ()) {
    result = gDispatchTableForMethod__semanticDeclarationAST__performSemanticAnalysis (inClassPtr->slotID () COMMA_HERE) ;
  }
  if (result == NULL) {
    AC_galgasClassRunTimeInformationEX * superClassPtr = inClassPtr->superClassPtr () ;
    if (superClassPtr != NULL) {
      result = findCategoryMethod__semanticDeclarationAST__performSemanticAnalysis (superClassPtr) ;
      gDispatchTableForMethod__semanticDeclarationAST__performSemanticAnalysis.forceObjectAtIndex (inClassPtr->slotID (), result, NULL COMMA_HERE) ;
    }
  }
  return result ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//       Category method '@predefinedTypeAST.performSemanticAnalysis'        *
//                                                                           *
//---------------------------------------------------------------------------*

static void
category_method__predefinedTypeAST__performSemanticAnalysis (C_Compiler & inLexique,
                                const cPtr_predefinedTypeAST * operand_4211,
                                GGS_semanticContext & var_cas_inSemanticContext,
                                GGS_semanticDeclarationListForGeneration  & var_cas_ioSemanticDeclarationListForGeneration
                                COMMA_UNUSED_LOCATION_ARGS) {
  if (operand_4211 != NULL) {
    GGS_unifiedTypeMapIndex  var_cas_idx ;
    GGS_unifiedTypeMapIndex::class_method_makeRegularIndex (inLexique, GGS_lstring ::constructor_new (inLexique, operand_4211->mPredefinedTypeName, GGS_location (inLexique) COMMA_SOURCE_FILE_AT_LINE (78)), var_cas_inSemanticContext.mTypeMap, var_cas_idx COMMA_SOURCE_FILE_AT_LINE (78)) ;
    var_cas_ioSemanticDeclarationListForGeneration.addAssign_operation (GGS_primitiveTypeForGeneration ::constructor_new (inLexique, var_cas_idx COMMA_SOURCE_FILE_AT_LINE (79))) ;
  }
}

//---------------------------------------------------------------------------*
//                                                                           *
//      Category method '@listDeclarationAST.performSemanticAnalysis'        *
//                                                                           *
//---------------------------------------------------------------------------*

static void
category_method__listDeclarationAST__performSemanticAnalysis (C_Compiler & inLexique,
                                const cPtr_listDeclarationAST * operand_4732,
                                GGS_semanticContext & var_cas_inSemanticContext,
                                GGS_semanticDeclarationListForGeneration  & var_cas_ioSemanticDeclarationListForGeneration
                                COMMA_UNUSED_LOCATION_ARGS) {
  if (operand_4732 != NULL) {
    GGS_typedAttributeList  var_cas_typedAttributeList = GGS_typedAttributeList ::constructor_emptyList () ;
    {
      GGS_attributeInCollectionListAST::cEnumerator enumerator_4934 (operand_4732->mAttributeList, true) ;
      const GGS_attributeInCollectionListAST::cElement * operand_4934 = NULL ;
      while (((operand_4934 = enumerator_4934.nextObject ()))) {
        macroValidPointer (operand_4934) ;
        GGS_unifiedTypeMapIndex  var_cas_idx ;
        GGS_unifiedTypeMapIndex::class_method_makeRegularIndex (inLexique, operand_4934->mAttributeTypeName, var_cas_inSemanticContext.mTypeMap, var_cas_idx COMMA_SOURCE_FILE_AT_LINE (94)) ;
        var_cas_typedAttributeList.addAssign_operation (var_cas_idx, operand_4934->mAttributeName) ;
      }
    }
    GGS_unifiedTypeMapIndex  var_cas_idx ;
    GGS_unifiedTypeMapIndex::class_method_makeRegularIndex (inLexique, operand_4732->mListTypeName, var_cas_inSemanticContext.mTypeMap, var_cas_idx COMMA_SOURCE_FILE_AT_LINE (101)) ;
    var_cas_ioSemanticDeclarationListForGeneration.addAssign_operation (GGS_listTypeForGeneration ::constructor_new (inLexique, var_cas_idx, var_cas_typedAttributeList COMMA_SOURCE_FILE_AT_LINE (102))) ;
  }
}

//---------------------------------------------------------------------------*
//                                                                           *
//     Category method '@structDeclarationAST.performSemanticAnalysis'       *
//                                                                           *
//---------------------------------------------------------------------------*

static void
category_method__structDeclarationAST__performSemanticAnalysis (C_Compiler & inLexique,
                                const cPtr_structDeclarationAST * operand_5542,
                                GGS_semanticContext & var_cas_inSemanticContext,
                                GGS_semanticDeclarationListForGeneration  & var_cas_ioSemanticDeclarationListForGeneration
                                COMMA_UNUSED_LOCATION_ARGS) {
  if (operand_5542 != NULL) {
    GGS_typedAttributeList  var_cas_typedAttributeList = GGS_typedAttributeList ::constructor_emptyList () ;
    {
      GGS_attributeInCollectionListAST::cEnumerator enumerator_5744 (operand_5542->mAttributeList, true) ;
      const GGS_attributeInCollectionListAST::cElement * operand_5744 = NULL ;
      while (((operand_5744 = enumerator_5744.nextObject ()))) {
        macroValidPointer (operand_5744) ;
        GGS_unifiedTypeMapIndex  var_cas_idx ;
        GGS_unifiedTypeMapIndex::class_method_makeRegularIndex (inLexique, operand_5744->mAttributeTypeName, var_cas_inSemanticContext.mTypeMap, var_cas_idx COMMA_SOURCE_FILE_AT_LINE (118)) ;
        var_cas_typedAttributeList.addAssign_operation (var_cas_idx, operand_5744->mAttributeName) ;
      }
    }
    GGS_unifiedTypeMapIndex  var_cas_idx ;
    GGS_unifiedTypeMapIndex::class_method_makeRegularIndex (inLexique, operand_5542->mStructTypeName, var_cas_inSemanticContext.mTypeMap, var_cas_idx COMMA_SOURCE_FILE_AT_LINE (125)) ;
    var_cas_ioSemanticDeclarationListForGeneration.addAssign_operation (GGS_structTypeForGeneration ::constructor_new (inLexique, var_cas_idx, var_cas_typedAttributeList COMMA_SOURCE_FILE_AT_LINE (126))) ;
  }
}

//---------------------------------------------------------------------------*
//                                                                           *
//      Category method '@genericTypeTypeAST.performSemanticAnalysis'        *
//                                                                           *
//---------------------------------------------------------------------------*

static void
category_method__genericTypeTypeAST__performSemanticAnalysis (C_Compiler & inLexique,
                                const cPtr_genericTypeTypeAST * operand_6352,
                                GGS_semanticContext & var_cas_inSemanticContext,
                                GGS_semanticDeclarationListForGeneration  & var_cas_ioSemanticDeclarationListForGeneration
                                COMMA_UNUSED_LOCATION_ARGS) {
  if (operand_6352 != NULL) {
    GGS_unifiedTypeMapIndex  var_cas_idx ;
    GGS_unifiedTypeMapIndex::class_method_makeRegularIndex (inLexique, GGS_lstring ::constructor_new (inLexique, operand_6352->mTypeName, GGS_location (inLexique) COMMA_SOURCE_FILE_AT_LINE (139)), var_cas_inSemanticContext.mTypeMap, var_cas_idx COMMA_SOURCE_FILE_AT_LINE (139)) ;
    var_cas_ioSemanticDeclarationListForGeneration.addAssign_operation (GGS_genericTypeForGeneration ::constructor_new (inLexique, var_cas_idx COMMA_SOURCE_FILE_AT_LINE (140))) ;
  }
}

//---------------------------------------------------------------------------*
//                                                                           *
//      Category method '@classDeclarationAST.performSemanticAnalysis'       *
//                                                                           *
//---------------------------------------------------------------------------*

static void
category_method__classDeclarationAST__performSemanticAnalysis (C_Compiler & inLexique,
                                const cPtr_classDeclarationAST * operand_6860,
                                GGS_semanticContext & var_cas_inSemanticContext,
                                GGS_semanticDeclarationListForGeneration  & var_cas_ioSemanticDeclarationListForGeneration
                                COMMA_UNUSED_LOCATION_ARGS) {
  if (operand_6860 != NULL) {
    GGS_typedAttributeList  var_cas_typedAttributeList = GGS_typedAttributeList ::constructor_emptyList () ;
    {
      GGS_attributeInCollectionListAST::cEnumerator enumerator_7087 (operand_6860->mAttributeList, true) ;
      const GGS_attributeInCollectionListAST::cElement * operand_7087 = NULL ;
      while (((operand_7087 = enumerator_7087.nextObject ()))) {
        macroValidPointer (operand_7087) ;
        GGS_unifiedTypeMapIndex  var_cas_idx ;
        GGS_unifiedTypeMapIndex::class_method_makeRegularIndex (inLexique, operand_7087->mAttributeTypeName, var_cas_inSemanticContext.mTypeMap, var_cas_idx COMMA_SOURCE_FILE_AT_LINE (155)) ;
        var_cas_typedAttributeList.addAssign_operation (var_cas_idx, operand_7087->mAttributeName) ;
      }
    }
    GGS_instanceMethodMap  var_cas_inheritedInstanceMethodMap ;
    const GGS_bool cond_7502 = (operand_6860->mSuperClassName.reader_string (inLexique COMMA_SOURCE_FILE_AT_LINE (163))).operator_isEqual (GGS_string ("")) ;
    if (cond_7502.isBuiltAndTrue ()) {
      var_cas_inheritedInstanceMethodMap = GGS_instanceMethodMap ::constructor_emptyMap (inLexique COMMA_SOURCE_FILE_AT_LINE (164)) ;
    }else if (cond_7502.isBuiltAndFalse ()) {
      GGS_bool automatic_var_7600_0 ;
      GGS_unifiedTypeMapIndex  automatic_var_7600_1 ;
      GGS_typeKindEnum automatic_var_7600_2 ;
      GGS_typedAttributeList  automatic_var_7600_3 ;
      GGS_typedAttributeList  automatic_var_7600_4 ;
      GGS_constructorMap  automatic_var_7600_5 ;
      GGS_readerMap  automatic_var_7600_6 ;
      GGS_modifierMap  automatic_var_7600_7 ;
      GGS_classMethodMap  automatic_var_7600_8 ;
      GGS_enumerationDescriptorList  automatic_var_7600_9 ;
      GGS_uint  automatic_var_7600_10 ;
      GGS_unifiedTypeMapIndexList  automatic_var_7600_11 ;
      GGS_unifiedTypeMapIndexList  automatic_var_7600_12 ;
      GGS_nativeAttributeList  automatic_var_7600_13 ;
      const GGS_unifiedTypeMap  temp_7546 = var_cas_inSemanticContext.reader_mTypeMap (inLexique COMMA_SOURCE_FILE_AT_LINE (166)) ;
      if (temp_7546.isBuilt ()) {
        temp_7546 (HERE)->method_searchKey (inLexique, operand_6860->mSuperClassName, automatic_var_7600_0, automatic_var_7600_1, automatic_var_7600_2, automatic_var_7600_3, automatic_var_7600_4, automatic_var_7600_5, automatic_var_7600_6, automatic_var_7600_7, var_cas_inheritedInstanceMethodMap, automatic_var_7600_8, automatic_var_7600_9, automatic_var_7600_10, automatic_var_7600_11, automatic_var_7600_12, automatic_var_7600_13 COMMA_SOURCE_FILE_AT_LINE (166)) ;
      }
    }
    GGS_unifiedTypeMapIndex  var_cas_superClassIndex ;
    const GGS_bool cond_7845 = (operand_6860->mSuperClassName.reader_string (inLexique COMMA_SOURCE_FILE_AT_LINE (170))).operator_isEqual (GGS_string ("")) ;
    if (cond_7845.isBuiltAndTrue ()) {
      GGS_unifiedTypeMapIndex::class_method_makeRegularIndex (inLexique, GGS_lstring ::constructor_new (inLexique, GGS_string ("class"), GGS_location (inLexique) COMMA_SOURCE_FILE_AT_LINE (171)), var_cas_inSemanticContext.mTypeMap, var_cas_superClassIndex COMMA_SOURCE_FILE_AT_LINE (171)) ;
    }else if (cond_7845.isBuiltAndFalse ()) {
      GGS_unifiedTypeMapIndex::class_method_makeRegularIndex (inLexique, operand_6860->mSuperClassName, var_cas_inSemanticContext.mTypeMap, var_cas_superClassIndex COMMA_SOURCE_FILE_AT_LINE (173)) ;
    }
    GGS_unifiedTypeMapIndex  var_cas_idx ;
    GGS_unifiedTypeMapIndex::class_method_makeRegularIndex (inLexique, operand_6860->mClassTypeName, var_cas_inSemanticContext.mTypeMap, var_cas_idx COMMA_SOURCE_FILE_AT_LINE (177)) ;
    GGS_abstractMethodDefinitionListForGeneration  var_cas_abstractMethodList = GGS_abstractMethodDefinitionListForGeneration ::constructor_emptyList () ;
    {
      GGS_abstractMethodDefinitionListAST::cEnumerator enumerator_8241 (operand_6860->mAbstractMethodList, true) ;
      const GGS_abstractMethodDefinitionListAST::cElement * operand_8241 = NULL ;
      while (((operand_8241 = enumerator_8241.nextObject ()))) {
        macroValidPointer (operand_8241) ;
        const GGS_bool cond_8427 = (operand_6860->mIsAbstract).operator_not () ;
        if (cond_8427.isBuiltAndTrue ()) {
          operand_8241->mMethodName.reader_location (inLexique COMMA_HERE).signalGGSSemanticError (inLexique, GGS_string ("a concrete class cannot declare an abstract method") COMMA_SOURCE_FILE_AT_LINE (184)) ;
        }
        GGS_formalParameterListForGeneration  var_cas_formalParameterListForGeneration = GGS_formalParameterListForGeneration ::constructor_emptyList () ;
        {
          GGS_formalParameterListAST::cEnumerator enumerator_8572 (operand_8241->mSignature, true) ;
          const GGS_formalParameterListAST::cElement * operand_8572 = NULL ;
          while (((operand_8572 = enumerator_8572.nextObject ()))) {
            macroValidPointer (operand_8572) ;
            var_cas_formalParameterListForGeneration.addAssign_operation (operand_8572->mFormalParameterPassingMode, GGS_unifiedTypeMapIndex ::constructor_searchKey (inLexique, var_cas_inSemanticContext.reader_mTypeMap (inLexique COMMA_SOURCE_FILE_AT_LINE (190)), operand_8572->mFormalParameterTypeName COMMA_SOURCE_FILE_AT_LINE (190)), operand_8572->mFormalParameterName, operand_8572->mIsUnused) ;
          }
        }
        const GGS_bool cond_9292 = operand_8241->mIsOverriding ;
        if (cond_9292.isBuiltAndTrue ()) {
          GGS_formalParameterSignature  var_cas_inheritedSignature ;
          GGS_location  var_cas_inheritedDeclarationLocation ;
          GGS_bool automatic_var_9104_0 ;
          const GGS_instanceMethodMap  temp_9037 = var_cas_inheritedInstanceMethodMap ;
          if (temp_9037.isBuilt ()) {
            temp_9037 (HERE)->method_searchInheritedKey (inLexique, operand_8241->mMethodName, var_cas_inheritedSignature, var_cas_inheritedDeclarationLocation, automatic_var_9104_0 COMMA_SOURCE_FILE_AT_LINE (199)) ;
          }
          ::routine_checkMethodSignatures (inLexique,  var_cas_formalParameterListForGeneration,  operand_8241->mMethodName.reader_location (inLexique COMMA_SOURCE_FILE_AT_LINE (202)),  var_cas_inheritedSignature,  var_cas_inheritedDeclarationLocation COMMA_SOURCE_FILE_AT_LINE (200)) ;
        }else if (cond_9292.isBuiltAndFalse ()) {
          const GGS_bool cond_9475 = var_cas_inheritedInstanceMethodMap.reader_hasKey (operand_8241->mMethodName.reader_string (inLexique COMMA_SOURCE_FILE_AT_LINE (206))) ;
          if (cond_9475.isBuiltAndTrue ()) {
            operand_8241->mMethodName.reader_location (inLexique COMMA_HERE).signalGGSSemanticError (inLexique, GGS_string ("this method cannot be declared as abstract, it is already declared in super class") COMMA_SOURCE_FILE_AT_LINE (208)) ;
          }
        }
        var_cas_abstractMethodList.addAssign_operation (operand_8241->mIsOverriding, operand_8241->mMethodName, var_cas_formalParameterListForGeneration) ;
      }
    }
    GGS_methodDefinitionListForGeneration  var_cas_methodList = GGS_methodDefinitionListForGeneration ::constructor_emptyList () ;
    {
      GGS_methodDefinitionListAST::cEnumerator enumerator_9691 (operand_6860->mMethodList, true) ;
      const GGS_methodDefinitionListAST::cElement * operand_9691 = NULL ;
      while (((operand_9691 = enumerator_9691.nextObject ()))) {
        macroValidPointer (operand_9691) ;
        GGS_formalParameterListForGeneration  var_cas_formalParameterListForGeneration = GGS_formalParameterListForGeneration ::constructor_emptyList () ;
        {
          GGS_formalParameterListAST::cEnumerator enumerator_9834 (operand_9691->mSignature, true) ;
          const GGS_formalParameterListAST::cElement * operand_9834 = NULL ;
          while (((operand_9834 = enumerator_9834.nextObject ()))) {
            macroValidPointer (operand_9834) ;
            var_cas_formalParameterListForGeneration.addAssign_operation (operand_9834->mFormalParameterPassingMode, GGS_unifiedTypeMapIndex ::constructor_searchKey (inLexique, var_cas_inSemanticContext.reader_mTypeMap (inLexique COMMA_SOURCE_FILE_AT_LINE (219)), operand_9834->mFormalParameterTypeName COMMA_SOURCE_FILE_AT_LINE (219)), operand_9834->mFormalParameterName, operand_9834->mIsUnused) ;
          }
        }
        const GGS_bool cond_10554 = operand_9691->mIsOverriding ;
        if (cond_10554.isBuiltAndTrue ()) {
          GGS_formalParameterSignature  var_cas_inheritedSignature ;
          GGS_location  var_cas_inheritedDeclarationLocation ;
          GGS_bool automatic_var_10366_0 ;
          const GGS_instanceMethodMap  temp_10299 = var_cas_inheritedInstanceMethodMap ;
          if (temp_10299.isBuilt ()) {
            temp_10299 (HERE)->method_searchInheritedKey (inLexique, operand_9691->mMethodName, var_cas_inheritedSignature, var_cas_inheritedDeclarationLocation, automatic_var_10366_0 COMMA_SOURCE_FILE_AT_LINE (228)) ;
          }
          ::routine_checkMethodSignatures (inLexique,  var_cas_formalParameterListForGeneration,  operand_9691->mMethodName.reader_location (inLexique COMMA_SOURCE_FILE_AT_LINE (231)),  var_cas_inheritedSignature,  var_cas_inheritedDeclarationLocation COMMA_SOURCE_FILE_AT_LINE (229)) ;
        }else if (cond_10554.isBuiltAndFalse ()) {
          const GGS_bool cond_10737 = var_cas_inheritedInstanceMethodMap.reader_hasKey (operand_9691->mMethodName.reader_string (inLexique COMMA_SOURCE_FILE_AT_LINE (235))) ;
          if (cond_10737.isBuiltAndTrue ()) {
            operand_9691->mMethodName.reader_location (inLexique COMMA_HERE).signalGGSSemanticError (inLexique, GGS_string ("this method cannot be declared as abstract, it is already declared in super class") COMMA_SOURCE_FILE_AT_LINE (237)) ;
          }
        }
        var_cas_methodList.addAssign_operation (operand_9691->mIsOverriding, operand_9691->mMethodName, var_cas_formalParameterListForGeneration, GGS_semanticInstructionListForGeneration ::constructor_emptyList ()) ;
      }
    }
    var_cas_ioSemanticDeclarationListForGeneration.addAssign_operation (GGS_classDeclarationForGeneration ::constructor_new (inLexique, var_cas_idx, operand_6860->mIsAbstract, operand_6860->mClassTypeName, var_cas_superClassIndex, var_cas_typedAttributeList, var_cas_abstractMethodList, var_cas_methodList COMMA_SOURCE_FILE_AT_LINE (246))) ;
  }
}

//---------------------------------------------------------------------------*
//                                                                           *
//           Implementation of routine "performSemanticAnalysis"             *
//                                                                           *
//---------------------------------------------------------------------------*

void routine_performSemanticAnalysis (C_Compiler & inLexique,
                                const GGS_semanticDeclarationListAST   var_cas_inDeclarationList,
                                GGS_semanticContext & var_cas_inSemanticContext,
                                GGS_semanticDeclarationListForGeneration  & var_cas_outDecoratedDeclarationListForGeneration COMMA_UNUSED_LOCATION_ARGS) {
  #ifdef DEBUG_TRACE_ENABLED
    printf ("ENTER routine_performSemanticAnalysis at %s:%d\n", __FILE__, __LINE__) ;
  #endif
  var_cas_outDecoratedDeclarationListForGeneration = GGS_semanticDeclarationListForGeneration ::constructor_emptyList () ;
  {
    GGS_semanticDeclarationListAST::cEnumerator enumerator_11884 (var_cas_inDeclarationList, true) ;
    const GGS_semanticDeclarationListAST::cElement * operand_11884 = NULL ;
    while (((operand_11884 = enumerator_11884.nextObject ()))) {
      macroValidPointer (operand_11884) ;
      const GGS_semanticDeclarationAST  temp_11937 = operand_11884->mSemanticDeclaration ;
      if (temp_11937.isBuilt ()) {
        typeCategoryMethod__semanticDeclarationAST__performSemanticAnalysis method = findCategoryMethod__semanticDeclarationAST__performSemanticAnalysis (temp_11937.galgasObjectRunTimeInfo ()) ;
        if (method != NULL) {
          method (inLexique, temp_11937 (HERE), var_cas_inSemanticContext, var_cas_outDecoratedDeclarationListForGeneration COMMA_SOURCE_FILE_AT_LINE (271)) ;
        }
      }
    }
  }
  #ifdef DEBUG_TRACE_ENABLED
    printf ("LEAVE routine_performSemanticAnalysis\n") ;
  #endif
}

//---------------------------------------------------------------------------*
//                                                                           *
//                      Prologue and epilogue actions                        *
//                                                                           *
//---------------------------------------------------------------------------*

static void prologueRoutineFor_semanticAnalysis (void) {
  enterCategoryMethod__semanticDeclarationAST__performSemanticAnalysis (category_method__semanticDeclarationAST__performSemanticAnalysis, gClassInfoFor__semanticDeclarationAST.slotID ()) ;
  enterCategoryMethod__semanticDeclarationAST__performSemanticAnalysis ((typeCategoryMethod__semanticDeclarationAST__performSemanticAnalysis) category_method__predefinedTypeAST__performSemanticAnalysis, gClassInfoFor__predefinedTypeAST.slotID ()) ;
  enterCategoryMethod__semanticDeclarationAST__performSemanticAnalysis ((typeCategoryMethod__semanticDeclarationAST__performSemanticAnalysis) category_method__listDeclarationAST__performSemanticAnalysis, gClassInfoFor__listDeclarationAST.slotID ()) ;
  enterCategoryMethod__semanticDeclarationAST__performSemanticAnalysis ((typeCategoryMethod__semanticDeclarationAST__performSemanticAnalysis) category_method__structDeclarationAST__performSemanticAnalysis, gClassInfoFor__structDeclarationAST.slotID ()) ;
  enterCategoryMethod__semanticDeclarationAST__performSemanticAnalysis ((typeCategoryMethod__semanticDeclarationAST__performSemanticAnalysis) category_method__genericTypeTypeAST__performSemanticAnalysis, gClassInfoFor__genericTypeTypeAST.slotID ()) ;
  enterCategoryMethod__semanticDeclarationAST__performSemanticAnalysis ((typeCategoryMethod__semanticDeclarationAST__performSemanticAnalysis) category_method__classDeclarationAST__performSemanticAnalysis, gClassInfoFor__classDeclarationAST.slotID ()) ;
}

//---------------------------------------------------------------------------*

static void epilogueRoutineFor_semanticAnalysis (void) {
  gDispatchTableForMethod__semanticDeclarationAST__performSemanticAnalysis.free () ;
}

//---------------------------------------------------------------------------*

C_PrologueEpilogue prologueEpilogueObjectFor_semanticAnalysis (prologueRoutineFor_semanticAnalysis, epilogueRoutineFor_semanticAnalysis) ;

//---------------------------------------------------------------------------*

