//---------------------------------------------------------------------------*
//                                                                           *
//                        File 'semantics_parser.h'                          *
//         Generated by version GALGAS_BETA_VERSION (LL(1) grammar)          *
//                    february 15th, 2007, at 18h52'22"                      *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

#ifndef semantics_parser_DEFINED
#define semantics_parser_DEFINED

#include <string.h>

//---------------------------------------------------------------------------*

#include "galgas/C_GGS_Object.h"
#include "galgas/GGS_location.h"
#include "galgas/GGS_lbool.h"
#include "galgas/GGS_lchar.h"
#include "galgas/GGS_lstring.h"
#include "galgas/GGS_ldouble.h"
#include "galgas/GGS_luint.h"
#include "galgas/GGS_lsint.h"
#include "galgas/GGS_luint64.h"
#include "galgas/GGS_lsint64.h"
#include "galgas/GGS_stringset.h"
#include "galgas/GGS_binaryset.h"
#include "galgas/predefined_types.h"
#include "galgas/AC_galgas_domain.h"
#include "galgas/AC_galgas_map.h"
#include "galgas/AC_galgas_list.h"
#include "galgas/AC_galgas_sortedlist.h"

//---------------------------------------------------------------------------*

#include "galgas_scanner.h"

// Include imported semantics
#include "semantics_semantics.h"

//--- START OF USER ZONE 2


//--- END OF USER ZONE 2

//---------------------------------------------------------------------------*
//                                                                           *
//                          Class Predeclarations                            *
//                                                                           *
//---------------------------------------------------------------------------*


void routine_buildFileNameWithPath (C_Lexique &,
                                GGS_lstring  &,
                                GGS_lstring  ,
                                const GGS_lstring  &,
                                const GGS_lstring  & COMMA_LOCATION_ARGS) ;

//---------------------------------------------------------------------------*
//                                                                           *
//                Parser class semantics_parser declaration                  *
//                                                                           *
//---------------------------------------------------------------------------*

class semantics_parser {
  public : virtual ~semantics_parser (void) {}

  protected : virtual void nt_galgas_component_ (galgas_scanner &,
                                GGS_M_lexiqueComponents  &,
                                GGS_M_semanticsComponents  &,
                                GGS_M_syntaxComponents  &,
                                GGS_M_grammarComponents  &,
                                GGS_M_optionComponents  &,
                                GGS_M_metamodelsComponents  &,
                                GGS_M_constraintComponents  &) = 0 ;

  protected : virtual void nt_galgas_component_importLexique (galgas_scanner &,
                                GGS_M_lexiqueComponents  &) = 0 ;

  protected : virtual void nt_galgas_component_importSyntax (galgas_scanner &,
                                GGS_M_syntaxComponents  &,
                                GGS_M_metamodelsComponents  &) = 0 ;

  protected : virtual void nt_galgas_component_importSemantics (galgas_scanner &,
                                GGS_M_semanticsComponents  &,
                                GGS_M_metamodelsComponents  &,
                                GGS_M_constraintComponents  &) = 0 ;

  protected : virtual void nt_galgas_component_importGrammarForSemantics (galgas_scanner &,
                                GGS_M_grammarComponents  &,
                                GGS_M_metamodelsComponents  &,
                                GGS_M_constraintComponents  &) = 0 ;

  protected : virtual void nt_galgas_component_importOptions (galgas_scanner &,
                                GGS_M_optionComponents  &) = 0 ;

  protected : virtual void nt_parse_semantics_component_for_importing_ (galgas_scanner &,
                                const GGS_lstring  &,
                                GGS_M_semanticsComponents  &,
                                GGS_M_metamodelsComponents  &,
                                GGS_M_constraintComponents  &) = 0 ;

  protected : virtual void nt_parse_semantics_component_for_importing_parse (galgas_scanner &) = 0 ;

  protected : virtual void nt_parse_grammar_component_for_importing_ (galgas_scanner &,
                                const GGS_lstring  &,
                                GGS_M_grammarComponents  &,
                                GGS_M_metamodelsComponents  &,
                                GGS_M_constraintComponents  &) = 0 ;

  protected : virtual void nt_parse_grammar_component_for_importing_parse (galgas_scanner &) = 0 ;

  protected : virtual void nt_parse_option_component_for_importing_ (galgas_scanner &,
                                const GGS_lstring  &,
                                GGS_M_optionComponents  &) = 0 ;

  protected : virtual void nt_parse_option_component_for_importing_parse (galgas_scanner &) = 0 ;

  protected : virtual void nt_semantics_declaration_ (galgas_scanner &,
                                GGS_M_semanticsEntitiesForUse  &,
                                GGS_typeEntitiesToGenerateList  &,
                                const GGS_M_optionComponents  &,
                                GGS_typeTableNomRoutinesDeclarees  &,
                                GGS_typeTableEnAvant  &,
                                GGS_typeTableRoutinesAimplementer  &) = 0 ;

  protected : virtual void nt_semantics_declaration_importSemantics (galgas_scanner &,
                                GGS_ModelMap  &,
                                GGS_ActionMap  &,
                                GGS_M_semanticsEntitiesForUse  &,
                                GGS_typeTableNomRoutinesDeclarees  &,
                                GGS_typeTableEnAvant  &,
                                GGS_typeTableRoutinesAimplementer  &) = 0 ;

  protected : virtual void nt_semantics_declaration_parse (galgas_scanner &) = 0 ;

  protected : virtual void nt_import_headers_semantics_and_grammars_ (galgas_scanner &,
                                GGS_stringset  &,
                                GGS_stringset  &,
                                GGS_stringset  &,
                                GGS_stringset  &,
                                GGS_M_semanticsComponents  &,
                                GGS_M_metamodelsComponents  &,
                                GGS_M_constraintComponents  &,
                                GGS_M_grammarComponents  &,
                                GGS_M_optionComponents  &,
                                GGS_stringset  &,
                                GGS_stringset  &,
                                GGS_M_optionComponents  &,
                                GGS_ModelMap  &,
                                GGS_ActionMap  &,
                                GGS_M_semanticsEntitiesForUse  &,
                                GGS_typeTableEnAvant  &,
                                GGS_entityToImplementMap  &) = 0 ;

  protected : virtual void nt_import_headers_semantics_and_grammars_importSemantics (galgas_scanner &,
                                GGS_M_semanticsComponents  &,
                                GGS_stringset  &,
                                GGS_stringset  &,
                                GGS_ModelMap  &,
                                GGS_ActionMap  &,
                                GGS_M_semanticsEntitiesForUse  &,
                                GGS_M_metamodelsComponents  &,
                                GGS_M_constraintComponents  &) = 0 ;

  protected : virtual void nt_import_headers_semantics_and_grammars_parse (galgas_scanner &) = 0 ;

  protected : virtual void nt_parent_class_ (galgas_scanner &,
                                GGS_M_semanticsEntitiesForUse  &,
                                GGS_typeSemanticAttributesMap  &,
                                GGS_typeListeAttributsSemantiques  &,
                                GGS_typeTableMethodes  &,
                                GGS_typeSuperClassesMap  &,
                                GGS_typeClassInheritedMessagesMap  &,
                                GGS_lstring  &) = 0 ;

  protected : virtual void nt_parent_class_importSemantics (galgas_scanner &,
                                GGS_ModelMap  &,
                                GGS_stringset  &,
                                GGS_typeListModel  &,
                                GGS_classMessageMap  &,
                                GGS_M_semanticsEntitiesForUse  &,
                                GGS_typeSemanticAttributesMap  &,
                                GGS_typeListeAttributsSemantiques  &,
                                GGS_typeTableMethodes  &,
                                GGS_typeSuperClassesMap  &,
                                GGS_typeClassInheritedMessagesMap  &) = 0 ;

  protected : virtual void nt_parent_class_parse (galgas_scanner &) = 0 ;

  protected : virtual void nt_attributes_definition_list_ (galgas_scanner &,
                                GGS_typeListModel  &,
                                GGS_typeSemanticAttributesMap  &,
                                GGS_typeListeAttributsSemantiques  &,
                                GGS_typeListeAttributsSemantiques  &,
                                GGS_L_nameWithType  &,
                                GGS_M_semanticsEntitiesForUse  &) = 0 ;

  protected : virtual void nt_attributes_definition_list_parse (galgas_scanner &) = 0 ;

  protected : virtual void nt_type_parsing_ (galgas_scanner &,
                                GGS_M_semanticsEntitiesForUse  &,
                                GGS_AC_galgasType  &,
                                GGS_lstring  &) = 0 ;

  protected : virtual void nt_type_parsing_parse (galgas_scanner &) = 0 ;

  protected : virtual void nt_parse_method_ (galgas_scanner &,
                                const GGS_lstring  &,
                                const GGS_typeTableMethodes  &,
                                const GGS_typeListeAttributsSemantiques  &,
                                const GGS_typeTableMethodes  &,
                                const GGS_typeSuperClassesMap  &,
                                const GGS_typeClassInheritedMessagesMap  &,
                                const GGS_typeSemanticAttributesMap  &,
                                const GGS_bool &,
                                GGS_typeEntitiesToGenerateList  &,
                                GGS_M_semanticsEntitiesForUse  &,
                                GGS_typeTableEnAvant  &,
                                GGS_lstring  &,
                                GGS_typeInstructionList  &,
                                GGS_L_EXsignature  &,
                                GGS_typeListeTypesEtNomsArgMethode  &,
                                const GGS_M_optionComponents  &) = 0 ;

  protected : virtual void nt_parse_method_parse (galgas_scanner &) = 0 ;

  protected : virtual void nt_overrided_method_ (galgas_scanner &,
                                const GGS_lstring  &,
                                const GGS_typeTableMethodes  &,
                                const GGS_typeListeAttributsSemantiques  &,
                                GGS_typeTableMethodes  &,
                                const GGS_typeSuperClassesMap  &,
                                const GGS_typeClassInheritedMessagesMap  &,
                                const GGS_typeSemanticAttributesMap  &,
                                const GGS_bool &,
                                GGS_typeEntitiesToGenerateList  &,
                                GGS_M_semanticsEntitiesForUse  &,
                                GGS_typeTableMethodesAimplementer  &,
                                GGS_typeTableEnAvant  &,
                                const GGS_M_optionComponents  &) = 0 ;

  protected : virtual void nt_overrided_method_parse (galgas_scanner &) = 0 ;

  protected : virtual void nt_non_abstract_method_ (galgas_scanner &,
                                const GGS_lstring  &,
                                const GGS_typeTableMethodes  &,
                                const GGS_typeListeAttributsSemantiques  &,
                                GGS_typeTableMethodes  &,
                                const GGS_typeSuperClassesMap  &,
                                const GGS_typeClassInheritedMessagesMap  &,
                                const GGS_typeSemanticAttributesMap  &,
                                const GGS_bool &,
                                GGS_typeEntitiesToGenerateList  &,
                                GGS_M_semanticsEntitiesForUse  &,
                                GGS_typeTableMethodesAimplementer  &,
                                GGS_typeTableEnAvant  &,
                                const GGS_M_optionComponents  &) = 0 ;

  protected : virtual void nt_non_abstract_method_parse (galgas_scanner &) = 0 ;

  protected : virtual void nt_abstract_method_ (galgas_scanner &,
                                const GGS_bool &,
                                GGS_typeListeAttributsSemantiques  &,
                                GGS_typeEntitiesToGenerateList  &,
                                GGS_M_semanticsEntitiesForUse  &,
                                GGS_typeTableMethodes  &,
                                GGS_typeTableMethodesAimplementer  &,
                                GGS_typeTableEnAvant  &) = 0 ;

  protected : virtual void nt_abstract_method_parse (galgas_scanner &) = 0 ;

  protected : virtual void nt_semantic_instructions_list_ (galgas_scanner &,
                                GGS_M_semanticsEntitiesForUse  &,
                                GGS_typeEntitiesToGenerateList  &,
                                const GGS_M_optionComponents  &,
                                GGS_typeVariablesMap  &,
                                GGS_typeInstructionList  &,
                                GGS_entityPropertyMap  &,
                                GGS_stringset  &,
                                GGS_callInstructionSharedPropertySignatureMap  &) = 0 ;

  protected : virtual void nt_semantic_instructions_list_parse (galgas_scanner &) = 0 ;

  protected : virtual void nt_semantic_instructions_list_no_verif_ (galgas_scanner &,
                                GGS_M_semanticsEntitiesForUse  &,
                                GGS_typeEntitiesToGenerateList  &,
                                const GGS_M_optionComponents  &,
                                GGS_typeVariablesMap  &,
                                GGS_typeInstructionList  &,
                                GGS_entityPropertyMap  &,
                                GGS_stringset  &,
                                GGS_callInstructionSharedPropertySignatureMap  &) = 0 ;

  protected : virtual void nt_semantic_instructions_list_no_verif_parse (galgas_scanner &) = 0 ;

  protected : virtual void nt_semantic_instruction_ (galgas_scanner &,
                                GGS_M_semanticsEntitiesForUse  &,
                                GGS_typeEntitiesToGenerateList  &,
                                const GGS_M_optionComponents  &,
                                GGS_typeVariablesMap  &,
                                GGS_typeInstructionList  &,
                                GGS_entityPropertyMap  &,
                                GGS_stringset  &,
                                GGS_callInstructionSharedPropertySignatureMap  &) = 0 ;

  protected : virtual void nt_semantic_instruction_parse (galgas_scanner &) = 0 ;

  protected : virtual void nt_extract_instruction_ (galgas_scanner &,
                                GGS_M_semanticsEntitiesForUse  &,
                                GGS_typeEntitiesToGenerateList  &,
                                const GGS_M_optionComponents  &,
                                GGS_typeVariablesMap  &,
                                GGS_typeCplusPlusName  ,
                                GGS_lstring  ,
                                GGS_typeClassInheritedMessagesMap  ,
                                GGS_typeInstruction  &,
                                GGS_entityPropertyMap  &,
                                GGS_stringset  &,
                                GGS_callInstructionSharedPropertySignatureMap  &) = 0 ;

  protected : virtual void nt_extract_instruction_parse (galgas_scanner &) = 0 ;

  protected : virtual void nt_expression_ (galgas_scanner &,
                                GGS_M_semanticsEntitiesForUse  &,
                                const GGS_M_optionComponents  &,
                                GGS_typeVariablesMap  &,
                                GGS_typeExpression  &,
                                GGS_AC_galgasType  &) = 0 ;

  protected : virtual void nt_expression_parse (galgas_scanner &) = 0 ;

  protected : virtual void nt_input_parameters_list_ (galgas_scanner &,
                                GGS_L_assignedVariables  &,
                                GGS_typeCplusPlusNameList  &,
                                GGS_typeListeAttributsSemantiques  ,
                                GGS_typeVariablesMap  &) = 0 ;

  protected : virtual void nt_input_parameters_list_parse (galgas_scanner &) = 0 ;

  protected : virtual void nt_actual_parameters_list_ (galgas_scanner &,
                                const GGS_L_EXsignature  &,
                                GGS_typeExpressionList  &,
                                GGS_typeVariablesMap  &,
                                const GGS_M_optionComponents  &,
                                GGS_M_semanticsEntitiesForUse  &,
                                GGS_typeInstructionList  &) = 0 ;

  protected : virtual void nt_actual_parameters_list_parse (galgas_scanner &) = 0 ;

  protected : virtual void nt_parse_parameters_list_ (galgas_scanner &,
                                GGS_L_actualParametersSignature  &,
                                GGS_typeExpressionList  &,
                                GGS_typeVariablesMap  &,
                                const GGS_M_optionComponents  &,
                                GGS_M_semanticsEntitiesForUse  &) = 0 ;

  protected : virtual void nt_parse_parameters_list_parse (galgas_scanner &) = 0 ;

  protected : virtual void nt_read_access_ (galgas_scanner &,
                                GGS_lstring  &,
                                GGS_typeCplusPlusName  &,
                                GGS_AC_galgasType  &,
                                GGS_typeVariablesMap  &) = 0 ;

  protected : virtual void nt_read_access_parse (galgas_scanner &) = 0 ;

  protected : virtual void nt_instruction_beginning_with_identifier_ (galgas_scanner &,
                                GGS_lstring  ,
                                GGS_typeVariablesMap  &,
                                GGS_typeInstructionList  &,
                                const GGS_M_optionComponents  &,
                                GGS_M_semanticsEntitiesForUse  &) = 0 ;

  protected : virtual void nt_instruction_beginning_with_identifier_parse (galgas_scanner &) = 0 ;

  protected : virtual void nt_optional_assignment_ (galgas_scanner &,
                                const GGS_lstring  &,
                                const GGS_lstring  &,
                                const GGS_typeCplusPlusName  &,
                                const GGS_AC_galgasType  &,
                                GGS_typeVariablesMap  &,
                                GGS_typeInstructionList  &,
                                const GGS_M_optionComponents  &,
                                GGS_M_semanticsEntitiesForUse  &) = 0 ;

  protected : virtual void nt_optional_assignment_parse (galgas_scanner &) = 0 ;

  protected : virtual void nt_ex_map_method_ (galgas_scanner &,
                                GGS_lstring  &,
                                GGS_lstring  &) = 0 ;

  protected : virtual void nt_ex_map_method_parse (galgas_scanner &) = 0 ;

  protected : virtual void nt_map_method_ (galgas_scanner &,
                                GGS_lstring  &,
                                GGS_lstring  &,
                                GGS_lstring  &) = 0 ;

  protected : virtual void nt_map_method_parse (galgas_scanner &) = 0 ;

  protected : virtual void nt_formal_arguments_list_ (galgas_scanner &,
                                GGS_M_semanticsEntitiesForUse  &,
                                GGS_L_EXsignature  &,
                                GGS_typeVariablesMap  &,
                                GGS_typeListeTypesEtNomsArgMethode  &,
                                GGS_typeTableEnAvant  &,
                                GGS_L_signature  &) = 0 ;

  protected : virtual void nt_formal_arguments_list_importGrammarForSemantics (galgas_scanner &,
                                GGS_L_signature  &) = 0 ;

  protected : virtual void nt_formal_arguments_list_parse (galgas_scanner &) = 0 ;

  protected : virtual void nt_output_expression_list_ (galgas_scanner &,
                                GGS_typeExpressionList  &,
                                const GGS_typeListeAttributsSemantiques  &,
                                GGS_M_semanticsEntitiesForUse  &,
                                const GGS_M_optionComponents  &,
                                GGS_typeVariablesMap  &) = 0 ;

  protected : virtual void nt_output_expression_list_parse (galgas_scanner &) = 0 ;

  protected : virtual void nt_formal_argument_type_ (galgas_scanner &,
                                GGS_M_semanticsEntitiesForUse  &,
                                GGS_AC_galgasType  &,
                                GGS_typeTableEnAvant  &,
                                GGS_lstring  &) = 0 ;

  protected : virtual void nt_formal_argument_type_importGrammarForSemantics (galgas_scanner &,
                                GGS_lstring  &) = 0 ;

  protected : virtual void nt_formal_argument_type_parse (galgas_scanner &) = 0 ;

  protected : virtual void nt_parse_match_operand_ (galgas_scanner &,
                                GGS_typeVariablesMap  &,
                                GGS_typeCplusPlusName  &,
                                GGS_lstring  &,
                                GGS_location  &,
                                GGS_bool &,
                                GGS_enumConstantMap  &) = 0 ;

  protected : virtual void nt_parse_match_operand_parse (galgas_scanner &) = 0 ;

  protected : virtual void nt_parse_match_case_ (galgas_scanner &,
                                GGS_M_semanticsEntitiesForUse  &,
                                GGS_typeVariablesMap  &,
                                GGS_lstring  ,
                                GGS_location  ,
                                GGS_bool ,
                                GGS_enumConstantMap  ,
                                GGS_lstring  &) = 0 ;

  protected : virtual void nt_parse_match_case_parse (galgas_scanner &) = 0 ;

  protected : virtual void nt_parse_effective_input_parameters_list_ (galgas_scanner &,
                                GGS_typeVariablesMap  &,
                                GGS_typeListeAttributsSemantiques  ,
                                GGS_location  ,
                                GGS_localConstantBuildStyleEnum ,
                                GGS_bool &) = 0 ;

  protected : virtual void nt_parse_effective_input_parameters_list_parse (galgas_scanner &) = 0 ;

  protected : void pr_galgas_component_semantics_parser_433_6_ (galgas_scanner &,
                                GGS_M_lexiqueComponents  &,
                                GGS_M_semanticsComponents  &,
                                GGS_M_syntaxComponents  &,
                                GGS_M_grammarComponents  &,
                                GGS_M_optionComponents  &,
                                GGS_M_metamodelsComponents  &,
                                GGS_M_constraintComponents  &) ;

  protected : virtual sint16 select_repeat_semantics_parser_0 (galgas_scanner &) = 0 ;

  protected : void pr_galgas_component_semantics_parser_433_6_importSyntax (galgas_scanner &,
                                GGS_M_syntaxComponents  &,
                                GGS_M_metamodelsComponents  &) ;

  protected : void pr_galgas_component_semantics_parser_433_6_importSemantics (galgas_scanner &,
                                GGS_M_semanticsComponents  &,
                                GGS_M_metamodelsComponents  &,
                                GGS_M_constraintComponents  &) ;

  protected : void pr_galgas_component_semantics_parser_433_6_importLexique (galgas_scanner &,
                                GGS_M_lexiqueComponents  &) ;

  protected : void pr_galgas_component_semantics_parser_433_6_importGrammarForSemantics (galgas_scanner &,
                                GGS_M_grammarComponents  &,
                                GGS_M_metamodelsComponents  &,
                                GGS_M_constraintComponents  &) ;

  protected : void pr_galgas_component_semantics_parser_433_6_importOptions (galgas_scanner &,
                                GGS_M_optionComponents  &) ;

  protected : void pr_import_headers_semantics_and_grammars_semantics_parser_677_6_ (galgas_scanner &,
                                GGS_stringset  &,
                                GGS_stringset  &,
                                GGS_stringset  &,
                                GGS_stringset  &,
                                GGS_M_semanticsComponents  &,
                                GGS_M_metamodelsComponents  &,
                                GGS_M_constraintComponents  &,
                                GGS_M_grammarComponents  &,
                                GGS_M_optionComponents  &,
                                GGS_stringset  &,
                                GGS_stringset  &,
                                GGS_M_optionComponents  &,
                                GGS_ModelMap  &,
                                GGS_ActionMap  &,
                                GGS_M_semanticsEntitiesForUse  &,
                                GGS_typeTableEnAvant  &,
                                GGS_entityToImplementMap  &) ;

  protected : virtual sint16 select_repeat_semantics_parser_1 (galgas_scanner &) = 0 ;

  protected : virtual sint16 select_semantics_parser_2 (galgas_scanner &) = 0 ;

  protected : virtual sint16 select_semantics_parser_3 (galgas_scanner &) = 0 ;

  protected : virtual sint16 select_semantics_parser_4 (galgas_scanner &) = 0 ;

  protected : virtual sint16 select_semantics_parser_5 (galgas_scanner &) = 0 ;

  protected : virtual sint16 select_semantics_parser_6 (galgas_scanner &) = 0 ;

  protected : void pr_import_headers_semantics_and_grammars_semantics_parser_677_6_importSemantics (galgas_scanner &,
                                GGS_M_semanticsComponents  &,
                                GGS_stringset  &,
                                GGS_stringset  &,
                                GGS_ModelMap  &,
                                GGS_ActionMap  &,
                                GGS_M_semanticsEntitiesForUse  &,
                                GGS_M_metamodelsComponents  &,
                                GGS_M_constraintComponents  &) ;

  protected : void pr_import_headers_semantics_and_grammars_semantics_parser_677_6_parse (galgas_scanner & _inLexique) ;

  protected : void pr_semantics_declaration_semantics_parser_1014_6_ (galgas_scanner &,
                                GGS_M_semanticsEntitiesForUse  &,
                                GGS_typeEntitiesToGenerateList  &,
                                const GGS_M_optionComponents  &,
                                GGS_typeTableNomRoutinesDeclarees  &,
                                GGS_typeTableEnAvant  &,
                                GGS_typeTableRoutinesAimplementer  &) ;

  protected : virtual sint16 select_semantics_parser_7 (galgas_scanner &) = 0 ;

  protected : void pr_semantics_declaration_semantics_parser_1014_6_importSemantics (galgas_scanner &,
                                GGS_ModelMap  &,
                                GGS_ActionMap  &,
                                GGS_M_semanticsEntitiesForUse  &,
                                GGS_typeTableNomRoutinesDeclarees  &,
                                GGS_typeTableEnAvant  &,
                                GGS_typeTableRoutinesAimplementer  &) ;

  protected : void pr_semantics_declaration_semantics_parser_1014_6_parse (galgas_scanner & _inLexique) ;

  protected : void pr_parent_class_semantics_parser_1149_6_ (galgas_scanner &,
                                GGS_M_semanticsEntitiesForUse  &,
                                GGS_typeSemanticAttributesMap  &,
                                GGS_typeListeAttributsSemantiques  &,
                                GGS_typeTableMethodes  &,
                                GGS_typeSuperClassesMap  &,
                                GGS_typeClassInheritedMessagesMap  &,
                                GGS_lstring  &) ;

  protected : void pr_parent_class_semantics_parser_1149_6_importSemantics (galgas_scanner &,
                                GGS_ModelMap  &,
                                GGS_stringset  &,
                                GGS_typeListModel  &,
                                GGS_classMessageMap  &,
                                GGS_M_semanticsEntitiesForUse  &,
                                GGS_typeSemanticAttributesMap  &,
                                GGS_typeListeAttributsSemantiques  &,
                                GGS_typeTableMethodes  &,
                                GGS_typeSuperClassesMap  &,
                                GGS_typeClassInheritedMessagesMap  &) ;

  protected : void pr_parent_class_semantics_parser_1149_6_parse (galgas_scanner & _inLexique) ;

  protected : void pr_parent_class_semantics_parser_1189_6_ (galgas_scanner &,
                                GGS_M_semanticsEntitiesForUse  &,
                                GGS_typeSemanticAttributesMap  &,
                                GGS_typeListeAttributsSemantiques  &,
                                GGS_typeTableMethodes  &,
                                GGS_typeSuperClassesMap  &,
                                GGS_typeClassInheritedMessagesMap  &,
                                GGS_lstring  &) ;

  protected : void pr_parent_class_semantics_parser_1189_6_importSemantics (galgas_scanner &,
                                GGS_ModelMap  &,
                                GGS_stringset  &,
                                GGS_typeListModel  &,
                                GGS_classMessageMap  &,
                                GGS_M_semanticsEntitiesForUse  &,
                                GGS_typeSemanticAttributesMap  &,
                                GGS_typeListeAttributsSemantiques  &,
                                GGS_typeTableMethodes  &,
                                GGS_typeSuperClassesMap  &,
                                GGS_typeClassInheritedMessagesMap  &) ;

  protected : void pr_parent_class_semantics_parser_1189_6_parse (galgas_scanner & _inLexique) ;

  protected : void pr_semantics_declaration_semantics_parser_1273_6_ (galgas_scanner &,
                                GGS_M_semanticsEntitiesForUse  &,
                                GGS_typeEntitiesToGenerateList  &,
                                const GGS_M_optionComponents  &,
                                GGS_typeTableNomRoutinesDeclarees  &,
                                GGS_typeTableEnAvant  &,
                                GGS_typeTableRoutinesAimplementer  &) ;

  protected : virtual sint16 select_semantics_parser_8 (galgas_scanner &) = 0 ;

  protected : virtual sint16 select_semantics_parser_9 (galgas_scanner &) = 0 ;

  protected : virtual sint16 select_repeat_semantics_parser_10 (galgas_scanner &) = 0 ;

  protected : void pr_semantics_declaration_semantics_parser_1273_6_importSemantics (galgas_scanner &,
                                GGS_ModelMap  &,
                                GGS_ActionMap  &,
                                GGS_M_semanticsEntitiesForUse  &,
                                GGS_typeTableNomRoutinesDeclarees  &,
                                GGS_typeTableEnAvant  &,
                                GGS_typeTableRoutinesAimplementer  &) ;

  protected : void pr_semantics_declaration_semantics_parser_1273_6_parse (galgas_scanner & _inLexique) ;

  protected : void pr_abstract_method_semantics_parser_1571_6_ (galgas_scanner &,
                                const GGS_bool &,
                                GGS_typeListeAttributsSemantiques  &,
                                GGS_typeEntitiesToGenerateList  &,
                                GGS_M_semanticsEntitiesForUse  &,
                                GGS_typeTableMethodes  &,
                                GGS_typeTableMethodesAimplementer  &,
                                GGS_typeTableEnAvant  &) ;

  protected : void pr_abstract_method_semantics_parser_1571_6_parse (galgas_scanner & _inLexique) ;

  protected : void pr_parse_method_semantics_parser_1607_6_ (galgas_scanner &,
                                const GGS_lstring  &,
                                const GGS_typeTableMethodes  &,
                                const GGS_typeListeAttributsSemantiques  &,
                                const GGS_typeTableMethodes  &,
                                const GGS_typeSuperClassesMap  &,
                                const GGS_typeClassInheritedMessagesMap  &,
                                const GGS_typeSemanticAttributesMap  &,
                                const GGS_bool &,
                                GGS_typeEntitiesToGenerateList  &,
                                GGS_M_semanticsEntitiesForUse  &,
                                GGS_typeTableEnAvant  &,
                                GGS_lstring  &,
                                GGS_typeInstructionList  &,
                                GGS_L_EXsignature  &,
                                GGS_typeListeTypesEtNomsArgMethode  &,
                                const GGS_M_optionComponents  &) ;

  protected : void pr_parse_method_semantics_parser_1607_6_parse (galgas_scanner & _inLexique) ;

  protected : void pr_non_abstract_method_semantics_parser_1691_6_ (galgas_scanner &,
                                const GGS_lstring  &,
                                const GGS_typeTableMethodes  &,
                                const GGS_typeListeAttributsSemantiques  &,
                                GGS_typeTableMethodes  &,
                                const GGS_typeSuperClassesMap  &,
                                const GGS_typeClassInheritedMessagesMap  &,
                                const GGS_typeSemanticAttributesMap  &,
                                const GGS_bool &,
                                GGS_typeEntitiesToGenerateList  &,
                                GGS_M_semanticsEntitiesForUse  &,
                                GGS_typeTableMethodesAimplementer  &,
                                GGS_typeTableEnAvant  &,
                                const GGS_M_optionComponents  &) ;

  protected : virtual sint16 select_semantics_parser_11 (galgas_scanner &) = 0 ;

  protected : virtual sint16 select_semantics_parser_12 (galgas_scanner &) = 0 ;

  protected : void pr_non_abstract_method_semantics_parser_1691_6_parse (galgas_scanner & _inLexique) ;

  protected : void pr_overrided_method_semantics_parser_1748_6_ (galgas_scanner &,
                                const GGS_lstring  &,
                                const GGS_typeTableMethodes  &,
                                const GGS_typeListeAttributsSemantiques  &,
                                GGS_typeTableMethodes  &,
                                const GGS_typeSuperClassesMap  &,
                                const GGS_typeClassInheritedMessagesMap  &,
                                const GGS_typeSemanticAttributesMap  &,
                                const GGS_bool &,
                                GGS_typeEntitiesToGenerateList  &,
                                GGS_M_semanticsEntitiesForUse  &,
                                GGS_typeTableMethodesAimplementer  &,
                                GGS_typeTableEnAvant  &,
                                const GGS_M_optionComponents  &) ;

  protected : virtual sint16 select_semantics_parser_13 (galgas_scanner &) = 0 ;

  protected : virtual sint16 select_semantics_parser_14 (galgas_scanner &) = 0 ;

  protected : void pr_overrided_method_semantics_parser_1748_6_parse (galgas_scanner & _inLexique) ;

  protected : void pr_formal_arguments_list_semantics_parser_1817_6_ (galgas_scanner &,
                                GGS_M_semanticsEntitiesForUse  &,
                                GGS_L_EXsignature  &,
                                GGS_typeVariablesMap  &,
                                GGS_typeListeTypesEtNomsArgMethode  &,
                                GGS_typeTableEnAvant  &,
                                GGS_L_signature  &) ;

  protected : virtual sint16 select_repeat_semantics_parser_15 (galgas_scanner &) = 0 ;

  protected : virtual sint16 select_semantics_parser_16 (galgas_scanner &) = 0 ;

  protected : virtual sint16 select_semantics_parser_17 (galgas_scanner &) = 0 ;

  protected : virtual sint16 select_semantics_parser_18 (galgas_scanner &) = 0 ;

  protected : void pr_formal_arguments_list_semantics_parser_1817_6_importGrammarForSemantics (galgas_scanner &,
                                GGS_L_signature  &) ;

  protected : void pr_formal_arguments_list_semantics_parser_1817_6_parse (galgas_scanner & _inLexique) ;

  protected : void pr_type_parsing_semantics_parser_1984_6_ (galgas_scanner &,
                                GGS_M_semanticsEntitiesForUse  &,
                                GGS_AC_galgasType  &,
                                GGS_lstring  &) ;

  protected : void pr_type_parsing_semantics_parser_1984_6_parse (galgas_scanner & _inLexique) ;

  protected : void pr_instruction_beginning_with_identifier_semantics_parser_2001_6_ (galgas_scanner &,
                                GGS_lstring  ,
                                GGS_typeVariablesMap  &,
                                GGS_typeInstructionList  &,
                                const GGS_M_optionComponents  &,
                                GGS_M_semanticsEntitiesForUse  &) ;

  protected : void pr_instruction_beginning_with_identifier_semantics_parser_2001_6_parse (galgas_scanner & _inLexique) ;

  protected : void pr_instruction_beginning_with_identifier_semantics_parser_2036_6_ (galgas_scanner &,
                                GGS_lstring  ,
                                GGS_typeVariablesMap  &,
                                GGS_typeInstructionList  &,
                                const GGS_M_optionComponents  &,
                                GGS_M_semanticsEntitiesForUse  &) ;

  protected : void pr_instruction_beginning_with_identifier_semantics_parser_2036_6_parse (galgas_scanner & _inLexique) ;

  protected : void pr_input_parameters_list_semantics_parser_2083_6_ (galgas_scanner &,
                                GGS_L_assignedVariables  &,
                                GGS_typeCplusPlusNameList  &,
                                GGS_typeListeAttributsSemantiques  ,
                                GGS_typeVariablesMap  &) ;

  protected : virtual sint16 select_repeat_semantics_parser_19 (galgas_scanner &) = 0 ;

  protected : virtual sint16 select_semantics_parser_20 (galgas_scanner &) = 0 ;

  protected : virtual sint16 select_semantics_parser_21 (galgas_scanner &) = 0 ;

  protected : void pr_input_parameters_list_semantics_parser_2083_6_parse (galgas_scanner & _inLexique) ;

  protected : void pr_instruction_beginning_with_identifier_semantics_parser_2158_6_ (galgas_scanner &,
                                GGS_lstring  ,
                                GGS_typeVariablesMap  &,
                                GGS_typeInstructionList  &,
                                const GGS_M_optionComponents  &,
                                GGS_M_semanticsEntitiesForUse  &) ;

  protected : virtual sint16 select_repeat_semantics_parser_22 (galgas_scanner &) = 0 ;

  protected : void pr_instruction_beginning_with_identifier_semantics_parser_2158_6_parse (galgas_scanner & _inLexique) ;

  protected : void pr_instruction_beginning_with_identifier_semantics_parser_2217_6_ (galgas_scanner &,
                                GGS_lstring  ,
                                GGS_typeVariablesMap  &,
                                GGS_typeInstructionList  &,
                                const GGS_M_optionComponents  &,
                                GGS_M_semanticsEntitiesForUse  &) ;

  protected : virtual sint16 select_repeat_semantics_parser_23 (galgas_scanner &) = 0 ;

  protected : void pr_instruction_beginning_with_identifier_semantics_parser_2217_6_parse (galgas_scanner & _inLexique) ;

  protected : void pr_instruction_beginning_with_identifier_semantics_parser_2276_6_ (galgas_scanner &,
                                GGS_lstring  ,
                                GGS_typeVariablesMap  &,
                                GGS_typeInstructionList  &,
                                const GGS_M_optionComponents  &,
                                GGS_M_semanticsEntitiesForUse  &) ;

  protected : void pr_instruction_beginning_with_identifier_semantics_parser_2276_6_parse (galgas_scanner & _inLexique) ;

  protected : void pr_instruction_beginning_with_identifier_semantics_parser_2303_6_ (galgas_scanner &,
                                GGS_lstring  ,
                                GGS_typeVariablesMap  &,
                                GGS_typeInstructionList  &,
                                const GGS_M_optionComponents  &,
                                GGS_M_semanticsEntitiesForUse  &) ;

  protected : void pr_instruction_beginning_with_identifier_semantics_parser_2303_6_parse (galgas_scanner & _inLexique) ;

  protected : void pr_actual_parameters_list_semantics_parser_2326_6_ (galgas_scanner &,
                                const GGS_L_EXsignature  &,
                                GGS_typeExpressionList  &,
                                GGS_typeVariablesMap  &,
                                const GGS_M_optionComponents  &,
                                GGS_M_semanticsEntitiesForUse  &,
                                GGS_typeInstructionList  &) ;

  protected : void pr_actual_parameters_list_semantics_parser_2326_6_parse (galgas_scanner & _inLexique) ;

  protected : void pr_parse_parameters_list_semantics_parser_2357_6_ (galgas_scanner &,
                                GGS_L_actualParametersSignature  &,
                                GGS_typeExpressionList  &,
                                GGS_typeVariablesMap  &,
                                const GGS_M_optionComponents  &,
                                GGS_M_semanticsEntitiesForUse  &) ;

  protected : virtual sint16 select_repeat_semantics_parser_24 (galgas_scanner &) = 0 ;

  protected : virtual sint16 select_semantics_parser_25 (galgas_scanner &) = 0 ;

  protected : void pr_parse_parameters_list_semantics_parser_2357_6_parse (galgas_scanner & _inLexique) ;

  protected : void pr_semantic_instructions_list_semantics_parser_2437_6_ (galgas_scanner &,
                                GGS_M_semanticsEntitiesForUse  &,
                                GGS_typeEntitiesToGenerateList  &,
                                const GGS_M_optionComponents  &,
                                GGS_typeVariablesMap  &,
                                GGS_typeInstructionList  &,
                                GGS_entityPropertyMap  &,
                                GGS_stringset  &,
                                GGS_callInstructionSharedPropertySignatureMap  &) ;

  protected : void pr_semantic_instructions_list_semantics_parser_2437_6_parse (galgas_scanner & _inLexique) ;

  protected : void pr_semantic_instruction_semantics_parser_2467_6_ (galgas_scanner &,
                                GGS_M_semanticsEntitiesForUse  &,
                                GGS_typeEntitiesToGenerateList  &,
                                const GGS_M_optionComponents  &,
                                GGS_typeVariablesMap  &,
                                GGS_typeInstructionList  &,
                                GGS_entityPropertyMap  &,
                                GGS_stringset  &,
                                GGS_callInstructionSharedPropertySignatureMap  &) ;

  protected : virtual sint16 select_semantics_parser_26 (galgas_scanner &) = 0 ;

  protected : virtual sint16 select_repeat_semantics_parser_27 (galgas_scanner &) = 0 ;

  protected : void pr_semantic_instruction_semantics_parser_2467_6_parse (galgas_scanner & _inLexique) ;

  protected : void pr_semantic_instruction_semantics_parser_2549_6_ (galgas_scanner &,
                                GGS_M_semanticsEntitiesForUse  &,
                                GGS_typeEntitiesToGenerateList  &,
                                const GGS_M_optionComponents  &,
                                GGS_typeVariablesMap  &,
                                GGS_typeInstructionList  &,
                                GGS_entityPropertyMap  &,
                                GGS_stringset  &,
                                GGS_callInstructionSharedPropertySignatureMap  &) ;

  protected : void pr_semantic_instruction_semantics_parser_2549_6_parse (galgas_scanner & _inLexique) ;

  protected : void pr_extract_instruction_semantics_parser_2594_6_ (galgas_scanner &,
                                GGS_M_semanticsEntitiesForUse  &,
                                GGS_typeEntitiesToGenerateList  &,
                                const GGS_M_optionComponents  &,
                                GGS_typeVariablesMap  &,
                                GGS_typeCplusPlusName  ,
                                GGS_lstring  ,
                                GGS_typeClassInheritedMessagesMap  ,
                                GGS_typeInstruction  &,
                                GGS_entityPropertyMap  &,
                                GGS_stringset  &,
                                GGS_callInstructionSharedPropertySignatureMap  &) ;

  protected : void pr_extract_instruction_semantics_parser_2594_6_parse (galgas_scanner & _inLexique) ;

  protected : void pr_extract_instruction_semantics_parser_2671_6_ (galgas_scanner &,
                                GGS_M_semanticsEntitiesForUse  &,
                                GGS_typeEntitiesToGenerateList  &,
                                const GGS_M_optionComponents  &,
                                GGS_typeVariablesMap  &,
                                GGS_typeCplusPlusName  ,
                                GGS_lstring  ,
                                GGS_typeClassInheritedMessagesMap  ,
                                GGS_typeInstruction  &,
                                GGS_entityPropertyMap  &,
                                GGS_stringset  &,
                                GGS_callInstructionSharedPropertySignatureMap  &) ;

  protected : virtual sint16 select_repeat_semantics_parser_28 (galgas_scanner &) = 0 ;

  protected : void pr_extract_instruction_semantics_parser_2671_6_parse (galgas_scanner & _inLexique) ;

  protected : void pr_semantic_instruction_semantics_parser_2771_6_ (galgas_scanner &,
                                GGS_M_semanticsEntitiesForUse  &,
                                GGS_typeEntitiesToGenerateList  &,
                                const GGS_M_optionComponents  &,
                                GGS_typeVariablesMap  &,
                                GGS_typeInstructionList  &,
                                GGS_entityPropertyMap  &,
                                GGS_stringset  &,
                                GGS_callInstructionSharedPropertySignatureMap  &) ;

  protected : void pr_semantic_instruction_semantics_parser_2771_6_parse (galgas_scanner & _inLexique) ;

  protected : void pr_semantic_instruction_semantics_parser_2810_6_ (galgas_scanner &,
                                GGS_M_semanticsEntitiesForUse  &,
                                GGS_typeEntitiesToGenerateList  &,
                                const GGS_M_optionComponents  &,
                                GGS_typeVariablesMap  &,
                                GGS_typeInstructionList  &,
                                GGS_entityPropertyMap  &,
                                GGS_stringset  &,
                                GGS_callInstructionSharedPropertySignatureMap  &) ;

  protected : virtual sint16 select_repeat_semantics_parser_29 (galgas_scanner &) = 0 ;

  protected : void pr_semantic_instruction_semantics_parser_2810_6_parse (galgas_scanner & _inLexique) ;

  protected : void pr_semantic_instruction_semantics_parser_2840_6_ (galgas_scanner &,
                                GGS_M_semanticsEntitiesForUse  &,
                                GGS_typeEntitiesToGenerateList  &,
                                const GGS_M_optionComponents  &,
                                GGS_typeVariablesMap  &,
                                GGS_typeInstructionList  &,
                                GGS_entityPropertyMap  &,
                                GGS_stringset  &,
                                GGS_callInstructionSharedPropertySignatureMap  &) ;

  protected : virtual sint16 select_repeat_semantics_parser_30 (galgas_scanner &) = 0 ;

  protected : void pr_semantic_instruction_semantics_parser_2840_6_parse (galgas_scanner & _inLexique) ;

  protected : void pr_instruction_beginning_with_identifier_semantics_parser_2872_6_ (galgas_scanner &,
                                GGS_lstring  ,
                                GGS_typeVariablesMap  &,
                                GGS_typeInstructionList  &,
                                const GGS_M_optionComponents  &,
                                GGS_M_semanticsEntitiesForUse  &) ;

  protected : void pr_instruction_beginning_with_identifier_semantics_parser_2872_6_parse (galgas_scanner & _inLexique) ;

  protected : void pr_semantic_instruction_semantics_parser_2907_6_ (galgas_scanner &,
                                GGS_M_semanticsEntitiesForUse  &,
                                GGS_typeEntitiesToGenerateList  &,
                                const GGS_M_optionComponents  &,
                                GGS_typeVariablesMap  &,
                                GGS_typeInstructionList  &,
                                GGS_entityPropertyMap  &,
                                GGS_stringset  &,
                                GGS_callInstructionSharedPropertySignatureMap  &) ;

  protected : void pr_semantic_instruction_semantics_parser_2907_6_parse (galgas_scanner & _inLexique) ;

  protected : void pr_semantic_instruction_semantics_parser_2956_6_ (galgas_scanner &,
                                GGS_M_semanticsEntitiesForUse  &,
                                GGS_typeEntitiesToGenerateList  &,
                                const GGS_M_optionComponents  &,
                                GGS_typeVariablesMap  &,
                                GGS_typeInstructionList  &,
                                GGS_entityPropertyMap  &,
                                GGS_stringset  &,
                                GGS_callInstructionSharedPropertySignatureMap  &) ;

  protected : virtual sint16 select_semantics_parser_31 (galgas_scanner &) = 0 ;

  protected : void pr_semantic_instruction_semantics_parser_2956_6_parse (galgas_scanner & _inLexique) ;

  protected : void pr_semantic_instruction_semantics_parser_3027_6_ (galgas_scanner &,
                                GGS_M_semanticsEntitiesForUse  &,
                                GGS_typeEntitiesToGenerateList  &,
                                const GGS_M_optionComponents  &,
                                GGS_typeVariablesMap  &,
                                GGS_typeInstructionList  &,
                                GGS_entityPropertyMap  &,
                                GGS_stringset  &,
                                GGS_callInstructionSharedPropertySignatureMap  &) ;

  protected : void pr_semantic_instruction_semantics_parser_3027_6_parse (galgas_scanner & _inLexique) ;

  protected : void pr_semantic_instruction_semantics_parser_3055_6_ (galgas_scanner &,
                                GGS_M_semanticsEntitiesForUse  &,
                                GGS_typeEntitiesToGenerateList  &,
                                const GGS_M_optionComponents  &,
                                GGS_typeVariablesMap  &,
                                GGS_typeInstructionList  &,
                                GGS_entityPropertyMap  &,
                                GGS_stringset  &,
                                GGS_callInstructionSharedPropertySignatureMap  &) ;

  protected : void pr_semantic_instruction_semantics_parser_3055_6_parse (galgas_scanner & _inLexique) ;

  protected : void pr_semantic_instruction_semantics_parser_3103_6_ (galgas_scanner &,
                                GGS_M_semanticsEntitiesForUse  &,
                                GGS_typeEntitiesToGenerateList  &,
                                const GGS_M_optionComponents  &,
                                GGS_typeVariablesMap  &,
                                GGS_typeInstructionList  &,
                                GGS_entityPropertyMap  &,
                                GGS_stringset  &,
                                GGS_callInstructionSharedPropertySignatureMap  &) ;

  protected : virtual sint16 select_semantics_parser_32 (galgas_scanner &) = 0 ;

  protected : virtual sint16 select_repeat_semantics_parser_33 (galgas_scanner &) = 0 ;

  protected : void pr_semantic_instruction_semantics_parser_3103_6_parse (galgas_scanner & _inLexique) ;

  protected : void pr_semantic_instruction_semantics_parser_3170_6_ (galgas_scanner &,
                                GGS_M_semanticsEntitiesForUse  &,
                                GGS_typeEntitiesToGenerateList  &,
                                const GGS_M_optionComponents  &,
                                GGS_typeVariablesMap  &,
                                GGS_typeInstructionList  &,
                                GGS_entityPropertyMap  &,
                                GGS_stringset  &,
                                GGS_callInstructionSharedPropertySignatureMap  &) ;

  protected : void pr_semantic_instruction_semantics_parser_3170_6_parse (galgas_scanner & _inLexique) ;

  protected : void pr_semantic_instruction_semantics_parser_3206_6_ (galgas_scanner &,
                                GGS_M_semanticsEntitiesForUse  &,
                                GGS_typeEntitiesToGenerateList  &,
                                const GGS_M_optionComponents  &,
                                GGS_typeVariablesMap  &,
                                GGS_typeInstructionList  &,
                                GGS_entityPropertyMap  &,
                                GGS_stringset  &,
                                GGS_callInstructionSharedPropertySignatureMap  &) ;

  protected : virtual sint16 select_repeat_semantics_parser_34 (galgas_scanner &) = 0 ;

  protected : virtual sint16 select_semantics_parser_35 (galgas_scanner &) = 0 ;

  protected : void pr_semantic_instruction_semantics_parser_3206_6_parse (galgas_scanner & _inLexique) ;

  protected : void pr_semantic_instruction_semantics_parser_3298_6_ (galgas_scanner &,
                                GGS_M_semanticsEntitiesForUse  &,
                                GGS_typeEntitiesToGenerateList  &,
                                const GGS_M_optionComponents  &,
                                GGS_typeVariablesMap  &,
                                GGS_typeInstructionList  &,
                                GGS_entityPropertyMap  &,
                                GGS_stringset  &,
                                GGS_callInstructionSharedPropertySignatureMap  &) ;

  protected : virtual sint16 select_repeat_semantics_parser_36 (galgas_scanner &) = 0 ;

  protected : virtual sint16 select_repeat_semantics_parser_37 (galgas_scanner &) = 0 ;

  protected : void pr_semantic_instruction_semantics_parser_3298_6_parse (galgas_scanner & _inLexique) ;

  protected : void pr_semantic_instruction_semantics_parser_3391_6_ (galgas_scanner &,
                                GGS_M_semanticsEntitiesForUse  &,
                                GGS_typeEntitiesToGenerateList  &,
                                const GGS_M_optionComponents  &,
                                GGS_typeVariablesMap  &,
                                GGS_typeInstructionList  &,
                                GGS_entityPropertyMap  &,
                                GGS_stringset  &,
                                GGS_callInstructionSharedPropertySignatureMap  &) ;

  protected : void pr_semantic_instruction_semantics_parser_3391_6_parse (galgas_scanner & _inLexique) ;

  protected : void pr_semantic_instruction_semantics_parser_3480_6_ (galgas_scanner &,
                                GGS_M_semanticsEntitiesForUse  &,
                                GGS_typeEntitiesToGenerateList  &,
                                const GGS_M_optionComponents  &,
                                GGS_typeVariablesMap  &,
                                GGS_typeInstructionList  &,
                                GGS_entityPropertyMap  &,
                                GGS_stringset  &,
                                GGS_callInstructionSharedPropertySignatureMap  &) ;

  protected : virtual sint16 select_semantics_parser_38 (galgas_scanner &) = 0 ;

  protected : void pr_semantic_instruction_semantics_parser_3480_6_parse (galgas_scanner & _inLexique) ;

  protected : void pr_semantic_instruction_semantics_parser_3551_6_ (galgas_scanner &,
                                GGS_M_semanticsEntitiesForUse  &,
                                GGS_typeEntitiesToGenerateList  &,
                                const GGS_M_optionComponents  &,
                                GGS_typeVariablesMap  &,
                                GGS_typeInstructionList  &,
                                GGS_entityPropertyMap  &,
                                GGS_stringset  &,
                                GGS_callInstructionSharedPropertySignatureMap  &) ;

  protected : virtual sint16 select_repeat_semantics_parser_39 (galgas_scanner &) = 0 ;

  protected : virtual sint16 select_semantics_parser_40 (galgas_scanner &) = 0 ;

  protected : void pr_semantic_instruction_semantics_parser_3551_6_parse (galgas_scanner & _inLexique) ;

  protected : void pr_parse_match_operand_semantics_parser_3648_6_ (galgas_scanner &,
                                GGS_typeVariablesMap  &,
                                GGS_typeCplusPlusName  &,
                                GGS_lstring  &,
                                GGS_location  &,
                                GGS_bool &,
                                GGS_enumConstantMap  &) ;

  protected : void pr_parse_match_operand_semantics_parser_3648_6_parse (galgas_scanner & _inLexique) ;

  protected : void pr_parse_match_case_semantics_parser_3686_6_ (galgas_scanner &,
                                GGS_M_semanticsEntitiesForUse  &,
                                GGS_typeVariablesMap  &,
                                GGS_lstring  ,
                                GGS_location  ,
                                GGS_bool ,
                                GGS_enumConstantMap  ,
                                GGS_lstring  &) ;

  protected : void pr_parse_match_case_semantics_parser_3686_6_parse (galgas_scanner & _inLexique) ;

  protected : void pr_parse_match_case_semantics_parser_3737_6_ (galgas_scanner &,
                                GGS_M_semanticsEntitiesForUse  &,
                                GGS_typeVariablesMap  &,
                                GGS_lstring  ,
                                GGS_location  ,
                                GGS_bool ,
                                GGS_enumConstantMap  ,
                                GGS_lstring  &) ;

  protected : void pr_parse_match_case_semantics_parser_3737_6_parse (galgas_scanner & _inLexique) ;

  protected : void pr_semantic_instruction_semantics_parser_3758_6_ (galgas_scanner &,
                                GGS_M_semanticsEntitiesForUse  &,
                                GGS_typeEntitiesToGenerateList  &,
                                const GGS_M_optionComponents  &,
                                GGS_typeVariablesMap  &,
                                GGS_typeInstructionList  &,
                                GGS_entityPropertyMap  &,
                                GGS_stringset  &,
                                GGS_callInstructionSharedPropertySignatureMap  &) ;

  protected : virtual sint16 select_repeat_semantics_parser_41 (galgas_scanner &) = 0 ;

  protected : void pr_semantic_instruction_semantics_parser_3758_6_parse (galgas_scanner & _inLexique) ;

  protected : void pr_semantic_instructions_list_no_verif_semantics_parser_3881_6_ (galgas_scanner &,
                                GGS_M_semanticsEntitiesForUse  &,
                                GGS_typeEntitiesToGenerateList  &,
                                const GGS_M_optionComponents  &,
                                GGS_typeVariablesMap  &,
                                GGS_typeInstructionList  &,
                                GGS_entityPropertyMap  &,
                                GGS_stringset  &,
                                GGS_callInstructionSharedPropertySignatureMap  &) ;

  protected : virtual sint16 select_repeat_semantics_parser_42 (galgas_scanner &) = 0 ;

  protected : void pr_semantic_instructions_list_no_verif_semantics_parser_3881_6_parse (galgas_scanner & _inLexique) ;

  protected : void pr_optional_assignment_semantics_parser_3910_6_ (galgas_scanner &,
                                const GGS_lstring  &,
                                const GGS_lstring  &,
                                const GGS_typeCplusPlusName  &,
                                const GGS_AC_galgasType  &,
                                GGS_typeVariablesMap  &,
                                GGS_typeInstructionList  &,
                                const GGS_M_optionComponents  &,
                                GGS_M_semanticsEntitiesForUse  &) ;

  protected : void pr_optional_assignment_semantics_parser_3910_6_parse (galgas_scanner & _inLexique) ;

  protected : void pr_optional_assignment_semantics_parser_3926_6_ (galgas_scanner &,
                                const GGS_lstring  &,
                                const GGS_lstring  &,
                                const GGS_typeCplusPlusName  &,
                                const GGS_AC_galgasType  &,
                                GGS_typeVariablesMap  &,
                                GGS_typeInstructionList  &,
                                const GGS_M_optionComponents  &,
                                GGS_M_semanticsEntitiesForUse  &) ;

  protected : void pr_optional_assignment_semantics_parser_3926_6_parse (galgas_scanner & _inLexique) ;

  protected : void pr_optional_assignment_semantics_parser_3958_6_ (galgas_scanner &,
                                const GGS_lstring  &,
                                const GGS_lstring  &,
                                const GGS_typeCplusPlusName  &,
                                const GGS_AC_galgasType  &,
                                GGS_typeVariablesMap  &,
                                GGS_typeInstructionList  &,
                                const GGS_M_optionComponents  &,
                                GGS_M_semanticsEntitiesForUse  &) ;

  protected : void pr_optional_assignment_semantics_parser_3958_6_parse (galgas_scanner & _inLexique) ;

  protected : void pr_semantics_declaration_semantics_parser_3998_6_ (galgas_scanner &,
                                GGS_M_semanticsEntitiesForUse  &,
                                GGS_typeEntitiesToGenerateList  &,
                                const GGS_M_optionComponents  &,
                                GGS_typeTableNomRoutinesDeclarees  &,
                                GGS_typeTableEnAvant  &,
                                GGS_typeTableRoutinesAimplementer  &) ;

  protected : virtual sint16 select_semantics_parser_43 (galgas_scanner &) = 0 ;

  protected : virtual sint16 select_repeat_semantics_parser_44 (galgas_scanner &) = 0 ;

  protected : void pr_semantics_declaration_semantics_parser_3998_6_importSemantics (galgas_scanner &,
                                GGS_ModelMap  &,
                                GGS_ActionMap  &,
                                GGS_M_semanticsEntitiesForUse  &,
                                GGS_typeTableNomRoutinesDeclarees  &,
                                GGS_typeTableEnAvant  &,
                                GGS_typeTableRoutinesAimplementer  &) ;

  protected : void pr_semantics_declaration_semantics_parser_3998_6_parse (galgas_scanner & _inLexique) ;

  protected : void pr_semantics_declaration_semantics_parser_4117_6_ (galgas_scanner &,
                                GGS_M_semanticsEntitiesForUse  &,
                                GGS_typeEntitiesToGenerateList  &,
                                const GGS_M_optionComponents  &,
                                GGS_typeTableNomRoutinesDeclarees  &,
                                GGS_typeTableEnAvant  &,
                                GGS_typeTableRoutinesAimplementer  &) ;

  protected : virtual sint16 select_semantics_parser_45 (galgas_scanner &) = 0 ;

  protected : virtual sint16 select_repeat_semantics_parser_46 (galgas_scanner &) = 0 ;

  protected : virtual sint16 select_repeat_semantics_parser_47 (galgas_scanner &) = 0 ;

  protected : virtual sint16 select_semantics_parser_48 (galgas_scanner &) = 0 ;

  protected : void pr_semantics_declaration_semantics_parser_4117_6_importSemantics (galgas_scanner &,
                                GGS_ModelMap  &,
                                GGS_ActionMap  &,
                                GGS_M_semanticsEntitiesForUse  &,
                                GGS_typeTableNomRoutinesDeclarees  &,
                                GGS_typeTableEnAvant  &,
                                GGS_typeTableRoutinesAimplementer  &) ;

  protected : void pr_semantics_declaration_semantics_parser_4117_6_parse (galgas_scanner & _inLexique) ;

  protected : void pr_ex_map_method_semantics_parser_4682_6_ (galgas_scanner &,
                                GGS_lstring  &,
                                GGS_lstring  &) ;

  protected : void pr_ex_map_method_semantics_parser_4682_6_parse (galgas_scanner & _inLexique) ;

  protected : void pr_map_method_semantics_parser_4694_6_ (galgas_scanner &,
                                GGS_lstring  &,
                                GGS_lstring  &,
                                GGS_lstring  &) ;

  protected : virtual sint16 select_semantics_parser_49 (galgas_scanner &) = 0 ;

  protected : void pr_map_method_semantics_parser_4694_6_parse (galgas_scanner & _inLexique) ;

  protected : void pr_semantics_declaration_semantics_parser_4717_6_ (galgas_scanner &,
                                GGS_M_semanticsEntitiesForUse  &,
                                GGS_typeEntitiesToGenerateList  &,
                                const GGS_M_optionComponents  &,
                                GGS_typeTableNomRoutinesDeclarees  &,
                                GGS_typeTableEnAvant  &,
                                GGS_typeTableRoutinesAimplementer  &) ;

  protected : virtual sint16 select_semantics_parser_50 (galgas_scanner &) = 0 ;

  protected : void pr_semantics_declaration_semantics_parser_4717_6_importSemantics (galgas_scanner &,
                                GGS_ModelMap  &,
                                GGS_ActionMap  &,
                                GGS_M_semanticsEntitiesForUse  &,
                                GGS_typeTableNomRoutinesDeclarees  &,
                                GGS_typeTableEnAvant  &,
                                GGS_typeTableRoutinesAimplementer  &) ;

  protected : void pr_semantics_declaration_semantics_parser_4717_6_parse (galgas_scanner & _inLexique) ;

  protected : void pr_semantics_declaration_semantics_parser_4829_6_ (galgas_scanner &,
                                GGS_M_semanticsEntitiesForUse  &,
                                GGS_typeEntitiesToGenerateList  &,
                                const GGS_M_optionComponents  &,
                                GGS_typeTableNomRoutinesDeclarees  &,
                                GGS_typeTableEnAvant  &,
                                GGS_typeTableRoutinesAimplementer  &) ;

  protected : virtual sint16 select_semantics_parser_51 (galgas_scanner &) = 0 ;

  protected : virtual sint16 select_repeat_semantics_parser_52 (galgas_scanner &) = 0 ;

  protected : virtual sint16 select_semantics_parser_53 (galgas_scanner &) = 0 ;

  protected : void pr_semantics_declaration_semantics_parser_4829_6_importSemantics (galgas_scanner &,
                                GGS_ModelMap  &,
                                GGS_ActionMap  &,
                                GGS_M_semanticsEntitiesForUse  &,
                                GGS_typeTableNomRoutinesDeclarees  &,
                                GGS_typeTableEnAvant  &,
                                GGS_typeTableRoutinesAimplementer  &) ;

  protected : void pr_semantics_declaration_semantics_parser_4829_6_parse (galgas_scanner & _inLexique) ;

  protected : void pr_attributes_definition_list_semantics_parser_4981_6_ (galgas_scanner &,
                                GGS_typeListModel  &,
                                GGS_typeSemanticAttributesMap  &,
                                GGS_typeListeAttributsSemantiques  &,
                                GGS_typeListeAttributsSemantiques  &,
                                GGS_L_nameWithType  &,
                                GGS_M_semanticsEntitiesForUse  &) ;

  protected : virtual sint16 select_repeat_semantics_parser_54 (galgas_scanner &) = 0 ;

  protected : void pr_attributes_definition_list_semantics_parser_4981_6_parse (galgas_scanner & _inLexique) ;

  protected : void pr_semantics_declaration_semantics_parser_5019_6_ (galgas_scanner &,
                                GGS_M_semanticsEntitiesForUse  &,
                                GGS_typeEntitiesToGenerateList  &,
                                const GGS_M_optionComponents  &,
                                GGS_typeTableNomRoutinesDeclarees  &,
                                GGS_typeTableEnAvant  &,
                                GGS_typeTableRoutinesAimplementer  &) ;

  protected : virtual sint16 select_repeat_semantics_parser_55 (galgas_scanner &) = 0 ;

  protected : virtual sint16 select_repeat_semantics_parser_56 (galgas_scanner &) = 0 ;

  protected : virtual sint16 select_semantics_parser_57 (galgas_scanner &) = 0 ;

  protected : virtual sint16 select_repeat_semantics_parser_58 (galgas_scanner &) = 0 ;

  protected : void pr_semantics_declaration_semantics_parser_5019_6_importSemantics (galgas_scanner &,
                                GGS_ModelMap  &,
                                GGS_ActionMap  &,
                                GGS_M_semanticsEntitiesForUse  &,
                                GGS_typeTableNomRoutinesDeclarees  &,
                                GGS_typeTableEnAvant  &,
                                GGS_typeTableRoutinesAimplementer  &) ;

  protected : void pr_semantics_declaration_semantics_parser_5019_6_parse (galgas_scanner & _inLexique) ;

  protected : void pr_formal_argument_type_semantics_parser_5292_6_ (galgas_scanner &,
                                GGS_M_semanticsEntitiesForUse  &,
                                GGS_AC_galgasType  &,
                                GGS_typeTableEnAvant  &,
                                GGS_lstring  &) ;

  protected : void pr_formal_argument_type_semantics_parser_5292_6_importGrammarForSemantics (galgas_scanner &,
                                GGS_lstring  &) ;

  protected : void pr_formal_argument_type_semantics_parser_5292_6_parse (galgas_scanner & _inLexique) ;

  protected : void pr_formal_argument_type_semantics_parser_5314_6_ (galgas_scanner &,
                                GGS_M_semanticsEntitiesForUse  &,
                                GGS_AC_galgasType  &,
                                GGS_typeTableEnAvant  &,
                                GGS_lstring  &) ;

  protected : void pr_formal_argument_type_semantics_parser_5314_6_importGrammarForSemantics (galgas_scanner &,
                                GGS_lstring  &) ;

  protected : void pr_formal_argument_type_semantics_parser_5314_6_parse (galgas_scanner & _inLexique) ;

  protected : void pr_formal_argument_type_semantics_parser_5339_6_ (galgas_scanner &,
                                GGS_M_semanticsEntitiesForUse  &,
                                GGS_AC_galgasType  &,
                                GGS_typeTableEnAvant  &,
                                GGS_lstring  &) ;

  protected : void pr_formal_argument_type_semantics_parser_5339_6_importGrammarForSemantics (galgas_scanner &,
                                GGS_lstring  &) ;

  protected : void pr_formal_argument_type_semantics_parser_5339_6_parse (galgas_scanner & _inLexique) ;

  protected : void pr_formal_argument_type_semantics_parser_5364_6_ (galgas_scanner &,
                                GGS_M_semanticsEntitiesForUse  &,
                                GGS_AC_galgasType  &,
                                GGS_typeTableEnAvant  &,
                                GGS_lstring  &) ;

  protected : void pr_formal_argument_type_semantics_parser_5364_6_importGrammarForSemantics (galgas_scanner &,
                                GGS_lstring  &) ;

  protected : void pr_formal_argument_type_semantics_parser_5364_6_parse (galgas_scanner & _inLexique) ;

  protected : void pr_semantics_declaration_semantics_parser_5395_6_ (galgas_scanner &,
                                GGS_M_semanticsEntitiesForUse  &,
                                GGS_typeEntitiesToGenerateList  &,
                                const GGS_M_optionComponents  &,
                                GGS_typeTableNomRoutinesDeclarees  &,
                                GGS_typeTableEnAvant  &,
                                GGS_typeTableRoutinesAimplementer  &) ;

  protected : void pr_semantics_declaration_semantics_parser_5395_6_importSemantics (galgas_scanner &,
                                GGS_ModelMap  &,
                                GGS_ActionMap  &,
                                GGS_M_semanticsEntitiesForUse  &,
                                GGS_typeTableNomRoutinesDeclarees  &,
                                GGS_typeTableEnAvant  &,
                                GGS_typeTableRoutinesAimplementer  &) ;

  protected : void pr_semantics_declaration_semantics_parser_5395_6_parse (galgas_scanner & _inLexique) ;

  protected : void pr_semantics_declaration_semantics_parser_5458_6_ (galgas_scanner &,
                                GGS_M_semanticsEntitiesForUse  &,
                                GGS_typeEntitiesToGenerateList  &,
                                const GGS_M_optionComponents  &,
                                GGS_typeTableNomRoutinesDeclarees  &,
                                GGS_typeTableEnAvant  &,
                                GGS_typeTableRoutinesAimplementer  &) ;

  protected : virtual sint16 select_repeat_semantics_parser_59 (galgas_scanner &) = 0 ;

  protected : virtual sint16 select_repeat_semantics_parser_60 (galgas_scanner &) = 0 ;

  protected : virtual sint16 select_repeat_semantics_parser_61 (galgas_scanner &) = 0 ;

  protected : void pr_semantics_declaration_semantics_parser_5458_6_importSemantics (galgas_scanner &,
                                GGS_ModelMap  &,
                                GGS_ActionMap  &,
                                GGS_M_semanticsEntitiesForUse  &,
                                GGS_typeTableNomRoutinesDeclarees  &,
                                GGS_typeTableEnAvant  &,
                                GGS_typeTableRoutinesAimplementer  &) ;

  protected : void pr_semantics_declaration_semantics_parser_5458_6_parse (galgas_scanner & _inLexique) ;

} ;

//---------------------------------------------------------------------------*

#endif
