//---------------------------------------------------------------------------*
//                                                                           *
//                  File 'include_C_grammarInstruction.h'                    *
//                 Generated by version GALGAS_BETA_VERSION                  *
//                     january 23th, 2010, at 19h1'46"                       *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

//---------------------------------------------------------------------------*
//                                                                           *
//                abstract class 'cPtr_C_grammarInstruction'                 *
//                                                                           *
//---------------------------------------------------------------------------*

class cPtr_C_grammarInstruction : public cPtr_typeInstruction {
  private : typedef cPtr_typeInstruction inherited ;
//--- START OF USER ZONE 2

  public : virtual void
  generateInstruction (AC_OutputStream & inCppFile,
                       const C_String & inTargetFileName,
                       PMSInt32 & ioPrototypeIndex,
                       const bool inGenerateDebug,
                       const bool inGenerateSemanticInstructions) const ;

public : virtual bool isLexiqueFormalArgumentUsed (const bool inGenerateSemanticInstructions) const ;
public : virtual bool formalArgumentIsUsed (const GGS_typeCplusPlusName & inArgumentCppName,
                                            const bool inGenerateSemanticInstructions) const ;

  public : virtual bool
  formalCurrentObjectArgumentIsUsed (void) const ;

//--- END OF USER ZONE 2

//--- Constructor
  public : cPtr_C_grammarInstruction (const GGS_bool& ,
                                const GGS_typeExpression & ,
                                const GGS_lstring & ,
                                const GGS_typeExpressionList & ,
                                const GGS_lstring & ,
                                const GGS_lstring & ,
                                const GGS_typeCplusPlusName & ,
                                const GGS_typeExpression & ,
                                const GGS_typeExpression & 
                                COMMA_LOCATION_ARGS) ;

//--- Attributes
  public : GGS_bool mSourceIsFile ;
  public : GGS_typeExpression  mSourceExpression ;
  public : GGS_lstring  mGrammarName ;
  public : GGS_typeExpressionList  mExpressionsList ;
  public : GGS_lstring  mAltSymbol ;
  public : GGS_lstring  mLexiqueClassName ;
  public : GGS_typeCplusPlusName  mSentStringName ;
  public : GGS_typeExpression  mDependencyFileExtension ;
  public : GGS_typeExpression  mDependancyFilePath ;
//--- Class message
  public : virtual const char * instanceMessage (void) const ;
  public : static const char * _static_message (void) ;

//--- Method for 'description' reader
  public : virtual void
  appendForDescription (C_String & ioString,
                        const PMSInt32 inIndentation) const ;

//--- Comparison
  public : virtual bool
  isEqualToObject (const cPtr__AC_galgas_class * inOperand) const ;

//--- Galgas RTTI
  public : virtual AC_galgasClassRunTimeInformationEX * galgasRTTI (void) const ;

//--- Make clone
  public : virtual cPtr__AC_galgas_class * makeClone (void) const ;
} ;

//---------------------------------------------------------------------------*

