#---------------------------------------------------------------*

all:
	$(MAKE) -f makefile_LL1.mke all
#	$(MAKE) -f makefile_SLR.mke all
#	$(MAKE) -f makefile_LR1.mke all

#---------------------------------------------------------------*

clean:
	$(MAKE) -f makefile_LL1.mke clean
#	$(MAKE) -f makefile_SLR.mke clean
#	$(MAKE) -f makefile_LR1.mke clean

#---------------------------------------------------------------*

install:
	$(MAKE) -f makefile_LL1.mke install
#	$(MAKE) -f makefile_SLR.mke install
#	$(MAKE) -f makefile_LR1.mke install

#---------------------------------------------------------------*

