#---------------------------------------------------------------*
#                                                               *
# MAKEFILE for building galgas LL1, SLR, LR1 command line tools *
#                                                               *
#---------------------------------------------------------------*

all:
	$(MAKE) -f makefile_LL1 all
	$(MAKE) -f makefile_SLR all
	$(MAKE) -f makefile_LR1 all

#---------------------------------------------------------------*

clean:
	$(MAKE) -f makefile_LL1 clean
	$(MAKE) -f makefile_SLR clean
	$(MAKE) -f makefile_LR1 clean

#---------------------------------------------------------------*

install:
	$(MAKE) -f makefile_LL1 install
	$(MAKE) -f makefile_SLR install
	$(MAKE) -f makefile_LR1 install

#---------------------------------------------------------------*

install_debug:
	$(MAKE) -f makefile_LL1 install_debug
	$(MAKE) -f makefile_SLR install_debug
	$(MAKE) -f makefile_LR1 install_debug

#---------------------------------------------------------------*

